seleniumbase/SeleniumBase

- integrations/docker/docker_requirements.txt
- integrations/docker/docker_setup.py
- integrations/selenium_grid/start-selenium-node.bat
- integrations/selenium_grid/start-selenium-server.sh
- requirements.txt
- seleniumbase/core/selenium_launcher.py
- setup.py
Upgrade to Selenium 2.50.0 (SeleniumBase 1.1.21)
> Upgrade to Selenium 2.50.0 (SeleniumBase 1.1.21)

- README.md
- examples/my_first_test.py
- examples/test_fail.py
- integrations/docker/docker_setup.py
- seleniumbase/core/selenium_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Mostly shortening some methods such as wait_for_element_visible(), wait_for_text_visible(), and wait_for_link_text_visible() to wait_for_element(), wait_for_text(), and wait_for_link_text(). Then updating the example tests and the ReadMe to use the shortened version.
> BaseCase improvements

- requirements.txt
- setup.py
The latest Firefox won't work with the previous version.
> Use latest selenium

- README.md
- examples/my_first_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- setup.py
Shortening method names: find_element(), find_text(), find_link_text()
Adding the get_text() method to simplify find_element().text
Updating a nose plugin
Use the latest version of selenium
Update the docs
> Framework updates

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
* Getting jQuery from the source
* Adding the slow_scroll_to() method, which is used in demo_mode
* Simplifying some method calls
> jQuery updates and slow scrolling

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Highlights is a very cool feature that allows spectators watching automation in demo_mode to see where the clicks will happen before they happen.
> Highlights for demo mode

- examples/masterqa_test.py
- seleniumbase/__init__.py
- seleniumbase/config/settings.py
- seleniumbase/masterqa/README.md
- seleniumbase/masterqa/master_qa.py
- setup.py
MasterQA is the ultimate QA experience. It combines the speed & robustness of automation with the flexibility of having human eyes to visually verify web pages as needed. After automation has done the bulk of the work for you, such as logging into a website, typing text, and clicking buttons, a simple method call creates a pop-up to ask the user whether or not the current page is acceptable. At the end of the test run, you'll receive a full report of the test results (with logs and screenshots) so that you can pass that information on to whoever is in charge of fixing the bugs. Manual QA will never be the same again.
> Integrate MasterQA with SeleniumBase (Augmented QA Mode)

- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
The default Demo Mode sleep value was changed to make things go a little faster.
Also adding the ability to set the number of highlight loops from the command line. (--highlights=NUMBER), as well as from the settings.py configuration file.
> Defaults update

- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Use the latest version of jQuery and don't block Javascript content when using WebDriver.
> jQuery update

- seleniumbase/masterqa/master_qa.py
- setup.py
Fixing a bug that was causing masterqa verifications to fail on chrome
> Fixing a bug with masterqa when using chrome

- Dockerfile
- requirements.txt
- server_requirements.txt
- setup.py
The Docker version of SeleniumBase stopped working for Chromedriver, so I fixed it.
> Docker fix

- Dockerfile
- integrations/docker/run_docker_test_in_phantomjs.sh
- integrations/linux/Linuxfile.sh
- setup.py
Upgrading to the latest version of PhantomJS for Docker and Linux runs.
> Phantomjs update

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
> Add double click method

- seleniumbase/masterqa/master_qa.py
- setup.py
Fix a bug when running MasterQA on Chrome
> Chrome masterqa fix

- README.md
- help_docs/mysql_installation.md
- server_setup.py
- setup.py
ReadMe updates and installation output changes
> ReadMe updates and installation output changes

- Dockerfile
- README.md
- requirements.txt
- server_requirements.txt
- server_setup.py
- setup.py
* Upgrading setuptools to version 34.3.2
* Making sure reinstallation goes smoothly
> Version upgrades

- help_docs/method_summary.md
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/masterqa/master_qa.py
- server_setup.py
- setup.py
Mostly adding SeleniumBase methods for making things easier, such as selecting options from an HTML "select" dropdown.
Also making a few updates to MasterQA
> Mostly adding methods. Select dropdown control. MasterQA updates.

- integrations/selenium_grid/grid-hub
- integrations/selenium_grid/grid-node
- seleniumbase/core/selenium_launcher.py
- server_setup.py
- setup.py
Update grid server to version 3 if Selenium 3 is installed
> Update grid server to version 3 if Selenium 3 is installed

- README.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/fixtures/xpath_to_css.py
- server_setup.py
- setup.py
Improve xpath usability.
Adding more methods.
> Improve xpath usability. Adding more methods.

- integrations/selenium_ide/convert_ide.py
- server_setup.py
- setup.py
> Update selenium ide converter

- README.md
- seleniumbase/plugins/pytest_plugin.py
- server_setup.py
- setup.py
> add pytest plugin entry point so does not require coping conftest.py

- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- server_setup.py
- setup.py
Add timeout_multiplier option to boost default timeout lengths
> Add timeout_multiplier option to boost default timeout lengths

- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- server_setup.py
- setup.py
Better error handling for Pytest teardowns
> Better error handling for Pytest teardowns

- seleniumbase/core/browser_launcher.py
- setup.py
Disable feature where Chrome asks to save passwords. (The pop-up breaks Selenium scripts)
> Dont ask to save passwords

- Dockerfile
Hi Michael,
This is a proposal to make the shell scripts executable on Dockerfile during the docker build process itself to ease the way we are trying to call the files and keep them ready for any demo.
You may please advise in case of any other thoughts.
Regards,
Revant
> Docker File update

- README.md
- examples/masterqa_test.py
- examples/my_test_suite.py
- examples/rate_limiting_test.py
- examples/setup.cfg
- help_docs/requirements_installation.md
- seleniumbase/core/mysql.py
- seleniumbase/core/selenium_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/masterqa/master_qa.py
- seleniumbase/plugins/selenium_plugin.py
- server_setup.py
- setup.cfg
- setup.py
Making the jump to Python 3! (You can still use Python 2.7!) Both versions are now supported.
> Python 3 Compatibility

- _config.yml
- requirements.txt
- server_requirements.txt
- server_setup.py
- setup.py
Removing urllib3 from requirements. It's no longer used anywhere in SeleniumBase.
> Remove unused requirement

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Scroll to page objects automatically before interacting with them.
> Test Reliability

- .travis.yml
- examples/gui_test_runner.py
- requirements.txt
- seleniumbase/common/encryption.py
- seleniumbase/common/obfuscate.py
- seleniumbase/common/unobfuscate.py
- seleniumbase/config/settings.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/s3_manager.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- server_requirements.txt
- server_setup.py
- setup.py
Improve Reliability
Better exception handling.
Update default timeouts.
Use flake8==3.5.0
> Improve Reliability

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- server_setup.py
- setup.py
Adding methods for testing analytics software:
It's easy to use JavaScript to create a referral link to any page from any page. This generates real referral traffic for testing analytics software.
> Adding methods for testing analytics software

- README.md
- _config.yml
- help_docs/before_installation.md
- help_docs/method_summary.md
- help_docs/requirements_installation.md
- seleniumbase/config/settings.py
- server_setup.py
- setup.py
Updating the settings page.
Updating installation instructions.
> Settings overhaul

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Not all HTML <a> tags have an href. Some might only have an ng-click instead.
> Fix link_text clicking bug

- .travis.yml
- README.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Fix an edge case with clicking a link hidden in a dropdown menu.
> Fix an edge case with clicking a link hidden in a dropdown menu.

- requirements.txt
- server_requirements.txt
- server_setup.py
- setup.py
Update pytest version to 3.4.2
> Update pytest version to 3.4.2

- help_docs/install.md
- requirements.txt
- setup.py
Don't set a specific version for pip & setuptools
> Minor update

- help_docs/method_summary.md
- integrations/selenium_ide/convert_ide.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/xpath_to_css.py
- setup.py
Mostly improving JavaScript actions
> Improve JavaScript actions

- seleniumbase/fixtures/base_case.py
- setup.py
Refactor duplicate code into a single method.
> Refactoring

- README.md
- examples/ReadMe.md
- help_docs/customizing_test_runs.md
- integrations/google_cloud/ReadMe.md
- integrations/katalon/ReadMe.md
- integrations/selenium_ide/ReadMe.md
> Update ReadMe files

- examples/boilerplates/samples/google_test.py
- examples/tour_examples/google_tour.py
- seleniumbase/core/style_sheet.py
- seleniumbase/fixtures/base_case.py
- setup.py
> Refactoring and tour updates

- README.md
- help_docs/virtualenv_instructions.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Fix compatibility with IE Browser
> Fix compatibility with IE Browser

- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
Update the Selenium IDE script-converter tool
> Update the Selenium IDE script-converter tool

- README.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Set Chrome window default sizing
> Set Chrome window default sizing

- examples/parameterized_test.py
- requirements.txt
- setup.py
* Adding ability for parameterized tests
> Adding ability for parameterized tests

- setup.py
* Fix pypi readme by setting content type to markdown
> Fix pypi readme by setting content type to markdown

- seleniumbase/fixtures/base_case.py
- setup.py
Minor reliability update:
* Autocomplete text boxes may need more time to finish updating
> Minor reliability update

- seleniumbase/fixtures/base_case.py
- setup.py
* Fix delayed asserts (the error message in the output)
Usage example:
```
...
self.delayed_assert_element(CSS_SELECTOR)
self.delayed_assert_text(TEXT, CSS_SELECTOR)
self.process_delayed_asserts()
...
```
> Fix delayed asserts (the error message in the output)

- requirements.txt
- setup.py
> Update pytest version

- pytest.ini
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- setup.py
> Handle deprecation warnings

- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
Use raw strings for regular expressions
> Use raw strings for regular expressions

- seleniumbase/fixtures/base_case.py
- setup.py
If the Google Auth password expires soon, get the next one.
> If the Google Auth password expires soon, get the next one.

- examples/tour_examples/hopscotch_google_tour.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
Accept xpath selectors in website tours
> Accept xpath selectors in website tours

- README.md
- examples/basic_script.py
- examples/delayed_assert_test.py
- examples/my_first_test.py
- examples/my_test_suite.py
- examples/test_fail.py
- examples/tour_examples/ReadMe.md
- examples/tour_examples/xkcd_tour.py
- help_docs/method_summary.md
- seleniumbase/common/ReadMe.md
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/style_sheet.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- setup.py
Add the ability to export a website tour as a .js file
> Add the ability to export a website tour as a .js file

- seleniumbase/fixtures/base_case.py
Minor change to Google Auth timing
> Minor change to Google Auth timing

- requirements.txt
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- setup.py
Removing "urllib3" requirement to prevent conflicts with "requests"
> Removing "urllib3" requirement to prevent conflicts with "requests"

- seleniumbase/fixtures/constants.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/db_reporting_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
Update env options and make browser selection case insensitive with pytest
> Update env options and make browser selection case insensitive with pytest

- seleniumbase/console_scripts/sb_install.py
- setup.py
Update driver installation
Fixes Firefox webdriver runs on Windows
> Update driver installation

- README.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- setup.py
Case insensitive console scripts.
Now, you can do something like:
```
seleniumbase install ChromeDriver
```
Before, you had to do this:
```
seleniumbase install chromedriver
```
> Case insensitive console scripts

- README.md
- examples/ReadMe.md
- help_docs/install.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/masterqa/ReadMe.md
> Update the docs

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Method updates
* Add self.find_elements()
* Rename self.pick_select_option_by_*() methods to self.select_option_by_*() methods
> Method updates

- examples/tour_examples/shepherd_google_tour.py
- seleniumbase/fixtures/base_case.py
- setup.py
Shepherd tour update
* Mainly adding a "Back" button to Shepherd website tours
> Shepherd tour update

- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/proxy_helper.py
- setup.py
Handle an edge case ("Permission denied") when using a proxy server with auth
> Handle an edge case when using a proxy server with auth

- seleniumbase/config/settings.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/masterqa/ReadMe.md
- seleniumbase/masterqa/master_qa.py
- setup.py
MasterQA Updates
* Edit Theme
* Improve Reliability
> MasterQA Updates

- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/utilities/selenium_grid/ReadMe.md
- seleniumbase/utilities/selenium_grid/download_selenium_server.py
- seleniumbase/utilities/selenium_grid/grid_hub.py
- seleniumbase/utilities/selenium_grid/grid_node.py
- setup.py
Update seleniumbase console scripts
Adding:
```bash
seleniumbase download server
```
This command downloads the latest Selenium Server Standalone JAR file from https://www.seleniumhq.org/download/
> Update seleniumbase console scripts

- README.md
- requirements.txt
- seleniumbase/config/proxy_list.py
- setup.py
Update pytest and pytest-xdist requirements
* pytest to 4.0.2 or greater
* pytest-xdist to 1.25.0 or greater
>  Update pytest and pytest-xdist requirements 

- .travis.yml
- README.md
- _config.yml
- setup.py
- virtualenv_install.bat
- virtualenv_install.sh
Simplify virtualenv installation by using shell scripts.
> Easy virtualenv installation

- MANIFEST.in
- setup.py
- virtualenv_install.bat
Update virtualenv script and manifest:
* Fix echo commands in a virtualenv Windows batch file
* Update the manifest file
> Update virtualenv script and manifest

- seleniumbase/config/proxy_list.py
- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
* Update the selenium ide conversion tool
* Also update a method for clicking link text inside dropdown menus
> Update the selenium ide conversion tool

- seleniumbase/fixtures/base_case.py
- setup.py
Allow a custom timeout for wait_for_link_text_present()
Allow a custom timeout for wait_for_link_text_visible()
> Allow a custom timeout when waiting for link text

- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
- setup.py
- virtualenv_install.sh
Update console scripts and traffic-generation code
* Autodetect "source" for activating virtualenv commands in bash
* Update seleniumbase console scripts menu
* Update traffic-generation code
> Update console scripts and traffic-generation code

- requirements.txt
- setup.py
Update parameterized version:
* Use parameterized==0.6.3
> Update parameterized version

- requirements.txt
- setup.py
Fix python 2 compatibility:
* Use more-itertools version >=5.0.0,<6.0.0
> Fix python 2 compatibility

- examples/my_first_test.py
- help_docs/method_summary.md
- integrations/node_js/my_first_test.py
- requirements.txt
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
Adding exact text methods and other improvements:
* Add ``self.assert_exact_text()``
* Add ``self.wait_for_exact_text_visible()``
* Update pytest version to 4.2.1
* Adding more reliability to some methods
> Adding exact text methods and other improvements

- README.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Clone an existing method with an additional name:
* Add ``self.assert_element_visible(CSS_SELECTOR)``, which does the same thing as ``self.assert_element(CSS_SELECTOR)``.
> Clone an existing method with an additional name

- MANIFEST.in
- setup.py
Fix browser extension loading for pypi installations:
* Include browser extensions as part of package data
> Fix browser extension loading for pypi installations

- .gitignore
- examples/visual_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/core/visual_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Automated Visual Testing
* Add ``self.check_window(name, level, baseline)`` method for automated visual testing
* Add methods for processing links and status codes on web pages:
```
self.get_unique_links()
self.get_link_status_code(link, allow_redirects=False, timeout=5)
self.assert_no_404_errors()
self.print_unique_links_with_status_codes()
```
* Update pytest versioning
> Automated Visual Testing

- examples/raw_parameter_script.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- setup.py
Small Fixes:
* Prevent PytestDeprecationWarning
* More efficient screenshots for logs
> Small Fixes

- .gitignore
- requirements.txt
- setup.py
Add pytest-metadata to the requirements
> Add pytest-metadata to the requirements

- examples/visual_testing/ReadMe.md
- examples/visual_testing/layout_test.py
- help_docs/install.md
- requirements.txt
- seleniumbase/config/proxy_list.py
- setup.py
Refactor visual/layout testing
> Refactor visual/layout testing

- seleniumbase/config/proxy_list.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/report_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/plugins/base_plugin.py
- setup.py
> Update test reports

- pytest.ini
- seleniumbase/console_scripts/sb_mkdir.py
- setup.py
> Ignore pytest cacheprovider

- .gitignore
- examples/image_test.py
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Add ability to save page elements as screenshot files
> Add ability to save page elements as screenshot files

- .gitignore
- README.md
- examples/raw_parameter_script.py
- examples/tour_examples/ReadMe.md
- help_docs/features_list.md
- help_docs/install_python_pip_git.md
- help_docs/mysql_installation.md
- help_docs/virtualenv_instructions.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
Several minor updates:
* Screenshots update
* Parameter update
* .gitignore update
* utf-8 encoding
* Docs update
> Several minor updates

- README.md
- help_docs/install_python_pip_git.md
- requirements.txt
- setup.py
Update pytest version to 4.4.1
> Update pytest version to 4.4.1 

- README.md
- examples/basic_test.py
- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
* Update Firefox profile settings
* Update urllib3 version
> Update Firefox profile settings

- seleniumbase/utilities/selenium_ide/objectify.py
- setup.py
Update the tool that generates page objects from selectors
> Update the tool that generates page objects from selectors

- pytest.ini
- requirements.txt
- seleniumbase/console_scripts/sb_mkdir.py
- setup.py
> Use pytest>=4.5.0

- README.md
- seleniumbase/core/browser_launcher.py
- setup.py
> Update default Chrome options

- requirements.txt
Split pytest requirements based on Python version installed
> Split pytest requirements based on Python version installed

- seleniumbase/core/settings_parser.py
- setup.py
Update the custom settings parser
> Update the custom settings parser

- .travis.yml
- README.md
- examples/my_first_test.py
- help_docs/customizing_test_runs.md
- help_docs/method_summary.md
- help_docs/mysql_installation.md
- integrations/node_js/my_first_test.py
- requirements.txt
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/mysql.py
- seleniumbase/fixtures/base_case.py
- setup.cfg
- setup.py
Update methods and mysql
* Using pymysql for all MySQL commands
* Adding ``self.assert_title(page_title)``
* Update log folder cleanup when using a custom-named logs folder
* Update a lot of docs
> Update methods and mysql

- examples/raw_parameter_script.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Fix ``self.maximize_window()``
* Rename the ``maximize_window`` option to resolve a conflict with a method of the same name.
> Fix self.maximize_window()

- examples/tour_examples/ReadMe.md
- examples/tour_examples/bootstrap_google_tour.py
- examples/tour_examples/bootstrap_xkcd_tour.py
- examples/tour_examples/google_tour.py
- examples/tour_examples/hopscotch_google_tour.py
- examples/tour_examples/introjs_google_tour.py
- examples/tour_examples/shepherd_google_tour.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/tour_helper.py
- setup.py
SeleniumBase Tour updates:
* Update tour code and examples
> SeleniumBase Tour updates

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
Update a method name from the last Pull Request:
* ``get_partial_link_attribute()`` => ``get_partial_link_text_attribute()``
> Update a method name from the last Pull Request

- .gitignore
- .travis.yml
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/utilities/selenium_ide/objectify.py
- seleniumbase/virtual_display/easyprocess.py
- seleniumbase/virtual_display/xvfb.py
- setup.py
- virtualenv_install.bat
- virtualenv_install.sh
* Better error output in assert methods
* Fix flake8 issues
* Prepare the new "msedgedriver" for SeleniumBase use
* Update help with virtualenv commands
* Update setup.py for easier and safer deploys to PyPI
> Many Updates

- README.md
- examples/ReadMe.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/db_reporting_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Skip the disable_csp Chrome extension by default in Demo Mode and MasterQA
* Also update and refactor command line arguments
> Fix issue with Chrome developer extensions

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
* Use pytest>=5.1.3 (for Python 3 users)
* Update default Firefox preferences
* Add wait_for_text_not_visible()
* Add assert_text_not_visible()
> Update requirements and methods

- README.md
- seleniumbase/core/browser_launcher.py
- setup.py
* Add DRIVER_DIR to PATH for Selenium 4 compatibility
> Selenium 4 compatibility

- README.md
- requirements.txt
- setup.py
> Update pytest requirements

- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
* Update the default webdriver search path
> Update the default webdriver search path

- README.md
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/utilities/selenium_grid/grid_hub.py
- seleniumbase/utilities/selenium_grid/grid_node.py
- setup.py
* Update the webdriver installer script (for chromedriver and geckodriver)
* Have the seleniumbase/drivers folder take PATH priority when multiple drivers exist
* If the expected webdriver isn't installed, install it automatically (during test runs)
* Make sure chromedriver is available for Selenium Grid use (installed automatically)
> Webdriver Upgrades

- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
Fix assert_no_404_errors() method
> Fix assert_no_404_errors() method

- README.md
- requirements.txt
- setup.py
Update Python dependencies such as pip and pytest
> Update Python dependencies such as pip and pytest

- README.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix issue with timeouts set by a custom settings file
> Fix issue with custom settings file usage

- README.md
- examples/test_fail.py
- examples/xpath_test.py
- requirements.txt
- setup.py
> Pytest update

- README.md
- examples/ReadMe.md
- examples/my_first_test.py
- help_docs/customizing_test_runs.md
- help_docs/features_list.md
- help_docs/hidden_files_info.md
- requirements.txt
- setup.py
* Update ``setuptools`` version
* Update ``flake8`` version
* Also update some ReadMe files
> Requirements update

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Update ``pytest``
* Update ``portalocker``
* Allow the ``update_text()`` method to handle ints and floats as text
* Improve some error messages if/when they occur
> Update pytest, portalocker, and improve some error-handling

- examples/test_pdf_asserts.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
> Add the assert_pdf_text() method for asserting PDF text

- seleniumbase/fixtures/base_case.py
- setup.py
> If the downloads_folder doesn't exist, create it for downloads

- examples/test_get_pdf_text.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
> Add get_pdf_text() and use that in assert_pdf_text()

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
- setup.py
Add ``click_nth_visible_element(selector, number, by=By.CSS_SELECTOR)``
```
Finds all matching page elements and clicks the nth visible one.
Example:
self.click_nth_visible_element('[type="checkbox"]', 5)
(Clicks the 5th visible checkbox on the page.)
```
> Add click_nth_visible_element(selector, number, by=By.CSS_SELECTOR)

- examples/test_event_firing.py
Add an example to demonstrate EventFiringWebDriver and AbstractEventListener
> Add an example to demonstrate EventFiringWebDriver

- README.md
- examples/ReadMe.md
- help_docs/customizing_test_runs.md
- help_docs/features_list.md
> Update several ReadMe files

- examples/custom_settings.py
- requirements.txt
- seleniumbase/config/proxy_list.py
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Refactor default browser resolutions into a settings file
* Bump tqdm version to >=4.40.2
> Settings refactoring

- README.md
- examples/ReadMe.md
- help_docs/customizing_test_runs.md
- help_docs/features_list.md
- requirements.txt
- setup.py
> Update pytest and pytest-xdist versions

- requirements.txt
- setup.py
> tqdm dependency update

- seleniumbase/config/proxy_list.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/js_utils.py
- setup.py
* Optimize JS by putting html <script> tags before the end of <body>
* Refactor jQuery exception code
* Update logging around making web drivers executable
> JS Optimization and Refactoring

- .github/workflows/python-package.yml
Trigger GitHub Workflows on master pushes and all PRs
> Trigger GitHub Workflows on master pushes and all PRs

- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
* Improve Firefox WebDriver usability on Linux
* Also update setuptools and tqdm requirements (unrelated)
> Firefox WebDriver Linux updates

- examples/raw_parameter_script.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
> Add option for Chrome's Incognito mode with "--incognito"

- README.md
- seleniumbase/core/browser_launcher.py
- setup.py
- virtualenv_install.bat
* Avoid logs such as: "``DevTools listening on ws://127.0.0.1 ...``" (#470)
* Also simplify virtualenv installation on Windows with the helper script.
> Reduce unwanted logging messages on Windows

- seleniumbase/masterqa/master_qa.py
> Refactor MasterQA mode

- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
Methods effected by the updates:
* ``find_elements(...)``
* ``find_visible_elements(...)``
* ``click_visible_elements(...)``
* ``click_nth_visible_element(...)``
* ``is_element_in_an_iframe(...)``
> Improve method reliability

- examples/edge_test.py
- help_docs/method_summary.md
- seleniumbase/config/proxy_list.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- setup.py
* Update get_page_title() and combine get_title() into it
* Add skip_test() to avoid using the camelCase version
* Improve reliability for the html_inspector
> Small updates

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Improve ``select_option_by_text(SELECTOR, TEXT)``
* Improve ``select_option_by_index(SELECTOR, INDEX)``
* Improve ``select_option_by_value(SELECTOR, VALUE)``
* Also update ``pytest`` and ``setuptools-scm`` dependencies
> Improve select_option_by_*() methods

- requirements.txt
- seleniumbase/fixtures/xpath_to_css.py
- setup.py
> Update the XPath-to-CSS converter

- examples/test_skype_site.py
- seleniumbase/config/proxy_list.py
- seleniumbase/fixtures/js_utils.py
- setup.py
> Improve demo-mode on mobile device tests

- requirements.txt
- setup.py
* pytest>=5.3.4
* setuptools>=45.1.0;python_version>="3"
* setuptools-scm>=3.4.2
> Update Python dependencies

- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Because Edge is Chromium-based now, it works like Chrome
* pip>=20.0.1
* urllib3==1.25.8
* pdfminer.six==20200121;python_version>="3.5"
> Treat the new Chromium Edge browser like Chrome

- README.md
- requirements.txt
- setup.py
* ``pip>=20.0.2``
* ``setuptools-scm>=3.4.3``
* ``packaging>=20.1``
* ``pdfminer.six==20200124;python_version>="3.5"``
> Refresh Python dependencies

- README.md
- help_docs/method_summary.md
- help_docs/mobile_testing.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Add ``scroll_to_top()`` and ``scroll_to_bottom()``
* Update ``tqdm`` Python dependency
> Add additional scroll methods

- seleniumbase/core/mysql.py
- setup.py
* Better error-handling with custom settings parsing
> Better error-handling with custom settings parsing

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Update ``requests``, ``idna``, and ``tqdm``
* Improve error-handling with PDF extraction methods
> Update dependencies and improve error-handling

- seleniumbase/fixtures/xpath_to_css.py
- setup.py
Fix the xpath-to-css converter
> Fix the xpath-to-css converter

- .github/workflows/python-package.yml
- .gitignore
- .travis.yml
- README.md
- azure-pipelines.yml
- examples/raw_parameter_script.py
- examples/translations/ReadMe.md
- examples/translations/chinese_test_1.py
- help_docs/customizing_test_runs.md
- help_docs/features_list.md
- help_docs/method_summary.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- seleniumbase/translate/chinese.py
- setup.py
* Add Chinese language translations with an example test
* Add the ``--no-sandbox`` and ``--disable-gpu`` Chrome options
> Add Chinese language translations 

- seleniumbase/fixtures/base_case.py
- setup.py
> Fix the hover_and_click() method for XPath selectors

- requirements.txt
- seleniumbase/fixtures/xpath_to_css.py
- setup.py
* Also update a few Python dependencies
> Fix the XPath-to-CSS Selector converter

- examples/translations/japanese_test_1.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/japanese.py
- setup.py
* Adding SeleniumBase methods in Japanese
* Also updating the Chinese translation
* Add an example test in Japanese
> Add the Japanese translation of SeleniumBase

- examples/translations/japanese_test_1.py
Selenium is "セレニウム" in Japanese. (Most people don't write Selenium in Japanese, by the way)
> Update for fixing odd Japanese

- examples/translations/french_test_1.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/french.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- setup.py
* Adding SeleniumBase methods in French
* Also updating existing translations
* Add an example test in French
* Limit demo-mode highlights for non-browser asserts
* Make sure special characters are kept with ``self.get_current_url()``
> Add the French translation of SeleniumBase

- examples/translations/italian_test_1.py
- requirements.txt
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- setup.py
Here's what the example test looks like:
```python
from seleniumbase.translate.italian import CasoDiProva
class ClasseDiTest(CasoDiProva):
def test_esempio_1(self):
self.apri_url("https://it.wikipedia.org/wiki/")
self.verificare_il_testo("Wikipedia")
self.verificare_elemento('[title="Lingua italiana"]')
self.aggiornare_il_testo("#searchInput", "Pizza")
self.fare_clic("#searchButton")
self.verificare_il_testo("Pizza", "#firstHeading")
self.verificare_elemento('img[alt*="pizza"]')
self.aggiornare_il_testo("#searchInput", "Colosseo")
self.fare_clic("#searchButton")
self.verificare_il_testo("Colosseo", "#firstHeading")
self.verificare_elemento('img[alt*="Colosseo"]')
self.indietro()
self.verificare_correttezza("Pizza" in self.ottenere_url_corrente())
self.avanti() …
```
> Seleniumbase in Italian

- examples/translations/chinese_test_1.py
- examples/translations/french_test_1.py
- examples/translations/italian_test_1.py
- examples/translations/japanese_test_1.py
- examples/translations/spanish_test_1.py
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/spanish.py
- setup.py
* Here's the example test:
```python
from seleniumbase.translate.spanish import CasoDePrueba
class MiClaseDePrueba(CasoDePrueba):
def test_ejemplo_1(self):
self.abrir_url("https://es.wikipedia.org/wiki/")
self.verificar_texto("Wikipedia")
self.verificar_elemento('[title="Visitar la página principal"]')
self.actualizar_texto("#searchInput", "Parc d'Atraccions Tibidabo")
self.haga_clic("#searchButton")
self.verificar_texto("Tibidabo", "#firstHeading")
self.verificar_elemento('img[alt*="Tibidabo"]')
self.actualizar_texto("#searchInput", "Palma de Mallorca")
self.haga_clic("#searchButton")
self.verificar_texto("Palma de Mallorca", "#firstHeading")
self.verificar_elemento('img[alt*="Palma"]')
self.volver()
self.verificar_verdad("Tibidabo" in self.obtener_url_actual())
self.adelante() …
```
> SeleniumBase in Spanish

- requirements.txt
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
* Update error output
* Refactor logging
* Update Python dependencies
> Update error output, refactor logging, and update dependencies

- .gitignore
- README.md
- examples/raw_parameter_script.py
- pytest.ini
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Usage:
* ``--guest``
(When the Guest Mode option is set, the Chromium browser launches in Guest Mode.)
* ``--devtools``
(When the Devtools option is set, Chromium will open the DevTools window on startup.)
> Add Guest Mode and DevTools options for Chromium

- examples/translations/chinese_test_1.py
- examples/translations/french_test_1.py
- examples/translations/italian_test_1.py
- examples/translations/japanese_test_1.py
- examples/translations/korean_test_1.py
- examples/translations/portuguese_test_1.py
- examples/translations/russian_test_1.py
- examples/translations/spanish_test_1.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* Here's an example test in Russian:
```python
from seleniumbase.translate.russian import ТестНаСелен  # noqa
class МойТестовыйКласс(ТестНаСелен):
def test_пример_1(self):
self.открытый("https://ru.wikipedia.org/wiki/")
self.проверить_элемент('[title="Русский язык"]')
self.проверить_текст("Википедия", "h2.main-wikimedia-header")
self.обновить_текст("#searchInput", "МГУ")
self.нажмите("#searchButton")
self.проверить_текст("университет", "#firstHeading")
self.проверить_элемент('img[alt="МГУ, вид с воздуха.jpg"]')
self.обновить_текст("#searchInput", "приключения Шурика")
self.нажмите("#searchButton")
self.проверить_текст("Операция «Ы» и другие приключения Шурика")
self.проверить_элемент('img[alt="Постер фильма"]')
self.назад()
self.проверить_правду("университет" in …
```
> Add the SeleniumBase Russian translation

- examples/offline_examples/demo_page.html
- examples/offline_examples/test_demo_page.py
- examples/test_demo_site.py
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
* Improve automation on Safari browsers
* Improve hover_and_click actions
* Update the demo page
* Update example tests
* Refresh the "pip" dependency
> Improve automation on Safari browsers

- examples/timeout_test.py
- examples/translations/english_test_1.py
- requirements.txt
- seleniumbase/common/exceptions.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/errors.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/shared_utils.py
- seleniumbase/translate/translator.py
- setup.py
* Improve exception-handling by using Selenium's built-in exceptions
* Improve error-handling around alerts during wait_for_ready_state_complete()
* Improve smart-word-wrap when printing Translation API results
* For the test time-limit feature, start the clock at the end of setUp()
> Improve exception-handling, and more

- help_docs/chinese.md
add chinese ReadMe.md as chinese.md
> add chinese.md (添加中文翻译的ReadMe.md文件)

- examples/offline_examples/demo_page.html
- examples/offline_examples/user_agent_test.py
- examples/test_get_user_agent.py
- examples/tour_examples/driverjs_maps_tour.py
- examples/tour_examples/xkcd_tour.py
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* Add the get_user_agent() method
* Update translations
* Improve mobile compatibility
> Add get_user_agent() and improve mobile compatibility

- requirements.txt
- setup.py
* Update Python dependencies
* Fix https://github.com/seleniumbase/SeleniumBase/issues/598
> Update Python dependencies and fix a Windows issue

- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
```python
md["create_presentation"][0] = "create_presentation"
md["create_presentation"][1] = "创建演示文稿"
md["create_presentation"][2] = "een_presentatie_maken"
md["create_presentation"][3] = "créer_une_présentation"
md["create_presentation"][4] = "creare_una_presentazione"
md["create_presentation"][5] = "プレゼンテーションを作成する"
md["create_presentation"][6] = "프레젠테이션_만들기"
md["create_presentation"][7] = "criar_uma_apresentação"
md["create_presentation"][8] = "создать_презентацию"
md["create_presentation"][9] = "crear_una_presentación"
md["add_slide"][0] = "add_slide"
md["add_slide"][1] = "添加幻灯片"
md["add_slide"][2] = "een_dia_toevoegen"
md["add_slide"][3] = "ajouter_une_diapositive"
md["add_slide"][4] = "aggiungere_una_diapositiva"
md["add_slide"][5] = "スライドを追加する"
md["add_slide"][6] = "슬라이드_추가" …
```
> Add Presenter language translations

- README.md
- integrations/github/workflows/ReadMe.md
examples how to gha 🚀 workflows to:
* send a slack notification to channel with workflow from seleniumbase
* upload an artifact from the seleniumbase presentation slide show
> additional examples to github actions workflows

- requirements.txt
- seleniumbase/fixtures/page_actions.py
- seleniumbase/utilities/selenium_grid/grid-hub
- seleniumbase/utilities/selenium_grid/grid_hub.py
- seleniumbase/utilities/selenium_grid/start-grid-hub.bat
- seleniumbase/utilities/selenium_grid/start-grid-hub.sh
- setup.py
* Improve error messages when expected page elements don't appear
* Update a Python dependency (``rich==3.0.5``)
* Update default Selenium Grid timeout settings
-- (``-timeout 230 -browserTimeout 170``)
> Improve error messages, and more

- seleniumbase/core/browser_launcher.py
- setup.py
> Add default Chrome option: "--use-gl=swiftshader"

- README.md
- examples/raw_parameter_script.py
- help_docs/customizing_test_runs.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* This enables Chrome's ``--use-gl=swiftshader`` feature
> Add the "--swiftshader" command-line option

- seleniumbase/core/browser_launcher.py
- setup.py
> Don't disable Chrome's GPU if using SwiftShader

- requirements.txt
- seleniumbase/console_scripts/objectify.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* Fix https://github.com/seleniumbase/SeleniumBase/issues/629
Also update Python requirements:
* jedi==0.17.2
* pymysql==0.10.0
> Fix UnicodeDecodeError issues on Windows

- examples/presenter/ReadMe.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/presenter/ReadMe.md for details about SeleniumBase Presenter
> Hide Presenter notes by default unless specified

- examples/swag_labs_suite.py
- examples/test_apple_site.py
- examples/test_swag_labs.py
- examples/test_usefixtures.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix double_click() for older versions of ChromeDriver
* Race through chart display if running in headless mode
* Update example tests
> Bug fixes and test updates

- docs/requirements.txt
- examples/basic_test.py
- examples/my_first_test.py
- examples/nth_child_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* Improve Safari automation
* Improve Demo Mode
* Improve Slow Mode
* Add ``post_message_and_highlight()``
* Add and update example tests
* Update Python dependencies (``pip`` and ``setuptools``)
> Improve Safari automation, Demo Mode, and Slow Mode

- seleniumbase/fixtures/base_case.py
- setup.py
* Nearly everyone is using pytest with SeleniumBase, so I don't expect that this impacted anyone for the very short time that this issue existed.
> Fix issue with nosetests tearDown()

- README.md
- seleniumbase/console_scripts/sb_install.py
- setup.py
* ``sbase install edgedriver`` will install/download EdgeDriver ``84.0.522.61`` now.
* You can always change the version installed: ``sbase install edgedriver VERSION``
> Update the default EdgeDriver version

- README.md
- examples/raw_parameter_script.py
- help_docs/ReadMe.md
- help_docs/customizing_test_runs.md
- help_docs/locale_codes.md
- help_docs/method_summary.md
- mkdocs.yml
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Examples:
* ``pytest --locale="ru"``
* ``pytest --locale="zh_cn"``
See https://seleniumbase.io/help_docs/locale_codes/ for a list of valid codes.
* Make improvements to JavaScript and jQuery methods
* Improve error logging
```python
self.activate_design_mode()
self.deactivate_design_mode()
```
> Add the ability to set the browser's Language/Locale

- seleniumbase/console_scripts/sb_print.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/translator.py
- setup.py
* Fix html when creating an iframe in a Presenter presentation
* Update smart-word-wrap in ``sbase print`` and ``sbase translate``
> Fix iframes in presentations and update smart-word-wrap

- requirements.txt
- seleniumbase/console_scripts/ReadMe.md
- setup.py
* ``setuptools>=50.1.0;python_version>="3.5"``
> Upgrade the "setuptools" dependency

- seleniumbase/fixtures/xpath_to_css.py
- setup.py
* Handle special xpath edge cases that weren't covered by the main converter
> Update the xpath-to-css selector converter

- docs/requirements.txt
- requirements.txt
- setup.py
* ``pytest==6.1.1;python_version>="3.5"``
* ``beautifulsoup4==4.9.3``
* ``rich==8.0.0;python_version>="3.6" and python_version<"4.0"``
* ``zipp==3.3.0;python_version>="3.6"``
* ``flake8==3.8.4;python_version>="3.5"``
* ``virtualenv>=20.0.33``
> Update Python requirements

- .github/Workflows.md
- help_docs/customizing_test_runs.md
- integrations/brython/ReadMe.md
- mkdocs.yml
- requirements.txt
- seleniumbase/ReadMe.md
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/core/browser_launcher.py
- setup.py
* Handle an edge case with multiple file downloads
-- (no more prompts when downloading multiple files)
* Also improve ``brython`` compatibility for Python 3.9 users
> Handle an edge case with multiple file downloads

- README.md
- docs/requirements.txt
- install.sh
- requirements.txt
- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
- setup.py
- win_install.bat
* Get the setup.py version from ``__version__.py``
* Improve reliability when slow-scrolling to elements
* Update console scripts output
* Update Python dependencies
-- ``prompt-toolkit==3.0.8``
-- ``colorama==0.4.4``
-- ``virtualenv>=20.0.34``
> Refactoring and other updates

- .travis.yml
- README.md
> Update the deploy script

- .github/workflows/python-package.yml
- azure-pipelines.yml
* Add Python 3.9 to Azure Pipelines
* Add Python 3.9 to GitHub Actions / Workflows
> Expand CI with Python 3.9

- .github/workflows/python-package.yml
- docs/requirements.txt
- examples/unit_tests/ReadMe.md
- examples/unit_tests/verify_framework.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Update the wheel dependency: ``wheel>=0.36.1``.
* Add the "pytester" plugin to make the "testdir" fixture available for unit tests.
> A few small updates

- README.md
- examples/ReadMe.md
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/plugins/pytest_plugin.py
* Update the seleniumbase install script (console output and colors)
* Also update Dashboard notifications (console color)
> Update the seleniumbase install script

- help_docs/features_list.md
- mkdocs.yml
- seleniumbase/__version__.py
- seleniumbase/fixtures/constants.py
- seleniumbase/translate/dutch.py
- setup.py
> Update HighCharts version for dashboards and charts

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* ``parso==0.8.1;python_version>="3.6"``
* ``jedi==0.18.0;python_version>="3.6"``
> Update Python dependencies: "parso" and "jedi"

- LICENSE
- docs/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* Some Firefox options weren't taking effect on all environments.
* Also refresh Python dependencies
> Update Firefox options to effect all environments

- examples/translations/pytest.ini
- pytest.ini
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/mysql.py
- setup.py
* ``pymysql==0.10.1;python_version<"3.6"``
* ``pymysql==1.0.0;python_version>="3.6"``
> Update the Python MySQL connector

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- setup.py
* Add method: ``drag_and_drop_with_offset(selector, x, y)``
* Also update Python dependencies: ``setuptools>=51.1.2``
> Improve drag-and-drop functionality

- docs/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/errors.py
- seleniumbase/plugins/db_reporting_plugin.py
- setup.py
* Have the test status match that of the dashboard:
-- ``Passed``, ``Failed``, ``Skipped``, ``Untested``.
* Fix an issue where the MySQL DB was missing test info / exceptions.
* Fix an issue where skipped tests didn't display ``Skipped`` status in the DB.
* ``parameterized==0.8.1``
* ``pymysql==1.0.2``
* ``rich==9.7.0``
> Renovate the MySQL DB system

- README.md
- help_docs/ReadMe.md
- help_docs/features_list.md
- help_docs/syntax_formats.md
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* Fix issue with multithreading caused by exceptions in threads
* Display all broken links that are found (not just the first one)
> Fix method: assert_no_404_errors()

- README.md
- docs/requirements.txt
- examples/visual_testing/ReadMe.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Update dashboard output
* Update dashboard timing for LiveJS updates
* Update plugin descriptions shown by: ``pytest --help``
* Update Python dependencies
-- ``pip>=21.0.1;python_version>="3.6"``
-- ``virtualenv>=20.4.1``
> Update the dashboard and Python dependencies

- docs/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
* Improve reliability and error output of some SeleniumBase methods
-- Uses ``self.wait_for_ready_state_complete()`` to do both things
> Update error handling

- requirements.txt
- setup.py
removed brython dependencies for issue-886
> issue-886 remove brython

- seleniumbase/fixtures/base_case.py
* Prevent duplicate ``setUp()`` & ``tearDown()`` from incorrect use
* Make sure the Dashboard takes more edge cases into account
* Do some refactoring
* Resolves https://github.com/seleniumbase/SeleniumBase/issues/884
> Prevent duplicate setUp & tearDown

- docs/requirements.txt
- examples/master_qa/pytest.ini
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/masterqa/master_qa.py
- setup.py
* Update MasterQA output
* **Update Python dependencies**:
* ``pip>=21.1.2;python_version>="3.6"``
* ``setuptools>=57.0.0;python_version>="3.6"``
* ``virtualenv>=20.4.7``
> Update dependencies and MasterQA output

- README.md
- examples/example_logs/ReadMe.md
- examples/test_chinese_pdf.py
- examples/test_get_pdf_text.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Improve reliability of ``self.click_nth_visible_element(...)``
* Improve reliability of ``self.set_value(...)``
* Keep ``self._print(...)`` from printing during multithreaded runs:
-- (Prevent garbled text on the console output)
-- ``pip>=21.2.1;python_version>="3.6"``
-- ``platformdirs==2.2.0;python_version>="3.6"``
> Reliability and other improvements

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/objectify.py
- setup.py
This tool is used to replace selectors in tests with page objects.
Here's an example of how it works on this existing file: (https://github.com/seleniumbase/SeleniumBase/blob/master/examples/basic_test.py)
```python
from seleniumbase import BaseCase
class MyTestClass(BaseCase):
def test_basics(self):
self.open("https://store.xkcd.com/search")
self.type('input[name="q"]', "xkcd book\n")
self.assert_text("xkcd book", "div.results")
self.open("https://xkcd.com/353/")
self.click('a[rel="license"]')
self.go_back()
self.click_link("About")
self.click_link("comic #249")
self.assert_element('img[alt*="Chess"]')
````
Now run ``sbase objectify basic_test.py``:
```bash
sbase objectify basic_test.py 
>>> ["page_objects.py"] was created!
>>> ["page_objects.py"] was updated!
>>> ["basic_test.py"] was …
```
> Update the instant page-object-generator tool

- README.md
- docs/requirements.txt
- examples/custom_settings.py
- examples/parameterized_test.py
- examples/test_demo_site.py
- examples/upload_file_test.py
- help_docs/customizing_test_runs.md
- help_docs/recorder_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/settings_parser.py
- seleniumbase/fixtures/base_case.py
- setup.py
<p>🔴 SeleniumBase <code>1.66.5</code> improves the algorithm for converting recorded actions into SeleniumBase code.</p>
* Update the custom_settings parser:
-- Add ``SWITCH_TO_NEW_TABS_ON_CLICK`` to parsed items.
-- ``filelock==3.2.0``
> Improve the "Recorder Mode" test generator

- seleniumbase/console_scripts/sb_mkrec.py
Hey Mike, still trying to get the browser to open, but at least this gets me past "INVALID OPTION: >> --gui"
> toward running interactively under ubuntu.

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
This is for https://github.com/seleniumbase/SeleniumBase/issues/1060
Although this won't handle all cases of the above, improvements will be noticeable in many situations.
* pycparser==2.21
* rich==10.13.0;python_version>="3.6"
> Simplify output associated with "NoSuchWindowException"

- seleniumbase/__version__.py
- seleniumbase/fixtures/js_utils.py
* This fixes https://github.com/seleniumbase/SeleniumBase/issues/1172
> Fix the algorithm for detecting if the driver switched to a frame

- help_docs/ReadMe.md
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* This fixes the output of some error messages and info messages
> Update code for extracting "capabilities" from the driver

- .github/workflows/python-package.yml
- azure-pipelines.yml
- examples/dialog_boxes/dialog_box_tour.py
- examples/raw_browser_launcher.py
- examples/setup.cfg
- examples/unit_tests/verify_framework.py
- examples/wordle_test.py
- help_docs/method_summary.md
- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/report_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.cfg
* Improve logging:
-- Include details about the browser and driver versions in logs.
-- Also includes some code refactoring.
* Improve Shadow DOM support:
-- The timing of Shadow DOM methods has been optimized.
* Add a shorter name for ``highlight_update_text(selector, text)``:
-- ``highlight_type(selector, text)``
* Update the ``flake8`` style guide rules for SeleniumBase:
-- Only ignore rule ``W503`` (line break before binary operator).
> Improve Logging, Shadow DOM support, and more

- examples/basic_test.py
- examples/migration/protractor/example_test.py
- examples/offline_examples/demo_page.html
- examples/offline_examples/handle_alert_test.py
- examples/raw_parameter_script.py
- examples/swag_labs_suite.py
- examples/test_show_file_choosers.py
- examples/user_agent_test.py
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* Improve Safari automation compatibility.
* Update the example tests.
> Safari optimizations and test updates

- examples/wordle_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add "caching" option to assert_pdf_text()](https://github.com/seleniumbase/SeleniumBase/commit/e65b0235592130b1e103c64ca91ef0390e6af019)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/20d52f14637d021ac7cc15e61f10437ef1e9502a)
> Update method args and dependencies

- seleniumbase/__version__.py
- seleniumbase/fixtures/js_utils.py
* Handle special cases of when the selector contains ``[style="`` or ``box-shadow:`` because Demo Mode will change those values as it highlights elements with a box-shadow.
> Improve Demo Mode highlighting

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Refresh pytest-metadata dependency](https://github.com/seleniumbase/SeleniumBase/commit/2f8393fef3504fe46f918afbd017302337fb8dfe)
> Refresh pytest-metadata dependency

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- mkdocs.yml
* [Add CODE_OF_CONDUCT.md](https://github.com/seleniumbase/SeleniumBase/commit/3c6c0b850971c1498fc6cc1b922fbe6d8c8224c5)
* [Add CONTRIBUTING.md](https://github.com/seleniumbase/SeleniumBase/commit/a966ebc3564f43b42fc8a603956323c021055337)
* [Add SECURITY.md](https://github.com/seleniumbase/SeleniumBase/commit/d7da5a3a318e4e6f607849a38f9c051390495a05)
> Housekeeping - Add new policies

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/settings_parser.py
- setup.py
* [Fix parsing of custom_settings files](https://github.com/seleniumbase/SeleniumBase/commit/bb58d2589982c4a0b4061d6536aff7cf04681d86)
* Fix https://github.com/seleniumbase/SeleniumBase/issues/1276
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/1b37c68f5e8961edade521091d3ccdd277048c16)
> Fix parsing of custom_settings files and refresh dependencies

- README.md
- examples/ReadMe.md
- examples/test_agent.py
- examples/test_chinese_pdf.py
- examples/test_get_pdf_text.py
- examples/user_agent_test.py
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
* [New feature: SeleniumBase Commander / GUI for pytest](https://github.com/seleniumbase/SeleniumBase/commit/52c04864dd4e34f47ebe5b9ce10c72d8b929d135)
* [Use requests.head() over requests.get() when possible](https://github.com/seleniumbase/SeleniumBase/commit/f03c595fd1414fa37f77e8e0bb6bcec6c53a8680)
* [Use self._print() to print output in multithreaded mode](https://github.com/seleniumbase/SeleniumBase/commit/b9f4a51c0c46d5e73a33dc53641003e7982f5def)
* [Update translations](https://github.com/seleniumbase/SeleniumBase/commit/08ea4f75f82f703c9cdd1fc24e82061a609bc0b5)
> New feature: SeleniumBase Commander / GUI for pytest

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/console_scripts/sb_recorder.py
* [Fix focus, spacing, and colors on desktop apps](https://github.com/seleniumbase/SeleniumBase/commit/76797d3a5ee3d80c14dc18d4c2e1634cafa07edb)
> Desktop app updates for the Commander and Recorder

- Dockerfile
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
* Fix https://github.com/seleniumbase/SeleniumBase/issues/1296
* Fix https://github.com/seleniumbase/SeleniumBase/issues/1314
> A few fixes (Dockerfile and "behave" Dashboard)

- examples/parameterized_test.py
- examples/test_canvas.py
- examples/test_chromedriver.py
- examples/upgrade_chromedriver.py
- help_docs/webdriver_installation.md
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/drivers/ReadMe.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
* [Make performance optimizations for driver downloads](https://github.com/seleniumbase/SeleniumBase/commit/d707826500da1c21cc93c2e5ce0f7891270a1663)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1341
> Optimizations for driver downloads

- README.md
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
* [Fix IE issue preventing the browser from quitting after tests](https://github.com/seleniumbase/SeleniumBase/commit/96d909d6d7ef0ed22e852902b95366565bc5dee6)
* This fixes https://github.com/seleniumbase/SeleniumBase/issues/1348
> Fix IE issue that prevented the browser from quitting after tests

- examples/behave_bdd/ReadMe.md
- integrations/behave/ReadMe.md
- sbase/steps.py
- seleniumbase/__version__.py
* [Fix issue with escaped characters in Behave ".feature" files](https://github.com/seleniumbase/SeleniumBase/commit/dd9a5f9e4602ec8f94e0a8b31c91024e2c296789)
* This fixes https://github.com/seleniumbase/SeleniumBase/issues/1350
> Fix issue with escaped characters in Behave ".feature" files

- .github/workflows/python-package.yml
Add Behave-BDD tests to GitHub Actions
> Add Behave-BDD tests to GitHub Actions

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/s3_manager.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/shared_utils.py
- setup.py
* [Add a method for installing dependencies as needed](https://github.com/seleniumbase/SeleniumBase/commit/1b658d80ec08983c56c2d71e281ef14838507dce)
* [Install missing optional dependencies as needed](https://github.com/seleniumbase/SeleniumBase/commit/9237c6a0203a497dbee919c3f17ff3b00f1a6908)
* [Transition some required dependencies into optional ones](https://github.com/seleniumbase/SeleniumBase/commit/b30c231404585702a06ff0ab69d37b4d953e7457)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1406
> Reduce required Python dependencies

- README.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
* [Handle edge cases with EdgeDriver](https://github.com/seleniumbase/SeleniumBase/commit/3ae728f243c8d6017faf0e414f20d12882456c7e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1415
* [Handle edge cases with js_click()](https://github.com/seleniumbase/SeleniumBase/commit/6acf508d8c0594ab145c01b5882dd0fd6e39c9e3)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1416
> Handle edge cases with EdgeDriver and js_click()

- README.md
- help_docs/customizing_test_runs.md
- seleniumbase/__version__.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
* [Add pytest option "--list-fail-page" to list URLs of failures](https://github.com/seleniumbase/SeleniumBase/commit/cb3f45408d68e7b8459c6f96e231b68e2bb76685)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1417
* [Improve the reliability of js_click(selector)](https://github.com/seleniumbase/SeleniumBase/commit/7776b795802e315fd5ecfb2988d617e49f802cc6)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1418
> Add a debugging option and improve reliability

- README.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Update default Firefox preferences](https://github.com/seleniumbase/SeleniumBase/commit/f75cda68c6fe086b664965b179f4d030cb8f922a)
* [Update Firefox error-handling](https://github.com/seleniumbase/SeleniumBase/commit/3a46d8353735e65f589bcb2bce9ccf3efc540f33)
* [Refactoring](https://github.com/seleniumbase/SeleniumBase/commit/c508f38d20b4ece77f291f1beb6edc58109887e2)
--> Use ``os.devnull`` instead of ``os.path.devnull`` where used.
--> Calling ``raise`` can be done without args. (Uses the last Exception in a try/except block).
> Update Default Firefox Preferences

- README.md
- help_docs/customizing_test_runs.md
- mkdocs_build/requirements.txt
- seleniumbase/behave/behave_sb.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
> Documentation updates

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/__init__.py
* Fix issue with loading a Chrome extension dir on Windows.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1496
* Optimize cleanup of Undetected-Chromedriver Mode (``--uc``).
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1497
> Two fixes for Windows

- examples/hack_the_planet.py
- examples/wordle_archive_test.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/undetected/__init__.py
* Use the newer way of opening a new tab / window.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1504
* Allow setting ``user_data_dir`` with Undetectable-Chromedriver Mode (``--uc``)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1505
* Update conditions for undetected-chromedriver options.
* Cover a special edge case with previous Safari versions.
> A few optimizations (for new tabs and undetected-chromedriver mode)

- README.md
- examples/raw_parameter_script.py
- examples/swag_labs_suite.py
- examples/test_image_saving.py
- examples/test_swag_labs.py
- help_docs/method_summary.md
- sbase/steps.py
- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/behave/behave_helper.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_objectify.py
- seleniumbase/core/mysql.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
* Add special methods for ``js_click()``:
--> ``self.js_click_if_present()``
--> ``self.js_click_if_visible()``
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1518
* Add method: ``assert_title_contains(substring)``
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1519
* ``seleniumbase.version_info`` should return a tuple, not a list:
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1520
* Path refactoring with the correct separator per OS:
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1521
* Update output for the ``seleniumbase behave-gui`` runner:
* Refactoring.
> New methods and refactoring

- examples/example_logs/ReadMe.md
- examples/performance_test.py
- examples/time_limit_test.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/common/ReadMe.md
- seleniumbase/common/decorators.py
- setup.py
* Add Python decorators for performance testing
--> https://github.com/seleniumbase/SeleniumBase/commit/06c195916caa0e2870d5d63e4b85010481821a5b
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1544
--> https://github.com/seleniumbase/SeleniumBase/commit/d69964b9561e86be09ea7ba77911f13f37fa15de
* Update tests with examples of performance testing
--> https://github.com/seleniumbase/SeleniumBase/commit/759423a802844ba5cdb37c502fb0b81407295807
> Performance Testing decorators

- README.md
- seleniumbase/__version__.py
- seleniumbase/fixtures/shared_utils.py
* Update the method that returns the console width.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1551
> Update the console width method

- README.md
- examples/migration/raw_selenium/flaky_messy_raw.py
- examples/migration/raw_selenium/long_messy_raw.py
- examples/migration/raw_selenium/messy_raw.py
- examples/migration/raw_selenium/refined_raw.py
- examples/migration/raw_selenium/simple_sbase.py
- examples/raw_browser_launcher.py
- examples/raw_driver.py
- help_docs/syntax_formats.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/sb_manager.py
* Update default settings for Undetected Mode:
--> Use a subprocess for pure Python syntax formats
* Check if an attribute is defined before using it:
--> This fixes an issue when not using ``pytest``
> Update default settings for Undetected Mode

- mkdocs.yml
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/js_utils.py
* Fix ``save_teardown_screenshot()`` for Python 3.11
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1593
* Improve methods that scroll to elements.
* Prevent extra waiting of Safari tests in Demo Mode.
> Python 3.11 updates and more

- examples/hack_the_planet.py
- examples/old_wordle_script.py
- examples/wordle_test.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* Fix an issue with getting older drivers on M1/M2 Macs:
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1605
--> https://github.com/seleniumbase/SeleniumBase/commit/d21ff8ebad3bfc7cf2dbbcb4e731e42a2fed62e7
* Also add translations for more methods:
--> https://github.com/seleniumbase/SeleniumBase/commit/95e1818e8b9db61ce7170abb38a08407479cec4b
* Also refresh Python dependencies:
--> https://github.com/seleniumbase/SeleniumBase/commit/eab999d515f10953ea4f749ff8ab09db30f89a71
> Improve Mac M1 and M2 compatibility

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
* Fix driver downloads on M1/M2 Macs
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1612
--> https://github.com/seleniumbase/SeleniumBase/commit/f114c0ff56c8be6ea6c0b2ea9fe77ad60680bfb0
> Fix driver downloads on M1/M2 Macs

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* Install special debuggers optionally.
--> https://github.com/seleniumbase/SeleniumBase/commit/4e4fb11b65e84f54356a757715f6ff81bd09b112
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1619
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1620
> Install special debuggers optionally

- .gitignore
- examples/boilerplates/samples/google_objects.py
- examples/boilerplates/samples/google_test.py
- help_docs/recorder_mode.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/console_scripts/sb_print.py
- seleniumbase/core/browser_launcher.py
- setup.py
* See https://github.com/seleniumbase/SeleniumBase/issues/1623 for details.
* I created https://github.com/mdmintz/pdbp
* I also created https://github.com/mdmintz/tabcompleter
**SeleniumBase will automatically use the new debugger when a breakpoint is reached.**
--------
* [Update ARM64-detection on Macs](https://github.com/seleniumbase/SeleniumBase/commit/1a223c47245ccb0d2ec47c110b38902903f86a5b)
* [Update the test-directory generator script](https://github.com/seleniumbase/SeleniumBase/commit/b1a48a7b17e7767fd4d90ea7de61b25a44d96f96)
* [Update colors when displaying dot-files](https://github.com/seleniumbase/SeleniumBase/commit/77e05e3d04302d886f7a62b83e65038f372db9d0)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/d04a9cae3e023407bb5b8989e011835b2ae …
> My Own Debugger and More

- examples/boilerplates/samples/google_test.py
- examples/test_download_files.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/5362b3da329e8a5fbdb10f47e4c61d4f56f35718)
* [Check more folders for browser detection](https://github.com/seleniumbase/SeleniumBase/commit/fc2cb942d5ae80ebd1e6dc9676b4b85eba30236f)
* [Update console scripts](https://github.com/seleniumbase/SeleniumBase/commit/b8bd9aa836d6ea64b987f520dc265345440ece3e)
* [Update example tests](https://github.com/seleniumbase/SeleniumBase/commit/a6830759c05f892faf4083f2d90a648a67a6b8c4)
> Update selenium and pdbp versions

- README.md
- mkdocs.yml
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- setup.py
* Refresh the ``pdbp`` dependency
--> https://github.com/seleniumbase/SeleniumBase/commit/fdecc6ec38c68d16d2d4e0409a5d5bebfeb6721c
--> More info on ``pdbp``: https://github.com/mdmintz/pdbp
> Refresh docs and dependencies

- README.md
- examples/test_url_asserts.py
- help_docs/method_summary.md
- sbase/steps.py
- seleniumbase/__version__.py
- seleniumbase/behave/behave_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/words.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
* Add methods for URL asserts
--> https://github.com/seleniumbase/SeleniumBase/commit/3321e5204ffe16f6a78fe5ed1473972205bb7959
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1654
* Update translations
--> https://github.com/seleniumbase/SeleniumBase/commit/98f49c19bc2e14e2e6fe59d5923ce320afe5f0e3
* Update behave/BDD steps
--> https://github.com/seleniumbase/SeleniumBase/commit/a61db3ae83dcea3afde654f245af268caf66fd82
* Update Recorder Mode
--> https://github.com/seleniumbase/SeleniumBase/commit/e6b9d82fc6cf1b99cbd710e98ba3c584d2bc3bb8
> Add methods for URL asserts

- examples/github_test.py
- examples/hack_the_planet.py
- examples/proxy_test.py
- examples/raw_browser_launcher.py
- examples/raw_driver_context.py
- examples/test_docs_site.py
- examples/test_select_options.py
- examples/test_show_file_choosers.py
- examples/test_tinymce.py
- examples/test_todomvc.py
- help_docs/syntax_formats.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Fix issue with clicking in ``--uc`` mode
--> https://github.com/seleniumbase/SeleniumBase/commit/2cfa7cc89ca7020154b11420cbca5637c7d0ae19
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1679
* Fix bug with ``--pdb`` and ``--dashboard`` used together
--> https://github.com/seleniumbase/SeleniumBase/commit/9b09476c3a2313dee6cca10dab64579f3f73e6a5
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1680
--> https://github.com/seleniumbase/SeleniumBase/commit/6772da0c2ce19f76dd4ab265ec1df2420bd5e900
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1678
* Remove references to PhantomJS in the code
--> https://github.com/seleniumbase/SeleniumBase/commit/ef097eedc44d9296bb6bebdaddae276dfba991f8
> Even more bug fixes

- README.md
- examples/basic_test.py
- examples/gui_test_runner.py
- examples/parameterized_test.py
- examples/test_event_firing.py
- examples/test_get_locale_code.py
- examples/test_show_file_choosers.py
- examples/test_skype_site.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/common/decorators.py
- seleniumbase/console_scripts/rich_helper.py
- seleniumbase/console_scripts/sb_mkchart.py
- seleniumbase/console_scripts/sb_mkfile.py
- seleniumbase/console_scripts/sb_mkpres.py
- seleniumbase/console_scripts/sb_print.py
- seleniumbase/core/colored_traceback.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/mysql.py
- seleniumbase/core/report_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
- seleniumbase/undetected/dprocess.py
- seleniumbase/utilities/selenium_grid/download_selenium_server.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
* Refresh the "pdbp" (Pdb+) dependency for a bug fix
--> https://github.com/seleniumbase/SeleniumBase/commit/b905d861e1354f3e5c22af1d90d027174af3e4e2
* Refresh the "rich" dependency for better Markdown printing
--> https://github.com/seleniumbase/SeleniumBase/commit/b3a1837471e7fb2e57a4d77b8ca3aca2468ee3c9
* Improve Markdown printing with "sbase print FILE.md"
--> https://github.com/seleniumbase/SeleniumBase/commit/c37c8602deb6fe818634d7742dd108025ec494a2
* Apply colored tracebacks on a wider scale
--> https://github.com/seleniumbase/SeleniumBase/commit/dcda989e4ce5718fe84ddc7747a9e56544e98191
* Improve error-handling on open(URL)
--> https://github.com/seleniumbase/SeleniumBase/commit/3a136d2d3c4d6f59b2e1727ebd1db38be8c18651
* Make methods consistent between different parsers
--> …
> Dependencies and Refactoring

- examples/migration/raw_selenium/flaky_messy_raw.py
- examples/migration/raw_selenium/long_messy_raw.py
- examples/migration/raw_selenium/messy_raw.py
- examples/migration/raw_selenium/refined_raw.py
- examples/migration/raw_selenium/simple_sbase.py
- examples/test_override_driver.py
- examples/test_override_sb_fixture.py
- examples/uc_cdp_events.py
- examples/verify_undetected.py
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1691
* (Fixes an issue where ``--variables=DICTIONARY`` only worked on the first test run.)
* Also update several example tests that are not related to the issue.
> Fix processing of "--variables=DICTIONARY"

- examples/boilerplates/samples/google_test.py
- examples/migration/protractor/example_test.py
- examples/migration/protractor/input_test.py
- examples/migration/protractor/mat_paginator_test.py
- examples/parameterized_test.py
- examples/rate_limiting_test.py
- examples/raw_file_call.py
- examples/swag_labs_user_tests.py
- examples/test_calculator.py
- examples/test_canvas.py
- examples/test_event_firing.py
- examples/test_override_driver.py
- examples/test_repeat_tests.py
- examples/uc_cdp_events.py
- examples/verify_undetected.py
- seleniumbase/__version__.py
- seleniumbase/common/decorators.py
- seleniumbase/console_scripts/sb_print.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/detect_b_ver.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/webelement.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
* Make general improvements to UC Mode
--> https://github.com/seleniumbase/SeleniumBase/commit/86273f441a7a853a67798834c1834842ea55427b
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1706
--> This includes several updates, mostly around multi-threading and thread-locking.
* Use Monokai Theme for rich printing on Windows
--> https://github.com/seleniumbase/SeleniumBase/commit/5e70b91f4b5346531e78748a06512a06360027a2
--> This removed the ``abap`` theme, restoring the default ``monokai`` theme.
--> Usage: ``sbase print FILE``
* Also update multiple example tests.
> Mostly UC Mode improvements

- examples/coffee_cart_tests.py
- examples/offline_examples/user_agent_test.py
- examples/parameterized_test.py
- examples/test_pytest_parametrize.py
- examples/user_agent_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix geckodriver download issue on Windows
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1738
* Add flake8 "ignore=W503" for folders created by "sbase mkdir DIR" (to the config file)
--> https://github.com/seleniumbase/SeleniumBase/commit/a44e4bbfeaad3102e0cfb95d09cb6af3927e39c7
* Refresh Python dependencies:
--> https://github.com/seleniumbase/SeleniumBase/commit/2e6d8ff2c4ecd05efdbfb6b58d20b6c8c2ccac39
> Update console scripts and more

- examples/translations/italian_test_1.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/undetected/options.py
* Changes: https://github.com/seleniumbase/SeleniumBase/commit/f70e847924c55b74daee7a36a1ec3fc86f084a3f
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1758
> Fix Linux issue with using a custom user-data-dir in UC Mode

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* Changes: https://github.com/seleniumbase/SeleniumBase/commit/e5337159f61b5ba433be6309568522cdedae0cb0
> Update default UC Mode options on Linux

- seleniumbase/__version__.py
- seleniumbase/core/download_helper.py
- seleniumbase/plugins/pytest_plugin.py
* Changes: https://github.com/seleniumbase/SeleniumBase/commit/f72f33368277b658f07f575751b4af2f352b6fbe
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1766
> Fix issue with parallel tests that use the dashboard

- examples/proxy_test.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp.py
- seleniumbase/undetected/dprocess.py
- seleniumbase/undetected/options.py
- seleniumbase/undetected/patcher.py
- seleniumbase/undetected/reactor.py
- setup.py
* Refactor UC Mode
--> Changes: https://github.com/seleniumbase/SeleniumBase/commit/bdd383476d03c6741b79a3665bddfa9fbc690fad
--> Changes: https://github.com/seleniumbase/SeleniumBase/commit/3727f31a560c2eab8537e7d458132419aa22bcb8
> Refactor UC Mode

- .github/workflows/python-package-legacy.yml
- .github/workflows/python-package.yml
> Upgrade ubuntu to 22.04 on GitHub Actions

- README.md
- mkdocs_build/requirements.txt
- seleniumbase/plugins/pytest_plugin.py
> Documentation update

- .github/workflows/python-nightly-mac.yml
- .github/workflows/python-nightly-ubuntu.yml
- .github/workflows/python-nightly-windows.yml
> Add Nightly Tests

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_caseplans.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/console_scripts/sb_print.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- setup.py
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1781
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1782
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1783
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1784
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1785
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1786
> Six Bug Fixes

- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Add more methods for saving and parsing data to/from files
--> This resolves #1789
* Also refresh Python dependencies:
--> https://github.com/seleniumbase/SeleniumBase/commit/41d94435864f46dae43d859547ba8fc59b2e0729
> More methods for saving and reading file data

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* Update SeleniumBase Commander
--> https://github.com/seleniumbase/SeleniumBase/commit/e1edf96e3ad08ecc1da0088bd7391027f35a621f
* Update the code that returns unique links
--> https://github.com/seleniumbase/SeleniumBase/commit/5bc620942a8b66e2478c40ef26f8cbfc2bf0c242
* If deleting cookies, wait for page loads to complete first
--> https://github.com/seleniumbase/SeleniumBase/commit/ce54ec7ce80dc6b5bcf11161a45be4a3afc954d0
--> https://github.com/seleniumbase/SeleniumBase/commit/7cfd6f9f55bb6e24975a18640f8b2df06e957799
> A Few Updates

- examples/tour_examples/bootstrap_google_tour.py
- examples/tour_examples/google_tour.py
- examples/tour_examples/hopscotch_google_tour.py
- examples/tour_examples/introjs_google_tour.py
- examples/tour_examples/shepherd_google_tour.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Fix issue with headed mode on Linux
--> https://github.com/seleniumbase/SeleniumBase/commit/2ee05abdf6726f168c24d8802c693d75fc21145b
--> (Info: ``--headed`` mode still used ``xvfb``, which hid the browser window)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1808
* Fix log time offset from UTC during Daylight Savings
--> https://github.com/seleniumbase/SeleniumBase/commit/bb2e66d785da1ebf8a4798f9a8ecd564882788c7
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1809
--> https://github.com/seleniumbase/SeleniumBase/commit/43bc256ea5a7334bb3475f4473037d56ad3431d4
> Fix headed mode on Linux and the log time offset

- examples/locale_code_test.py
- examples/master_qa/pytest.ini
- examples/migration/raw_selenium/pytest.ini
- examples/pytest.ini
- examples/test_login.py
- examples/translations/pytest.ini
- mkdocs_build/requirements.txt
- pytest.ini
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/console_scripts/sb_mkdir.py
- setup.py
* Refactor pytest.ini
--> https://github.com/seleniumbase/SeleniumBase/commit/402a86da26786e4dbeb3227bddca7ac01e01179f
* Update Commander defaults
--> https://github.com/seleniumbase/SeleniumBase/commit/074f0f059227a1b75da6a079b378f39abcbd8a67
--> Usage: ``sbase gui`` on the command-line
--> https://github.com/seleniumbase/SeleniumBase/commit/e1d74a27c2dbeb508ce125114e88287218be76b0
> Refactor pytest.ini and more

- examples/hack_the_planet.py
- examples/test_download_files.py
- examples/test_download_images.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
--> https://github.com/seleniumbase/SeleniumBase/commit/0ab66092b7881df119f2625cee3a0f66626c625c
* Use Guest Mode by default for Edge tests on Windows
--> https://github.com/seleniumbase/SeleniumBase/commit/50430d600ce12fd7dac5f7e47a767d628ac9baf2
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1842
> Refresh dependencies and fix a bug

- examples/presenter/edge_presentation.py
- examples/test_skype_site.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Update tour logic
--> https://github.com/seleniumbase/SeleniumBase/commit/5f5dca824508ee287abd7322da33817fdf777ec6
* Update error-handling
--> https://github.com/seleniumbase/SeleniumBase/commit/7cb08f935a9ec1a93bb79313bbab584fe2897521
* Set default user_agent in mobile mode if not set
--> https://github.com/seleniumbase/SeleniumBase/commit/1757793067d229ff8d80cfb34191361a8f08943c
--> https://github.com/seleniumbase/SeleniumBase/commit/4eb176eceaf9ee76eb111119548e75f1838e38fa
> Update tours and mobile mode

- examples/hack_the_planet.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_caseplans.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
* Update colors of GUI apps
--> https://github.com/seleniumbase/SeleniumBase/commit/7e2995373393c7c40a52166f6a1dd35a645a8ae8
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1862
* Fix issue with self.has_exception()
--> https://github.com/seleniumbase/SeleniumBase/commit/c1b355d5f0bbb940288b0f3fff1499208bc7b4fa
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1861
--> https://github.com/seleniumbase/SeleniumBase/commit/d05532e046687e912e401aaaf97a9ca3bba2d962
> GUI colors and fixes

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/unittest_helper.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Refactoring
--> https://github.com/seleniumbase/SeleniumBase/commit/3c260affd02d99a13cc14d352f00021f2b58d077
--> This improves compatibility and fixes issues with Python ``3.11`` and ``3.12``.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1864
--> This includes an improvement to stack traces in the ``basic_test_info.txt`` file.
--> Some of this is related to changes in ``unittest`` between Python ``3.10`` and ``3.11``.
> Version compatibility and logging

- seleniumbase/__version__.py
- seleniumbase/undetected/__init__.py
* https://github.com/seleniumbase/SeleniumBase/commit/a29101cbb0d9aeb80923a643761869d5896a9ac3
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1867
> Fix issue with setting user_data_dir in --uc mode

- examples/test_download_files.py
- examples/test_todomvc.py
- examples/user_agent_test.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Make a message more helpful
--> https://github.com/seleniumbase/SeleniumBase/commit/88298c17df0bfd3bfc0c4cbbae037cb6a795901a
--> https://github.com/seleniumbase/SeleniumBase/commit/bcecc11a4e891622ee75cee07c709335293f54bf
> Some refactoring

- examples/migration/protractor/mat_paginator_test.py
- examples/wordle_test.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix issue with long filenames in logs
--> https://github.com/seleniumbase/SeleniumBase/commit/0d4fc83639cb8913c10429f965b667dfb8a6ba38
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1882
* Also refresh Python dependencies
--> https://github.com/seleniumbase/SeleniumBase/commit/c8e2da2fb0d7d0ce8fe285cc34ea5ad5eb709f10
> Fix issue with long filenames in logs

- examples/presenter/edge_presentation.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* Avoid notifications on Edge when possible
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1897
> Avoid notifications on Edge when possible

- seleniumbase/__version__.py
- seleniumbase/core/mysql.py
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1943
> Improve MySQL error messages

- seleniumbase/__version__.py
- seleniumbase/core/mysql.py
* [Fix issue with a missing PyMySQL dependency](https://github.com/seleniumbase/SeleniumBase/commit/b23e33a8551f426a1740cb1b21c6a67d909a7b5d)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1945
> Fix issue with the MySQL integration

- examples/translations/korean_test_1.py
- help_docs/syntax_formats.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkchart.py
- seleniumbase/console_scripts/sb_mkfile.py
- seleniumbase/console_scripts/sb_mkpres.py
- setup.py
* [Refactor file generators](https://github.com/seleniumbase/SeleniumBase/commit/905367aafc2ace421fac320b04685932b68bd3bb)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1957
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/33f8304cb47a002afaa81763fc68707220d95f75)
* [Update the Korean example test](https://github.com/seleniumbase/SeleniumBase/commit/6180efa849b0103d96fd3cb6e1831e0ddd48af75)
> Refactor file generators

- README.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/__init__.py
* [Fix an issue with Chrome 115 automation](https://github.com/seleniumbase/SeleniumBase/commit/f288aedb85a650df35fcdd2b328ebdd64ea1af0c)
* This was caused by https://chromedriver.chromium.org/downloads stopping at 114
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1966
> Fix an issue with Chrome 115 automation

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1995
* Also [Refresh the pdbp (Pdb+) dependency](https://github.com/seleniumbase/SeleniumBase/commit/bf96feb56f06177e5d49b7cb952f18e1b6d4a36a)
> Fix issue with proxies in UC Mode

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Fix issue that occurs if a driver path contains spaces](https://github.com/seleniumbase/SeleniumBase/commit/d4355ed493f3d933b9bfbd6fa0d6401f2fb11438)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1996
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/3b1643be55eafa9fbe1888de88f88a41220bbb01)
* [Refresh Python dependencies (Pdb+)](https://github.com/seleniumbase/SeleniumBase/commit/0cca424a72686de0db9afa197eb24e93c2d8e3a8)
> Fix a bug, update UC Mode, and upgrade Pdb+

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
* [Optimize timeouts in requests](https://github.com/seleniumbase/SeleniumBase/commit/0a3eddcf4233664f43858b05ce8bb0d04d6862e1)
In particular, if you're trying to download a driver while behind a VPN (eg. Cisco AnyConnect), then the download will complete much sooner.
> Optimize timeouts in requests

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/detect_b_ver.py
- seleniumbase/fixtures/constants.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Improve UC Mode on Linux](https://github.com/seleniumbase/SeleniumBase/commit/35b44d29c288aa79761644d853a840a71f1dfc62)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2018
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/46f92df3b3440b2ba1be1b322ce578b3911c9809)
> Improve UC Mode on Linux

- examples/offline_examples/test_extended_driver.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/page_actions.py
* [Refactor the extended "driver" instance](https://github.com/seleniumbase/SeleniumBase/commit/b3bb993677984fec2c0efaeebc350c18b35581ec)
* [Add a "sleep" method directly into "driver" instances](https://github.com/seleniumbase/SeleniumBase/commit/97fcf2202306cc9e2a8f6cc487136c9f100082b7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2090
> Refactor extended `driver` instances

- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/proxy_helper.py
* [Fix issue with authenticated proxy and proxy_bypass_list](https://github.com/seleniumbase/SeleniumBase/commit/4e7b87f696eaac6df5a9a16c9c83d399cbdc845e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2093
* [Update default Edge preferences](https://github.com/seleniumbase/SeleniumBase/commit/c9b895e6aaf00d45ca6fa123d95fcb4f492fb62c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1897
> Fix proxying with auth, proxy_bypass_list, and Edge notifications

- README.md
- examples/uc_cdp_events.py
- examples/verify_undetected.py
- help_docs/method_summary.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Make improvements to UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/6f5257d22e955652e798f0eafb95252e1828496a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2112
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2114
* [Add methods for verifying downloads via regex](https://github.com/seleniumbase/SeleniumBase/commit/abcd21df30182d1f39e2e4e421df216460f240a8)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2113
--> New method: `self.is_downloaded_file_regex_present(regex)`
--> New method: `self.assert_downloaded_file_regex(regex, timeout=None)`
* [Refresh optional Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/417aaf7917c3e2474db27c90a3cd8d2f9579f554)
> Update UC Mode and add methods for verifying downloads via regex

- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_driver.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Make convenience updates to "driver.find_element()"](https://github.com/seleniumbase/SeleniumBase/commit/c613b2d44701b0427a3ad73ed98e931dd9324d40)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2122
* [Prevent "StaleElementReferenceException" with "js_click()"](https://github.com/seleniumbase/SeleniumBase/commit/d341191f0f2a913912cf982acb9edec587177758)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2124
* [Make "__check_browser()" a non-private method](https://github.com/seleniumbase/SeleniumBase/commit/e7286c6cdedb670a17ef8f9f3a78672715a4c262)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2123
* [Add option: --driver-version="keep"](https://github.com/seleniumbase/SeleniumBase/commit/ecb23ad988027892627c6275c6f83376 …
> `driver` updates and internal methods

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_caseplans.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/__init__.py
* [Refactor GUI apps](https://github.com/seleniumbase/SeleniumBase/commit/6ac74b9ce6eebad1d7628408dfc34dc59334d2de)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2179
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2177
* [Refactor UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/547e617f5dd5bf2cdabb06ad416c90e59f858f7d)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2176
> Refactor GUI apps and UC Mode

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Prevent various prompts from appearing](https://github.com/seleniumbase/SeleniumBase/commit/f20ae06d7189e030e8932edc4e3622310b9fade1)
--> Prevent "Customize Chrome", "Permission", and "Translate" prompts from appearing.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2203
> Prevent various prompts

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Hide the "Find your downloads here" bubble on Chrome](https://github.com/seleniumbase/SeleniumBase/commit/2485d8fe206abd418ba9a5034cbbebf561061fb5)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/2293
> Hide the "Find your downloads here" bubble on Chrome

- seleniumbase/__version__.py
- seleniumbase/fixtures/constants.py
* [Add Chromium browsers for use via "binary_location"](https://github.com/seleniumbase/SeleniumBase/commit/9b6aea4f5974392c92ee223002541f56414ae3f4)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2324
> Additional Chromium Browsers

- LICENSE
- examples/shadow_root_test.py
- examples/test_cdp_ad_blocking.py
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Welcome to 2024](https://github.com/seleniumbase/SeleniumBase/commit/cdcde247da61f1fb54c1dc5f2009472ff4899b3f)
* [Upgrade the default geckodriver version to v0.34.0](https://github.com/seleniumbase/SeleniumBase/commit/2de1ad3456bd4c42f037ab64333d73406fd17f6a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2411
* [Improve the method for saving overlay text on images](https://github.com/seleniumbase/SeleniumBase/commit/6519f87f34da0a0fdc70a6f08f4a784e5290a4d5)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2412
* [Fix the Browserstack integration](https://github.com/seleniumbase/SeleniumBase/commit/50f8a0330eaec87893556e5c58c070c5ce53ea91)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2401
----> (To activate, include …
> Welcome to 2024

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
* [Update chromedriver download origin](https://github.com/seleniumbase/SeleniumBase/commit/c8d59f24fb142ed55f01fc617988a00d288a1e9c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2519
> Update the chromedriver download origin

- examples/offline_examples/test_demo_page.py
- examples/raw_form_turnstile.py
- examples/raw_nopecha.py
- examples/raw_pixelscan.py
- examples/raw_turnstile.py
- examples/raw_uc_mode.py
- examples/test_demo_site.py
- examples/verify_undetected.py
- help_docs/method_summary.md
- help_docs/uc_mode.md
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/webelement.py
* [Allow truncated URLs in UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/e3d4deb7c4a764e49c2b38b4e15e31b300202bac)
* [Allow customized timing for "uc_switch_to_frame()"](https://github.com/seleniumbase/SeleniumBase/commit/b2329c19b5a65d2238fc88bc983fe31d01f6387f)
* Update the default `reconnect_time` for `uc_click()`
* Update a test file generated by `sbase mkdir DIR`
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/e5281a107f93bd047feb2b2fbfb73ece3679c995)
* Update some documentation
> Mostly UC Mode updates

- examples/raw_bing_captcha.py
- examples/raw_cdp_logging.py
- examples/raw_nopecha.py
- examples/raw_robot.py
- examples/raw_uc_mode.py
- examples/test_3d_apis.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_driver.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Add methods and update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/dc86046193ba25b4cd21117a3bfb6e24c3c416e4)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2581
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2582
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2583
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2584
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2585
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/f1c91d8aa7b9c16eaed8cabc834b882999d43582)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/516d9b2679021a2171db350e515028fd04f49111)
> More methods and UC Mode updates

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/shared_utils.py
* [Update IE Compatibility Mode](https://github.com/seleniumbase/SeleniumBase/commit/6541cf8017f6bc71c348bd4026c2d152304e7855)
* [Refactor the code](https://github.com/seleniumbase/SeleniumBase/commit/b0952747ac8db578052b497ba27893fecabdc64f)
> Refactoring and IE compatibility

- seleniumbase/__version__.py
- seleniumbase/core/detect_b_ver.py
* [Fix the "binary_location" option on Windows](https://github.com/seleniumbase/SeleniumBase/commit/c522c2379023910d1f359a809ac6ebc0e5d639f1)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2610
> Fix the `binary_location` option on Windows

- seleniumbase/__version__.py
- seleniumbase/core/detect_b_ver.py
----
* [Fix issue with getting browser version from Chrome-for-Testing on Windows](https://github.com/seleniumbase/SeleniumBase/commit/d45641459b372ef5d0e72acc0355fa0547a1c7dd)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2613
> Fix issue with getting browser version from Chrome-for-Testing on Windows

- README.md
- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add more cookie methods](https://github.com/seleniumbase/SeleniumBase/commit/e495530413bffcfb047d23322b2a522ef56602c4)
* [Refresh optional Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/94206e0de02807a55ff953683e9b2e4a00087faf)
> Add more cookie methods

- Dockerfile
- examples/raw_games.py
- integrations/docker/ReadMe.md
- integrations/docker/docker_config.cfg
- integrations/docker/run_docker_test_in_firefox.sh
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Update the Docker integration](https://github.com/seleniumbase/SeleniumBase/commit/66394b359fea84bf3e3ede7d89e1b5fb16d33b8b)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2692
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2690
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/6b84d945e2dda92eaeb93c7c08164fbc6ff3c91c)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/e657a86427707db0d731df1106dfa328597b1081)
> Docker overhaul and more

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Downgrade pytest temporarily to fix an issue](https://github.com/seleniumbase/SeleniumBase/commit/a2fa210cf9893c00b2bb715e9fa3e61af77c7830)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2832
> Downgrade the `pytest` version to fix an issue

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Refactor Chromium options](https://github.com/seleniumbase/SeleniumBase/commit/5846a70db998ef79a1b6ca05f02bdd6c2ab29c83)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2836
> Refactor Chromium options

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Update default browser options](https://github.com/seleniumbase/SeleniumBase/commit/0c46e2c9cbf2e3c1521e269cabdbc859dd7c5157)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/f1579d0d76c86187e6d1ca4116b196ba573e23b4)
> Update default browser options

- examples/raw_bing_captcha.py
- examples/raw_gui_click.py
- examples/raw_nopecha.py
- examples/raw_order_tickets.py
- examples/raw_pyautogui.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/ee916874035de376eb41513df6ec281070c34ec4)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2957
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/383579765d132976bbfd144aafe1b8f9af63f5e7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2956
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/149afd6cc223f50ff071d4903f7dc4be5952ea02)
> Refresh dependencies and UC Mode

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/164f0558860ab2a2c6e7588cc1d839796dff7e87)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2962
> Update UC Mode CAPTCHA-bypass

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
* [Update error-handling for Mobile Mode](https://github.com/seleniumbase/SeleniumBase/commit/9a518568d4f88a47c1c6d8bc8aabb7f21b5778b7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2985
> Update Mobile Mode

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix issue with UC Mode clicking on Windows](https://github.com/seleniumbase/SeleniumBase/commit/0bcfc3aaf99e2b4027a1b96cd062098524e2221c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3007
> Fix UC Mode clicking on Windows

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/0160a135ae9aaecda43f155d383d0a44438b54c7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3128
> UC Mode: Reload & Click, as needed

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* [Activate virtual display after all settings are parsed](https://github.com/seleniumbase/SeleniumBase/commit/0628210b2cec59cb59642a537df62ffd0d552c5d)
* [Refactor options](https://github.com/seleniumbase/SeleniumBase/commit/b52f9b0ada76f80804a256ec34eb8e11171bf79d)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/5805c0d59469b96a544db4804a40b2bd6476bbd4)
> Fix Xvfb settings and refactor

- seleniumbase/common/ReadMe.md
Commit 5764a4cd9fd80fdb6df28f8e6f27e2749ad9ab62 renamed the test decryption file. This PR adjusts sources to changes.
> Update test decryption reference

- examples/cdp_mode/raw_albertsons.py
- examples/cdp_mode/raw_cf.py
- examples/cdp_mode/raw_nordstrom.py
- examples/cdp_mode/raw_pixelscan.py
- examples/cdp_mode/raw_res_nike.py
- examples/cdp_mode/raw_tiktok.py
- examples/raw_pixelscan.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/proxy_helper.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/shared_utils.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/undetected/cdp_driver/element.py
* [Improve CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/a1a3b659da940dd68c761a09c79741ff5c7c857a)
* [Improve multi-threading](https://github.com/seleniumbase/SeleniumBase/commit/eeff476f67f607ca5cbc57cc1974306b1b1ddcaa)
* [Add new CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/be1a182e5a5a5ef555ed23273231f1ed3f4763a6)
> CDP Mode - Patch 17

- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* [Fix missing argument bug in CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/d0a3c67d440d205db0f6f3bdb3f8f0a6da627209)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3415
> CDP Mode - Patch 25

- examples/cdp_mode/raw_cdp_methods.py
- examples/cdp_mode/raw_cdp_nike.py
- examples/cdp_mode/raw_driver.py
- examples/raw_games.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/1c0987b79f5a761dc0c151806c0a5f98478fcfd0)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3483
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3485
--> This improves the `uc_gui_click_captcha()` method.
* [Update examples for UC Mode / CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/1e25659c3bc05b106592f44380e56b91ccb5f670)
--> (3 examples added. 1 example updated.)
* [Do some refactoring](https://github.com/seleniumbase/SeleniumBase/commit/d29006549e37c710aa7158b18ece891feaf94b0e)
--> This prevents the new warnings from `BeautifulSoup`.
> CDP Mode - Patch 30

- seleniumbase/__version__.py
- seleniumbase/core/proxy_helper.py
* [Revert the proxy scheme change from the previous release](https://github.com/seleniumbase/SeleniumBase/commit/7b342ce6efa76aafeae805023449679780594ad3)
--> The previous change uncovered issues that weren't originally seen
--> Going back to the way done in https://stackoverflow.com/a/35293284
> Revert proxy scheme change

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/74b57669ff85d2a524b344a252a8c4472ea2c129)
> Selenium update

- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
* [Fix CDP Mode issues](https://github.com/seleniumbase/SeleniumBase/commit/a68f33ce0d883e500bedac8cb2519a3fc6aed37a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3654
> Fix CDP Mode issues

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/connection.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/96b015adf44fbd776075fd5c15bea82aa5d69143)
--> This fixes a memory leak issue.
--> This also resolves https://github.com/seleniumbase/SeleniumBase/issues/3719
> CDP Mode: Patch 47

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix bug with headless UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/74bb35d15a4c6d2ae8047c1e11a550d13c6eef2a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3744
--> (This fixes a regression in the previous release.)
> Fix headless UC Mode

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_driver.py
- examples/cdp_mode/raw_planetmc.py
- help_docs/syntax_formats.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_driver.py
- seleniumbase/fixtures/page_actions.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/b339c5c3136a83df5e44ae506ffb3ed94a24ec80)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/b0ebf8bf9aa80dda63bc99c8de54db997ce1235d)
> CDP Mode: Patch 60
