- README.md
- conftest.py
- docker/docker_setup.py
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Demo Mode allows you to run your SeleniumBase scripts at a slower speed so that your audience has a chance to see what the automation is doing, because otherwise it can move too fast for the human eye.
Usage:
--demo_mode (from the command line)
You can update the default wait in either settings.py or from the command line:
--demo_sleep=1.2
> Demo Mode for SeleniumBase

- integrations/google_cloud/Linuxfile.sh
- integrations/google_cloud/ReadMe.md
- integrations/google_cloud/Xvfb_launcher.sh
- integrations/google_cloud/jenkins_permissions.sh
This pull request adds support for using SeleniumBase with a Jenkins virtual machine running on the Google Cloud Platform.
> Add Google Cloud Jenkins integration

- .gitignore
- integrations/docker/docker_setup.py
- integrations/selenium_grid/ReadMe.md
- integrations/selenium_grid/download_selenium.py
- integrations/selenium_grid/grid-hub
- integrations/selenium_grid/grid-node
- integrations/selenium_grid/start-selenium-node.bat
- integrations/selenium_grid/start-selenium-server.sh
- setup.py
Making life easier for those using the Selenium Grid
> Selenium Grid overhaul

- conftest.py
- seleniumbase/fixtures/base_case.py
This will allow pytest runs to write to a MySQL DB
> DB reporting plugin for pytest

- integrations/docker/docker_setup.py
- seleniumbase/fixtures/base_case.py
- setup.py
There were two issues:
One: The link to log files uploaded to S3 in MySQL wasn't showing up on test failures during pytest runs.
Two: The exception message was missing in MySQL on test failures during pytest runs.
> Fix MySQL pytest plugin

- integrations/google_cloud/ReadMe.md
- integrations/linux/Linuxfile.sh
This will improve the Linuxfile, which is used to install all SeleniumBase dependencies on a Linux machine.
> Linux improvements

- integrations/docker/docker_setup.py
- seleniumbase/core/mysql.py
- seleniumbase/fixtures/base_case.py
- setup.py
One of the changes made is that SeleniumBase will now try to connect to the MySQL database before running tests if the MySQL option is turned on.
Also, the time to fail is lowered in the case that SeleniumBase can't connect to the MySQL DB when the MySQL option is turned on.
> MySQL updates

- README.md
- examples/test_fail.py
- seleniumbase/fixtures/page_actions.py
- setup.py
Methods such as self.driver.switch_to_[X] have become self.driver.switch_to.[X]
> Replace deprecated methods

- seleniumbase/fixtures/page_actions.py
Should be "switch_to.alert" not "switch_to.alert()". Oddly enough.
> Fix switching to an alert.

- .gitignore
- README.md
- examples/my_test_suite.py
- seleniumbase/config/settings.py
- seleniumbase/core/report_helper.py
- seleniumbase/core/style_sheet.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/plugins/base_plugin.py
- setup.py
Usage: "--report" (Also requires: "--with-testing_base")
This will create an html report page after tests finish running.
The report contains detailed test info, a table of tests run, screenshots, etc.
Adding "--hide_report" will archive the report rather than displaying it after the test suite completes.
> Add the option to save reports for test runs

- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
The big thing here is that newer syntax will make the code more understandable to readers.
self.assert_element(ELEMENT) vs self.find_element(ELEMENT)
self.assert_text(TEXT, ELEMENT) vs self.find_text(TEXT, ELEMENT)
self.assert_link_text(LINK_TEXT) vs self.find_link_text(LINK_TEXT)
It wasn't clear with older methods what would happen if the element wasn't found.
In some cases, we just wanted an assert. The older methods will still return the element. Each version will fail if the element isn't found.
Older method names kept for backwards compatibility.
> Revamp framework

- README.md
- examples/non_terminating_checks_test.py
- help_docs/method_summary.md
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
Ever wanted to check multiple elements on a page without having your test exit after the first failure? In this latest update to SeleniumBase, I bring you non-terminating checks! Here's how it works:
```python
from seleniumbase import BaseCase
class MyTestClass(BaseCase):
def test_non_terminating_checks(self):
self.open('http://xkcd.com/993/')
self.wait_for_element('#comic')
self.check_assert_element('img[alt="Brand Identity"]')
self.check_assert_element('img[alt="Rocket Ship"]')  # Will Fail
self.check_assert_element('#comicmap')
self.check_assert_text('Fake Item', '#middleContainer')  # Will Fail
self.check_assert_text('Random', '#middleContainer')
self.check_assert_element('a[name="Super Fake !!!"]')  # Will Fail
self.process_checks()
```
New methods ``self.check_assert_element()`` and …
> Add the non-terminating checks feature for tests.

- examples/gui_test_runner.py
- requirements.txt
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- server_requirements.txt
- setup.py
The multi-assert feature allows you to assert multiple elements at the same time and have all the failing assertions fail together so that you can find all the problems on a page at one time without having to rerun the test after fixing each individual issue.
> Update the multi-assert feature

- conftest.py
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/masterqa/master_qa.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
The verify_delay for MasterQA is the number of seconds to pause the screen before each verify() call creates a pop-up for the manual QA tester. The default is 1.0 seconds, which is set in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/config/settings.py
This delay gives the manual QA tester time to inspect the page freely without the question pop-up.
> Add the option to set the MasterQA verify delay from the command line

- requirements.txt
- server_requirements.txt
- setup.py
Use hard selenium version of 2.53.6 because otherwise the latest version of selenium is 3.* and that is causing tests to break due to the new Geckodriver.
> Fix deploy - Keep using Selenium 2 until ready for 3

- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
Also changed the profile setting for download complete animation from default true values to false so clicking on element does not fail due to active download complete animations.
> Update selenium version to fix Firefox browser not starting with profile

- seleniumbase/core/download_helper.py
Currently if the download directory path contains wrong OS path separator, then Firefox will not use that path as valid download directory path.  This will construct the download directory path using os.path.join so  OS specific path separator is used.
> Correctly set download directory in Windows Firefox

- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- server_setup.py
- setup.py
The check_assert system may have been confusing to SeleniumBase users. It was built to allow a test to make multiple assertions on a page without raising any test failures until all desired check_asserts were called and then self.process_checks() called after that.
The check_asserts include self.check_assert_element() and self.check_assert_text().
Rather than fail a test immediately after the first assertion failure, the test failure is delayed until later when more assertions have been made. The issue arose when SeleniumBase users called the check_assert methods in their tests without calling self.process_checks() afterward. This led to tests that had failed assertions that were never raised at the end of the test, giving the test a Pass instead of a Fail when it should be failing. Now, …
> Improve check_assert system

- requirements.txt
- seleniumbase/fixtures/base_case.py
- server_requirements.txt
- server_setup.py
- setup.py
Going from BeautifulSoup to BeautifulSoup4
(This is a Python HTML-parsing library)
> Upgrade BeautifulSoup Python Library

- examples/gui_test_runner.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- server_setup.py
- setup.py
Log files were missing when running tests tests in Python 3 due to differences in method functionality between Python 2 and Python 3. These changes will allow the logs to be complete when running tests using Python 3 pytest or nosetests.
> Fix Python 3 Logging Issue

- README.md
- requirements.txt
- seleniumbase/config/settings.py
- seleniumbase/core/browser_launcher.py
- server_requirements.txt
- server_setup.py
- setup.py
Have option to run Chrome in full screen mode by default
Other Chrome and Chromedriver improvements
> Improvements for running tests in Chrome

- seleniumbase/common/ReadMe.md
- seleniumbase/common/encryption.py
- seleniumbase/common/obfuscate.py
- seleniumbase/common/unobfuscate.py
- seleniumbase/config/settings.py
- server_setup.py
- setup.py
Adding a system for obfuscating passwords. Obfuscated passwords can then be decrypted back into the original passwords for tests.
> Password Obfuscation

- .travis.yml
- README.md
- _config.yml
The travis deploy script will now use Geckodriver with a newer version of Firefox.
> Update the deploy script and the ReadMe

- help_docs/ReadMe.md
- help_docs/before_installation.md
- help_docs/hidden_files_info.md
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
* Auto-detect xpath in method calls
* Update Help Documents
> Auto-detect xpath in method calls

- README.md
- _config.yml
- help_docs/method_summary.md
- seleniumbase/core/download_helper.py
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Adding methods for processing downloaded files from tests
> Adding methods for processing downloaded files

- README.md
- integrations/selenium_grid/ReadMe.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Small updates:
Updated some exception-handling.
Updated some timing.
Updated some ReadMe files.
> Small updates

- help_docs/method_summary.md
- help_docs/webdriver_installation.md
- seleniumbase/config/proxy_list.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- server_setup.py
- setup.py
Updating Chrome options for a smoother automation experience.
Expanding valid proxy server input requirements from ip:port to also include host:port
Adding method: self.get_property_value()
> Update chrome options; update valid proxy input; and add a method

- .travis.yml
- README.md
- examples/github_test.py
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
* self.open_new_window(switch_to=True)
* self.switch_to_window(window, timeout=settings.SMALL_TIMEOUT)
* self.switch_to_default_window()
* self.get_new_driver(browser=None, headless=None, servername=None, port=None, proxy=None, switch_to=True)
* self.switch_to_driver(driver)
* self.switch_to_default_driver()
> More methods for handling webdriver actions

- README.md
- seleniumbase/fixtures/base_case.py
- setup.py
* Use plain javascript instead of jQuery when highlighting elements because some websites (such as GitHub) have Content Security Policy directives that prevent loading jQuery for custom scripts.
* If waiting for angularjs to load as part of ready state, wait less time
* Set maximum time for activating jQuery to be settings.MINI_TIMEOUT
> Minor updates

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
Use Python standard library methods when possible:
I'm replacing an old method I wrote a long time ago called jq_format() with a Python standard library method that I probably didn't know about then, called re.escape(), which performs the same intended action.
> Use Python standard library methods when possible

- help_docs/method_summary.md
- seleniumbase/config/ad_block_list.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Add ad-blocking functionality
Usage:
On the command line:
"pytest SOME_TEST.py --ad_block"
OR
"nosetests SOME_TEST.py --ad_block"
From inside a test:
self.ad_block()
Uses AD_BLOCK_LIST from seleniumbase/config/ad_block_list.py to determine what gets blocked.
> Add ad-blocking functionality

- .travis.yml
- README.md
- requirements.txt
- setup.py
Fix MySQL installation for windows. (Mainly removing the direct requirement because of issues installing mysqlclient directly)
> Fix MySQL installation for windows

- .travis.yml
- examples/my_first_test.py
- examples/tour_examples/ReadMe.md
- examples/tour_examples/google_tour.py
- help_docs/method_summary.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Introducing SeleniumBase Tours, which integrates the HubSpot Shepherd Library into SeleniumBase for making and running tours on any website. (See http://github.hubspot.com/shepherd/docs/welcome/ for Shepherd details.)
> Add tour feature

- console_scripts/run.py
- integrations/selenium_grid/grid-node
- integrations/selenium_grid/grid_hub.py
- integrations/selenium_grid/grid_node.py
- setup.py
> Small fixes

- console_scripts/run.py
- integrations/selenium_ide/convert_ide.py
- requirements.txt
- setup.py
> Console scripts update

- Dockerfile
- README.md
- integrations/docker/ReadMe.md
- integrations/linux/Linuxfile.sh
- seleniumbase/fixtures/base_case.py
- setup.py
> Fix the Docker integration

- help_docs/webdriver_installation.md
```brew install chromedriver```
fails, needs to be run through cask, ```brew cask install chromedriver```
geckodriver still works through normal install
> updated brew command

- .gitignore
- .travis.yml
- README.md
- console_scripts/ReadMe.md
- console_scripts/run.py
- console_scripts/sb_install.py
- console_scripts/sb_mkdir.py
- drivers/ReadMe.md
- examples/ReadMe.md
- examples/my_first_test.py
- help_docs/customizing_test_runs.md
- help_docs/webdriver_installation.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* You can now install web drivers by using seleniumbase console scripts:
```
seleniumbase install chromedriver
seleniumbase install geckodriver
seleniumbase install edgedriver
```
(SeleniumBase takes care of determining the latest version for your operating system's platform, downloading the zip file, extracting the driver from the zip file to the SeleniumBase ``drivers/`` folder, and setting the permissions of the driver with "chmod" to make it executable for browser tests.)
* You can now run tests in headless mode without using pyvirtualdisplay.
Usage:  ``--headless``. (Make sure you have the latest versions of Chrome and Firefox installed.)
```
pytest my_first_test.py --browser=chrome --headless
```
> Console script updates and driver updates

- examples/example_logs/ReadMe.md
- help_docs/features_list.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/plugins/base_plugin.py
- setup.py
* Don't let Firefox install updates in the middle of a test run
* Keep console logs under control when running Chrome on Windows
* Avoid multi-threaded test runs when using nosetests (Use pytest instead!)
> Fix edge cases

- README.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Internet Explorer optimization (because people are still using that browser, surprisingly)
> Internet Explorer optimization

- help_docs/features_list.md
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* Fix a bug with website tours.
* Add save_data_as() method.
> Fix a bug and add a new method

- requirements.txt
- seleniumbase/common/encryption.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/style_sheet.py
- seleniumbase/core/testcase_manager.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/fixtures/xpath_to_css.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
Fixing bugs that were seen when switching to Python 3.7.0
After some investigation, I learned that the functionality of Python's re.escape() has changed between Python 3.6.5 and Python 3.7.0:
Python 3.6.5:
```python
>>> import re
>>> re.escape('"')
'\\"'
```
Python 3.7.0:
```python
>>> import re
>>> re.escape('"')
'"'
```
Also fixing an unrelated bug with Geckodriver automatic downloads. To do this, I switched to using urllib3.
> Python 3.7.0 compatibility

- examples/boilerplates/samples/google_objects.py
- examples/boilerplates/samples/google_test.py
- examples/tour_examples/ReadMe.md
- examples/tour_examples/bootstrap_google_tour.py
- examples/tour_examples/google_tour.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- setup.py
> Tour updates

- seleniumbase/fixtures/base_case.py
- setup.py
Convert XPATH to CSS Selector before using a hover method.
* Applies to hover_on_element() and hover_and_click()
> Fix XPath hover methods

- requirements.txt
- seleniumbase/console_scripts/sb_install.py
- setup.py
Sync "requests" and "urllib3" dependencies
Based on compatibility issues between python "requests" and "urllib3" (See https://github.com/requests/requests/issues/4830 ) I'm locking down the versions used in seleniumbase to keep them in sync and prevent dependency conflicts. I'll check frequently on newer versions of those libs to see if I can safely update the version used in seleniumbase.
> Sync "requests" and "urllib3" dependencies

- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
Fix issue with proxy server auth in chrome headless mode.
When using a proxy server that has authentication with Chrome in headless mode, SeleniumBase will now use PyVirtualDisplay (already implemented in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/fixtures/base_case.py) rather than using Chrome's built-in headless mode because Chrome doesn't allow extensions when using headless mode. This assumes that the user's system already supports Xvfb (the headless display system) in order to run with PyVirtualDisplay.
See https://bugs.chromium.org/p/chromium/issues/detail?id=706008 , where a member from the Chromium team says: "Headless mode doesn't currently support extensions".
> Fix issue with proxy server auth in chrome headless mode

- requirements.txt
- seleniumbase/common/encryption.py
- seleniumbase/core/s3_manager.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/email_manager.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/fixtures/xpath_to_css.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
Upgrade flake8 version and make fixes based on it
> Upgrade flake8 version and make fixes based on it

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
Fix edge case with BaseCase tearDown() method
* If running tests with ``--pdb``, tests would fail if there were no errors. Now fixed.
> Fix edge case with BaseCase tearDown() method

- examples/capabilities/ReadMe.md
- examples/capabilities/sample_cap_file_BS.py
- examples/capabilities/sample_cap_file_SL.py
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/capabilities_parser.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Allow users to specify browser desired capabilities for webdriver when running SeleniumBase tests on a remote SeleniumGrid server such as [BrowserStack](https://www.browserstack.com/automate/capabilities), [Sauce Labs](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/), or [TestingBot](https://testingbot.com/support/other/test-options).
A sample run command may look like this: (When run from the ``SeleniumBase/examples/`` folder):
```bash
pytest my_first_test.py --browser=remote --server=username:key@hub.browserstack.com --port=80 --cap_file=capabilities/sample_cap_file_BS.py
```
A regex parser was built into SeleniumBase to capture all lines from the specified desired capabilities file in the following formats:
``'KEY': 'VALUE'``
``caps['KEY'] = "VALUE"``
(Each pair must be …
> Remote desired capabilities

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Set default selector to ``html`` for text-search methods.
(It's also optional now.)
Now you can do something like this:
```python
self.assert_text("SOME TEXT")
```
instead of this:
```python
self.assert_text("SOME TEXT", "html")
```
(Default selector type for selectors: ``by=By.CSS_SELECTOR``)
Methods effected:
``assert_text``
``is_text_visible``
``wait_for_text``
``find_text``
``delayed_assert_text``
``wait_for_text_visible``
``assert_text_visible``
Due to keeping backwards compatibility, a few older methods remain that do the same thing as newer methods. (Method names were shortened from their previous versions.)
> Set default selector to "html" for text-search methods

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Add method/option to check for Javascript errors on page loads:
* New method:
```python
self.assert_no_js_errors()
```
* New command line option:
```bash
--check_js
```
(When the command line option is turned on, Selenium will check for Javascript errors after every page load.)
> Add method/option to check for Javascript errors on page loads

- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
Spell "JavaScript" like this.
Changing several spellings of "Javascript" to "JavaScript" for accuracy.
> Spell "JavaScript" like this

- help_docs/method_summary.md
- seleniumbase/config/proxy_list.py
- seleniumbase/fixtures/base_case.py
- setup.py
Add click_visible_elements(selector) method
Finds all matching page elements and clicks visible ones in order.
If a click reloads or opens a new page, the clicking will stop.
Works best for actions such as clicking all checkboxes on a page.
Example:
```python
self.click_visible_elements('input[type="checkbox"]')
```
> Add click_visible_elements(selector) method

- requirements.txt
- setup.py
> Update pytest requirements

- examples/raw_parameter_script.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- setup.py
Improve Messenger methods and a few other things
* Improve methods for posting in-test messages with JS
* Update pytest-html to >= 1.20.0
* Add an example that can be run without the Pytest unittest runner (AKA pure Python)
> Improve Messenger methods and a few other things

- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
Mostly replacing a pytest deprecated call with a new one to prevent:
``PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.``
The solution involved using ``sb_config`` in place of ``pytest.config.option``
Unrelated, there's also a small update to fix a console script used for downloading the selenium server jar file. (It's only needed when you're trying to run your own Selenium Grid)
> Mostly replacing a pytest deprecated call with a new one

- help_docs/customizing_test_runs.md
This illustrates how to run selenium base tests on CrossBrowserTesting remote devices.
> Adding CrossBrowserTesting remote server example

- help_docs/method_summary.md
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- setup.py
Tour update:
* Save the URL with exported SeleniumBase tours
> Save the URL with exported SeleniumBase tours

- setup.py
Make flake8 requirements more flexible:
``flake8>=3.6.0,<3.8.0``
To resolve https://github.com/seleniumbase/SeleniumBase/issues/276
> Make flake8 requirements more flexible

- seleniumbase/config/settings.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/fixtures/base_case.py
- setup.py
Update webdriver installation script:
* ``seleniumbase install chromedriver`` will now install chromedriver v2.46, except on Linux machines, which may be using older versions of Chrome
* ``seleniumbase install geckodriver`` will now install v0.24.0 (for Firefox)
* ``seleniumbase install operadriver`` will now install v.2.40
Other changes:
* Update starting browser dimensions
> Update webdriver installation script

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Add "limit" argument to methods that return or click multiple elements.
Updated methods:  ("0" means no limit)
* ``self.find_elements(selector, by=By.CSS_SELECTOR, limit=0)``
* ``self.find_visible_elements(selector, by=By.CSS_SELECTOR, limit=0)``
* ``self.click_visible_elements(selector, by=By.CSS_SELECTOR, limit=0)``
Example:
``self.click_visible_elements('[type="checkbox"]', limit=5)``
(Click the first 5 visible checkboxes on a page)
>  Add limit argument to methods that return or click multiple elements

- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Add the ability to save screenshots at the end of tests.
This adds the feature for passing tests. (This feature already existed for failing tests automatically.)
Check the latest_logs folder for the images.
Usage: (on the command line when running tests)
* ``--save_screenshot``
The screenshot will be taken right before the browser is closed.
> Add the ability to save screenshots at the end of tests

- seleniumbase/core/log_helper.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
Add a command-line option to archive old log files rather than deleting them.
If the option is set, log files from the latest_logs folder will get moved to the archived_logs folder for storage. Otherwise, any existing logs in the latest_logs folder will be deleted at the start of the next test run.
Usage: (on the command line when running tests)
* ``--archive_logs``
> Add a command-line option to archive old log files rather than deleting them.

- .gitignore
- README.md
- examples/tour_examples/bootstrap_google_tour.py
- examples/tour_examples/google_tour.py
- examples/tour_examples/hopscotch_google_tour.py
- examples/tour_examples/introjs_google_tour.py
- examples/tour_examples/shepherd_google_tour.py
- examples/tour_examples/xkcd_tour.py
- requirements.txt
- seleniumbase/config/settings.py
- seleniumbase/core/tour_helper.py
- setup.py
* Save exported website tours to the "tours_exported" folder
* Update tour examples
* Set flake8 version to 3.7.7
> Save exported website tours to the "tours_exported" folder 

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
Add methods for setting and removing element attributes:
* Add ``self.set_attribute(selector, attribute, value)``
* Add ``self.remove_attribute(selector, attribute)``
> Add methods for setting and removing element attributes

- .gitignore
- examples/raw_parameter_script.py
- seleniumbase/config/settings.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/masterqa/master_qa.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Add a command-line option to disable the Content Security Policy.
(The CSP may prevent SeleniumBase custom JavaScript abilities from loading on various web pages.)
> Add a command-line option to disable the Content Security Policy

- seleniumbase/fixtures/page_utils.py
- setup.py
Fix method that finds all links on a web page
* Ignore parsing urls on pages that don't have ``://`` in the url (ex: ``about:blank``)
> Fix method that finds all links on a web page

- examples/capabilities/ReadMe.md
- seleniumbase/core/capabilities_parser.py
- setup.py
Allow passing a boolean value to desired capabilities
* All formats as of now:
``'KEY': 'VALUE'``
``'KEY': True``
``'KEY': False``
``caps['KEY'] = "VALUE"``
``caps['KEY'] = True``
``caps['KEY'] = False``
(Each pair must be on a separate line. You can interchange single and double quotes.)
See https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities for the full ReadMe and sample capabilities files.
> Allow passing a boolean value to desired capabilities

- azure-pipelines.yml
- integrations/google_cloud/ReadMe.md
- integrations/linux/jenkins_permissions.sh
- integrations/linux/tomcat_permissions.sh
- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
Some minor updates:
* Use log-level 3 for default Chrome logging
* Use pytest-forked>=1.0.2
* Update Azure test pipeline
> Some minor updates

- examples/run_my_first_test_in_chrome.sh
- examples/run_my_first_test_in_firefox.sh
- examples/run_rate_limiting_test.sh
- examples/run_test_fail_with_logging.sh
- examples/swag_labs_suite.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* Add multithreading to link checking -> ``self.assert_no_404_errors()`` now works faster
* Add pytest-ordering
* Fix method that calculates full links from partial links
* Add slow-scrolling to demo_mode asserts
* Add Swag Labs test suite to the examples
> Add multithreading to link checking; and other improvements

- .travis.yml
- requirements.txt
- seleniumbase/console_scripts/sb_install.py
- setup.py
* Use requests instead of urllib3 for webdriver downloads
> Use requests instead of urllib3 for webdriver downloads

- README.md
- azure-pipelines.yml
- requirements.txt
- setup.py
Editable mode install update.
Due to https://github.com/pytest-dev/pytest/issues/5167 (pip 19.1 prevents pytest from being used in editable mode), I'm taking out the default pip editable mode install.
All this really means now is that now you should run ``python setup.py develop`` after installing the requirements.
> Editable mode install update

- help_docs/customizing_test_runs.md
- integrations/azure/jenkins/ReadMe.md
- requirements.txt
- setup.py
> Update urllib3 version

- Dockerfile
Attempted versions: 1.23.10, 1.17.1
Tried to build the docker image for SeleniumBase, however this appeared:
```
Step 1/30 : FROM ubuntu:17.10
17.10: Pulling from library/ubuntu
4ccdce43d1e0: Pulling fs layer
c95f13c88d92: Pulling fs layer
82656eee95ad: Pulling fs layer
78ff727be57a: Pulling fs layer
448bb314afa5: Pulling fs layer
78ff727be57a: Waiting
448bb314afa5: Waiting
82656eee95ad: Verifying Checksum
82656eee95ad: Download complete
c95f13c88d92: Verifying Checksum
c95f13c88d92: Download complete
4ccdce43d1e0: Verifying Checksum
4ccdce43d1e0: Download complete
448bb314afa5: Verifying Checksum
448bb314afa5: Download complete
78ff727be57a: Verifying Checksum
78ff727be57a: Download complete
4ccdce43d1e0: Pull complete
c95f13c88d92: Pull complete
82656eee95ad: Pull complete
78ff727be57a: …
```
> update base version

- README.md
- azure-pipelines.yml
- examples/master_qa/ReadMe.md
- help_docs/happy_customers.md
- requirements.txt
- seleniumbase/fixtures/constants.py
- setup.py
Performance improvements
* Switch to Cloudflare CDN for jQuery
* Update urllib3, requests, and pluggy versions
> Performance improvements

- README.md
- help_docs/install_python_pip_git.md
- install.bat
- install.sh
- requirements.txt
- setup.py
Pytest update:
* Use pytest >= 4.6.2
> Pytest update (Use pytest >= 4.6.2)

- help_docs/customizing_test_runs.md
- help_docs/features_list.md
- seleniumbase/core/browser_launcher.py
- setup.py
Allow a comma-separated list of Chrome extensions to use
> Allow a comma-separated list of Chrome extensions to use

- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Refactor command-line arguments
> Refactor command-line arguments

- examples/my_first_test.py
- help_docs/happy_customers.md
- integrations/node_js/my_first_test.py
- requirements.txt
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/js_utils.py
- setup.py
Fix pytest-html reports on Windows
* Use pytest-html==1.20.0 (later versions have errors on Windows)
> Fix pytest html reports on Windows

- examples/my_first_test.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Update demo-mode reliability
* Update logging level for "requests" and "urllib3"
> Small updates to reliability and logging

- README.md
- azure-pipelines.yml
- help_docs/how_it_works.md
- help_docs/virtualenv_instructions.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Optimize selector detection and usage
> Optimize selector detection and usage

- requirements.txt
- seleniumbase/core/tour_helper.py
- setup.py
Improve the export feature for website tours
> Improve the export feature for website tours

- README.md
- examples/raw_parameter_script.py
- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Make --headless mode the default setting on Linux
> Make --headless mode the default setting on Linux

- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/masterqa/master_qa.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Add the ability to set the initial URL with the "--start_page" command-line option
> Add ability to set initial URL with "--start_page" cmd option

- requirements.txt
- seleniumbase/common/unobfuscate.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/selenium_plugin.py
- seleniumbase/virtual_display/abstractdisplay.py
- seleniumbase/virtual_display/display.py
- seleniumbase/virtual_display/easyprocess.py
- seleniumbase/virtual_display/unicodeutil.py
- seleniumbase/virtual_display/xauth.py
- seleniumbase/virtual_display/xephyr.py
- seleniumbase/virtual_display/xvfb.py
- seleniumbase/virtual_display/xvnc.py
- setup.py
Use a customized virtual display in headless mode
* This removes the ``pyvirtualdisplay`` requirement
> Use a customized virtual display in headless mode

- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/js_utils.py
- setup.py
Adding w3c Chromedriver support
> Adding w3c Chromedriver support

- examples/test_sb_fixture.py
- examples/test_usefixtures.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Add the "sb" pytest fixture
Usage examples:
```python
def test_sb_fixture_with_no_class(sb):
sb.open("https://google.com/ncr")
sb.update_text('input[title="Search"]', 'SeleniumBase\n')
sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
sb.click('a[title="seleniumbase"]')
class Test_SB_Fixture():
def test_sb_fixture_inside_class(self, sb):
sb.open("https://google.com/ncr")
sb.update_text('input[title="Search"]', 'SeleniumBase\n')
sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
sb.click('a[title="examples"]')
```
> Add the "sb" pytest fixture

- .travis.yml
- README.md
- examples/custom_settings.py
- requirements.txt
- seleniumbase/core/settings_parser.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/utilities/selenium_grid/ReadMe.md
- setup.py
* Add a settings file parser for overriding default SeleniumBase settings
```
pytest my_first_test.py --settings=custom_settings.py
```
> Add a settings file parser for overriding default SeleniumBase settings

- seleniumbase/utilities/selenium_grid/download_selenium_server.py
- setup.py
Use shutil.move() instead of os.rename()
* This was used for downloading the selenium server and placing it in the correct directory
> Use shutil.move() instead of os.rename()

- README.md
- examples/raw_parameter_script.py
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Add a command-line option to maximize the browser window
* Update the default Chrome switches to prevent infobars
> Update browser options

- README.md
- examples/raw_parameter_script.py
- help_docs/customizing_test_runs.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
Use ``--mobile`` to quickly run your tests using Chrome's mobile device emulator with default values for device metrics (CSS Width, CSS Height, Pixel-Ratio) and a default value set for the user agent. To configure the mobile device metrics, use ``--metrics="CSS_Width,CSS_Height,Pixel_Ratio"`` to set those values. You'll also be able to set the user agent with ``--agent="USER-AGENT-STRING"`` (a default user agent will be used if not specified). To find real values for device metrics, [see this GitHub Gist](https://gist.github.com/sidferreira/3f5fad525e99b395d8bd882ee0fd9d00). For a list of available user agent strings, [check out this page](https://developers.whatismybrowser.com/useragents/explore/).
```bash
pytest test_swag_labs.py --mobile
pytest test_swag_labs.py --mobile …
```
> Add mobile device testing to SeleniumBase

- seleniumbase/console_scripts/sb_mkdir.py
I've never used nosetest, but from skimming their website and other directories in your repo, it looks like 'setup.cfg' is being used for configuring nosetest.
> Change nosetest config filename resulting from mkdir cli utility

- README.md
- examples/ReadMe.md
- help_docs/features_list.md
- help_docs/method_summary.md
- requirements.txt
- setup.py
* Bump pytest to minimum version 5.3.2 (Python 3)
> Bump pytest version to >= 5.3.2 (Python 3)

- seleniumbase/core/capabilities_parser.py
* parse json - .json files
* parse ast - raw .py dist
* parse .py as normal if other ways failed
> capabilities_parser parse ast and json

- examples/test_double_click.py
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
> Optimize methods for switching into iframes

- README.md
- examples/ReadMe.md
- examples/raw_parameter_script.py
- examples/timeout_test.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/shared_utils.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* This removes and replaces pytest-timeout, which wasn't thread-safe
Usage (command-line):
``--time-limit=s``  (fail the tests that run longer than "s" seconds)
Usage (in-test):
``self.set_time_limit(s)``  (fail that test if it runs longer than "s" seconds)
* Better detection of multi-thread use
* Update click_visible_elements()
* Some minor refactoring
> Add the ``--time-limit=s`` feature to fail long-running tests

- examples/visual_testing/ReadMe.md
- examples/visual_testing/layout_test.py
- examples/visual_testing/python_home_test.py
- examples/visual_testing/test_layout_fail.py
- examples/visual_testing/xkcd_visual_test.py
- requirements.txt
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- setup.py
* Improve automated visual testing
* Better handling of page scrolling to elements
* Better exception handling around log folders
* Update pytest and wheel
> Automated Visual Testing (2nd edition)

- README.md
- seleniumbase/fixtures/base_case.py
- setup.py
This fixes https://github.com/seleniumbase/SeleniumBase/issues/494
Allow URLS that start with ``://`` for the ``open(URL)`` method
If you copy/paste a URL such as ``://google.com`` into a web browser, the browser automatically converts the URL to ``https://google.com``. But if you use the webdriver ``get(URL)`` method for URLs that start with ``://``, you'll get the following error:
```
selenium.common.exceptions.WebDriverException:
Message: unhandled inspector error:
{"code":-32000,"message":"Cannot navigate to invalid URL"}
```
To fix this, we'll make sure that the SeleniumBase ``open(URL)`` method (which wraps ``driver.get``) automatically adds the ``https`` to URLs that start with ``://`` to prevent the error.
As a bonus, you'll be able to make your Python code lines 5 characters …
> Allow URLS that start with "://" for open()

- README.md
- seleniumbase/console_scripts/sb_install.py
- setup.py
* Using ``v0.24.0`` on Windows to prevent issues
(The default version for other systems is still ``v0.26.0``)
> Update default Geckodriver version on Windows

- examples/translations/portuguese_test_1.py
- seleniumbase/translate/portuguese.py
- setup.py
* Here's the example test:
```python
from seleniumbase.translate.portuguese import CasoDeTeste
class MinhaClasseDeTeste(CasoDeTeste):
def test_exemplo_1(self):
self.abrir_url("https://pt.wikipedia.org/wiki/")
self.verificar_texto("Wikipédia")
self.verificar_elemento('[title="Visitar a página principal"]')
self.atualizar_texto("#searchInput", "Rio de Janeiro")
self.clique("#searchButton")
self.verificar_texto("Rio de Janeiro", "#firstHeading")
self.verificar_elemento('img[alt*="edifícios"]')
self.atualizar_texto("#searchInput", "São Paulo")
self.clique("#searchButton")
self.verificar_texto("São Paulo", "#firstHeading")
self.verificar_elemento('img[src*="Monumento"]')
self.voltar()
self.verificar_verdade("Janeiro" in self.obter_url_atual())
self.avançar()  # noqa …
```
> Add SeleniumBase translations in Portuguese

- requirements.txt
- seleniumbase/core/browser_launcher.py
- setup.py
* The MSEdgeDriver being using must be on the local SeleniumBase Path rather than on the System Path. This prevents permission issues. If it's not there when a test uses the Edge Browser, it will automatically get downloaded into the SeleniumBase drivers folder.
Here's an example of running a SeleniumBase test using the new Edge browser:
```bash
cd examples/
pytest basic_test.py -v --browser=edge
=============================================== test session starts ================================================
platform darwin -- Python 3.7.0, pytest-5.3.5, py-1.8.0, pluggy-0.13.1 -- /Users/michael/.virtualenvs/sbase7/bin/python
metadata: {'Python': '3.7.0', 'Platform': 'Darwin-18.7.0-x86_64-i386-64bit', 'Packages': {'pytest': '5.3.5', 'py': '1.8.0', 'pluggy': '0.13.1'}, 'Plugins': …
```
> Fix MSEdgeDriver automatic installation

- README.md
- examples/capabilities/ReadMe.md
- examples/raw_parameter_script.py
- help_docs/customizing_test_runs.md
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Example:
```bash
pytest basic_test.py --cap-string='{"browserName":"chrome","name":"test1"}' --server="127.0.0.1" --browser=remote
```
(Enclose cap-string in single quotes. Enclose parameter keys in double quotes.)
If using a local Selenium Grid with SeleniumBase, start up the Grid Hub and nodes first:
```bash
seleniumbase grid-hub start
seleniumbase grid-node start
```
For more information on setting browser desired capabilities, see: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/capabilities/ReadMe.md
> Add option to set capabilities with --cap-string=STRING

- README.md
- examples/capabilities/ReadMe.md
- examples/raw_parameter_script.py
- help_docs/customizing_test_runs.md
- requirements.txt
- seleniumbase/config/proxy_list.py
- seleniumbase/console_scripts/run.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Do not use the Chrome flag: "--disable-extensions" (it breaks proxy auth)
* Add cmd option ``--use-auto-ext`` to use Chrome's Automation Extension
* Auto-generate the desired capabilities "name" if ``"*"`` is passed
* Remove unused "portalocker" from Python dependencies
> Fix Chrome proxy with auth; and a few other updates

- examples/test_apple_site.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Update Safari WebDriver launcher
* Set default Safari position and dimensions if not maximized
* Add an example test for the Apple developer site WebDriver instructions
* Add a localized ``set_window_rect(x, y, width, height)``
* Add additional ways to set the web browser's user agent
> Updates to running WebDriver tests with Safari

- help_docs/method_summary.md
- seleniumbase/fixtures/base_case.py
- setup.py
* Now by default waits up to six seconds for the file to appear in the downloads folder.
* The default timeout can be changed.
* This change was made to allow time for a download to complete.
> Update the assert_downloaded_file(file) method

- README.md
- examples/raw_parameter_script.py
- help_docs/customizing_test_runs.md
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Usage: (from **cmd**): ``--crumbs``
``--crumbs`` is only needed when also using ``--reuse-session``, where the same browser session is reused between tests. When not using ``--reuse-session``, every test spins up a completely clean browser session where no cookies are set.
> Add option to delete all cookies between tests that reuse sessions

- .github/workflows/python-package.yml
- azure-pipelines.yml
- docs/requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
> Fix Presenter image display on mobile devices

- seleniumbase/common/obfuscate.py
🐛 bugfix for command line helper, puts the ''s needed for encryption.decrypt() call
> bugfix to  decryption command line helper

- examples/presenter/ReadMe.md
- examples/presenter/my_presentation.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/common/obfuscate.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix Presenter "show_notes" and move arg to different area
* Include requirements.txt with "sbase mkdir DIR"
* Update a Python dependency (rich==3.0.1)
```python
self.create_presentation(name=None, theme="default")
self.add_slide(content=None, image=None, code=None, iframe=None,
content2=None, notes=None, name=None)
self.save_presentation(name=None, filename=None, show_notes=True, interval=0)
self.begin_presentation(name=None, filename=None, show_notes=True, interval=0)
```
> Fix the "show_notes" feature of SeleniumBase Presenter

- README.md
- requirements.txt
- seleniumbase/console_scripts/sb_mkdir.py
- setup.py
* Add color to the "sbase mkdir DIR" success message
* Update a Python dependency (rich==3.0.2)
> Update a success message and a Python dependency

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
When using ``--reuse-session`` (alt: ``--rs``), which allows you to reuse the same browser window between tests, the browser will now continue from the URL it left off at, rather than going to a blank page first.
The exception to this rule is when also using ``--crumbs``, which will clear out cookies and then navigate to a blank page before resuming the tests in the same browser window.
> Keep the current URL when using "--reuse-session"

- .gitignore
- docs/requirements.txt
- examples/ReadMe.md
- examples/chart_maker/ReadMe.md
- examples/chart_maker/my_chart.py
- examples/presenter/ReadMe.md
- help_docs/chart_maker.md
- help_docs/method_summary.md
- mkdocs.yml
- requirements.txt
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- setup.py
SeleniumBase Chart Maker allows you to create HTML charts with Python.<br />
The HighCharts library is used for creating charts.
(Currently only <b>pie charts</b> are supported.)
**Here's a sample chart:**
<a href="https://seleniumbase.io/other/chart_presentation.html"><img width="500" src="https://seleniumbase.io/other/sample_pie_chart.png" title="Screenshot"></a><br>
([Click on the image for the actual chart](https://seleniumbase.io/other/chart_presentation.html))
Here's how to run the example (a chart in a presentation):
```
cd examples/chart_maker
pytest my_chart.py
```
* Update SeleniumBase Tours
** ``parso==0.7.1``
** ``coverage==5.2.1``
** ``rich==4.1.0``
** ``allure-pytest==2.8.17``
** ``pdfminer.six==20200726``
> Add SeleniumBase "Chart Maker" for creating pie charts

- examples/swag_labs_suite.py
- examples/test_login.py
- examples/test_swag_labs.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Standardized widths across different browsers will lead to more consistent results
* Also upgrade the default GeckoDriver version to v0.27.0
> Standardize default starting widths across browsers

- seleniumbase/core/log_helper.py
- setup.py
Example ``basic_test_info.txt`` file from ``latest_logs/``:
```bash
examples.test_fail.MyTestClass.test_find_army_of_robots_on_xkcd_desert_island
----------------------------------------------------
Last Page: https://xkcd.com/731/
Browser: chrome
Timestamp: 1597818345  (Unix Timestamp)
Date: Wednesday, August 19, 2020
Time: 2:25:45 AM  (EST/EDT, UTC-5:00)
----------------------------------------------------
Traceback: File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
testMethod()
File "/Users/michael/github/SeleniumBase/examples/test_fail.py", line 17, in test_find_army_of_robots_on_xkcd_desert_island
self.assert_element("div#ARMY_OF_ROBOTS", timeout=1)
File "/Users/michael/github/SeleniumBase/seleniumbase/fixtures/base_case.py", …
```
> Improve basic logging with date, time, and time-zone info

- seleniumbase/fixtures/base_case.py
Existing logic incorrectly relies upon `By.LINK_TEXT`, so just a small tweak handles it properly.
> click_partial_link_text broken in demo/slow mode

- seleniumbase/fixtures/base_case.py
- setup.py
* Only scroll to iframes before switching to them if the identifier is a string
An iframe identifier can be a string, an int, or a web element, but the scroll_to() method expects a string selector for finding the element first.
> Fix edge case with iframe switching

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Add a custom timeout to methods that click visible elements:
```python
self.click_visible_elements(selector, by=By.CSS_SELECTOR, limit=0, timeout=None)
self.click_nth_visible_element(selector, number, by=By.CSS_SELECTOR, timeout=None)
```
* Also update the ``pip`` requirement: ``pip>=20.2.3``
> Update methods that click visible elements

- seleniumbase/fixtures/xpath_to_css.py
- setup.py
* Handle the case of ``//`` in the middle of an xpath selector
Example:
```python
self.convert_xpath_to_css("//section//p/p//div")
'section p > p div'
```
See the xpath cheatsheet for more details: https://devhints.io/xpath
> Another update to the xpath-to-css converter

- seleniumbase/fixtures/css_to_xpath.py
Subclassing cssselect.GenericTranslator gives us greater control
and better maintainability when converting CSS selectors to XPath.
> Use ConvertibleToCssTranslator in convert_css_to_xpath

- help_docs/method_summary.md
- requirements.txt
- seleniumbase/fixtures/base_case.py
- seleniumbase/translate/chinese.py
- seleniumbase/translate/dutch.py
- seleniumbase/translate/french.py
- seleniumbase/translate/italian.py
- seleniumbase/translate/japanese.py
- seleniumbase/translate/korean.py
- seleniumbase/translate/master_dict.py
- seleniumbase/translate/portuguese.py
- seleniumbase/translate/russian.py
- seleniumbase/translate/spanish.py
- setup.py
* Add ``self.clear(SELECTOR)``
* Add ``self.set_text(SELECTOR, TEXT)``
* Update SeleniumBase translations
* Also set the ``pymysql`` requirement to version ``0.10.1``
* Although most methods that type text already clear out the text field first, and although clearing out the text field can already be done with ``self.type(SELECTOR, "")``, I'm adding the ``self.clear(SELECTOR)`` method to avoid confusion because developers will expect that method to exist.
* Developers would also expect there to be a ``self.set_text(SELECTOR, TEXT)`` method (<i>even though methods already exist that do the same thing</i>) because there's a ``self.get_text(SELECTOR)`` method and a ``self.set_attribute(SELECTOR, ATTRIBUTE, VALUE)`` method, which sound similar.
> Add expected methods

- azure-pipelines.yml
- examples/decryption_test.py
- examples/test_usefixtures.py
- requirements.txt
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/objectify.py
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_mkfile.py
- setup.py
* Update the console scripts tool for generating page objects
* Also optimize ``colorama`` / speed up console scripts output
* Also update the Python ``rich`` requirement to version ``7.0.0``
--------
```bash
** extract-objects **
Usage:
seleniumbase extract-objects [SELENIUMBASE_PYTHON_FILE]
OR:    sbase extract-objects [SELENIUMBASE_PYTHON_FILE]
Output:
Creates page objects based on selectors found in a
seleniumbase Python file and saves those objects to the
"page_objects.py" file in the same folder as the tests.
** inject-objects **
Usage:
seleniumbase inject-objects [SELENIUMBASE_PYTHON_FILE]
OR:    sbase inject-objects [SELENIUMBASE_PYTHON_FILE]
Options:
-c, --comments  (Add object selectors to the comments.)
(Default: No added comments.)
Output:
Takes the page objects found in the …
```
> Update the console scripts' tools for generating page objects

- docs/requirements.txt
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
The following is an example of a Katalon Recorder exported file (WebDriver + unittest format).
It is messy and has unnecessary lines of code to do the task that was recorded.
```python
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re
class Swag(unittest.TestCase):
def setUp(self):
self.driver = webdriver.Firefox()
self.driver.implicitly_wait(30)
self.base_url = "https://www.google.com/"
self.verificationErrors = []
self.accept_next_alert = True
def test_swag(self):
driver = self.driver …
```
> Update the tool for converting SeleniumIDE exports to SB format

- requirements.txt
- seleniumbase/fixtures/base_case.py
- setup.py
* Convert integer inputs to strings before typing text
* Also update the ``cffi`` requirement to ``cffi==1.14.3``
The fix for this is simple:
```python
if type(text) is int or type(text) is float:
text = str(text)
```
This conversion is necessary to prevent errors from occurring in:
```python
if not text.endswith('\n'):
element.send_keys(text)
else:
element.send_keys(text[:-1])
element.send_keys(Keys.RETURN)
```
Most text-typing methods already fixed this. Now they all fix it.
Fixed methods:
```python
self.add_text(selector, text)
self.send_keys(selector, text)  # Same as self.add_text()
```
> Convert int/float inputs to strings before typing text

- requirements.txt
- setup.py
* ``importlib-metadata==1.7.0``
* ``virtualenv>=20.0.31``
This prevents an incompatibility that was occurring when seleniumbase had both ``virtualenv`` and ``importlib-metadata==2.0.0`` installed previously.
> Update Python dependencies

- requirements.txt
- setup.py
* ``pathlib2>=2.3.5;python_version<"3.5"``
This will fix the following issue on systems running an older version of Python: 
``error: pathlib2 2.3.2 is installed but pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" is required by set(['virtualenv'])``
> Backport a fix for older versions of Python

- seleniumbase/__version__.py
- seleniumbase/fixtures/js_utils.py
(This completes the change from the previous release)
A change was made that may impact tests that have alert pop-ups when opening a new page via open or click. This was done to prevent an issue that could occur if developers set custom implicit waits in their code.
The method: wait_for_ready_state_complete() (which SeleniumBase uses for smart-waiting) runs some JavaScript to check that the readyState of the page is "complete" before moving on, but that automatically dismisses alert pop-ups that may appear. If you are expecting to deal with an alert pop-up after going to a new page via self.open(URL) or self.click(SELECTOR), consider using self.driver.get(URL) or self.find_element(SELECTOR).click() instead, which won't use the SeleniumBase smart-waiting that may dismiss alert pop-ups …
> Small update to "wait_for_ready_state_complete()"

- .gitignore
- docs/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- setup.py
* Update default edgedriver and geckodriver versions.
* Handle the new zip format for edgedriver packaging.
* Update Firefox preferences.
* Set ``urllib3`` version to ``1.26.2``.
> Driver updates and more

- .gitignore
- README.md
- examples/ReadMe.md
- examples/raw_parameter_script.py
- examples/test_parse_soup.py
- help_docs/ReadMe.md
- help_docs/customizing_test_runs.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Add the ``--remote-debug`` option to use Chromium's Remote Debugger (from the Chrome DevTools Protocol)
* Also upgrade "pip": ``pip>=20.3.1``
* Also make a few minor updates to ``assert_title()`` and ``get_beautiful_soup()``
See https://chromedevtools.github.io/devtools-protocol/ for more info on the Chrome DevTools Protocol.
When using ``--remote-debug`` on the command line with ``pytest``, you can access the Remote Debugger by going to: http://localhost:9222 while Chromedriver is running.
> Add the "--remote-debug" option to use Chrome's Remote Debugger

- README.md
- examples/example_logs/ReadMe.md
- help_docs/customizing_test_runs.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Combine data from the Dashboard and pytest html reports
* pytest html reports now display a pie chart when also using the Dashboard
* Also update a Python dependency: ``rich==9.5.1``
<h3><img src="https://seleniumbase.io/img/logo6.png" title="SeleniumBase" width="32" /> The SeleniumBase Dashboard:</h3>
The ``--dashboard`` option for pytest generates a SeleniumBase Dashboard located at ``dashboard.html``, which updates automatically as tests run and produce results. Example:
```bash
pytest --dashboard --rs --headless
```
Additionally, you can host your own SeleniumBase Dashboard Server on a port of your choice. Here's an example of that using Python 3's ``http.server``:
```bash
python -m http.server 1948
```
Now you can navigate to ``http://localhost:1948/dashboard.html`` in order to …
> Improve the SeleniumBase Dashboard functionality

- docs/requirements.txt
- examples/presenter/core_presentation.py
- integrations/node_js/ReadMe.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/css_to_xpath.py
- seleniumbase/fixtures/js_utils.py
- setup.py
* Improve Demo Mode initialization
* Update the css-to-xpath selector converter
* Improve Demo Mode for selectors that use ``:contains()``
* Update a JS dependency (``underscore v1.12.0``)
-- ``virtualenv>=20.3.0``
-- ``rich==9.8.0``
> Demo Mode updates and more

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* Make sure that untested Dashboard tests are displayed
* Make sure that the Dashboard refreshes properly on updates
* ``PyYAML>=5.4.1;python_version>="3.6"``
> Fix Dashboard display

- README.md
- docs/requirements.txt
- help_docs/syntax_formats.md
- integrations/google_cloud/ReadMe.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/console_scripts/sb_mkfile.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/utilities/selenium_ide/convert_ide.py
- setup.py
* Fix issue with duplicate dashboard entries caused by the "sb" fixture
* Fix issue with deselected tests appearing in the dashboard.
* Fix issue with console scripts "--help" / "-h" options
* Update output of "sbase convert FILE.py" for Python 3
* Update Python dependencies (urllib3 and coverage)
-- ``urllib3==1.26.3``
-- ``coverage==5.4``
> Fix the dashboard and more

- README.md
- examples/chart_maker/ReadMe.md
- examples/presenter/ReadMe.md
- help_docs/chart_maker.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_mkpres.py
- setup.py
<hr />
<h4><b><code>mkpres</code></b></h4>
* Usage:
``sbase mkpres [FILE.py] [LANGUAGE OPTIONS]``
* Example:
``sbase mkpres new_presentation.py``
* Language Options:
``--en`` / ``--English``    |    ``--zh`` / ``--Chinese``
``--nl`` / ``--Dutch``      |    ``--fr`` / ``--French``
``--it`` / ``--Italian``    |    ``--ja`` / ``--Japanese``
``--ko`` / ``--Korean``     |    ``--pt`` / ``--Portuguese``
``--ru`` / ``--Russian``    |    ``--es`` / ``--Spanish``
* Output:
Creates a new presentation with 3 example slides.
If the file already exists, an error is raised.
By default, the slides are written in English.
Slides use "serif" theme & "fade" transition.
This code can be used as a base boilerplate.
<br />
💠 <b>Here's an example of a presentation that was created by that:</b>
```python
from …
```
> Add the "sbase mkpres" console script for making HTML presentations

- README.md
- examples/offline_examples/test_demo_page.py
- examples/test_demo_site.py
- help_docs/customizing_test_runs.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/config/proxy_list.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/log_helper.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Add the ability to use Chrome extensions with Microsoft Edge
* Add the ability to set a SOCKS4/5 proxy on the command line
* Fix selector issue with assert_link_text() in Demo Mode
* Update the test name displayed in the ``latest_logs/`` info file
* Add the ``seleniumbase methods`` command to console scripts
-- ``setuptools>=53.0.0;python_version>="3.6``
-- ``ipython==7.20.0;python_version>="3.7"``
-- ``virtualenv>=20.4.2``
> Chrome extensions in Edge, Socks4/5 proxy support, and more

- README.md
- examples/boilerplates/ReadMe.md
- examples/boilerplates/classic_obj_test.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/sb_mkdir.py
- setup.py
* Update console scripts:
-- Add new file for ``sbase mkdir DIR``:
-- ``classic_obj_test.py`` was added.
* Bump a Python dependency to a newer version:
-- ``rich==9.11.1;python_version>="3.6"``
```bash
.
├── __init__.py
├── boilerplates/
│   ├── __init__.py
│   ├── base_test_case.py
│   ├── boilerplate_test.py
│   ├── classic_obj_test.py
│   ├── page_objects.py
│   └── samples/
│       ├── __init__.py
│       ├── google_objects.py
│       └── google_test.py
├── my_first_test.py
├── parameterized_test.py
├── pytest.ini
├── requirements.txt
├── setup.cfg
└── test_demo_site.py
```
> Update console scripts (sbase mkdir DIR)

- docs/requirements.txt
- help_docs/customizing_test_runs.md
- integrations/google_cloud/ReadMe.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- setup.py
* ``ipython==7.21.0;python_version>="3.7"``
-- (contains minor fixes and improvements)
* Update the docs / [seleniumbase.io](https://seleniumbase.io/) website:
-- (Rollback ``mkdocs-material`` to fix search)
-- (Change ReadMe files to improve search)
> Update ipython version and docs

- examples/test_swag_labs.py
- examples/upload_file_test.py
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* (The ``choose_file()`` method lets you upload a file to a website using a file-picker.)
```python
self.choose_file(selector, file_path)
self.choose_file('input[type="file"]', "my_dir/my_file.txt")
```
See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/upload_file_test.py for an example test that uses this method.
> Allow the choose_file() method to work on hidden "input" fields

- examples/swag_labs_suite.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* Fix ``self.get_unique_links()``:
-- (Links where the ``src`` starts with ``./`` weren't being processed correctly.)
-- This also fixes impacted methods such as ``self.assert_no_404_errors()``
* Also update a Python dependency:
-- ``setuptools-scm>=5.0.2``
> Fix a method that finds unique links

- README.md
- examples/chart_maker/ReadMe.md
- examples/chart_maker/chart_presentation.py
- examples/chart_maker/pie_charts.py
- examples/chart_maker/test_display_chart.py
- help_docs/chart_maker.md
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Updates for ChartMaker:
-- Add parameters for enabling/disabling labels & legends on charts.
-- Improve some layout and design details for chart generation.
* Updates for Traffic-generator methods:
-- Add parameters to traffic-gen code for lowering the bounce-rate.
---- (Lets you perform a click action as part of traffic-gen methods.)
* Make sure that generated presentations include a progress bar.
-- (This was probably already the default option if not changed.)
* Refactoring:
-- Move coverage and flake dependencies into own ``setup.py`` area.
---- (Install coverage tools with: ``pip install -e .[coverage]``)
---- (Install flake tools with: ``pip install -e .[flake]``)
* Update required and optional Python dependencies:
-- ``setuptools>=54.1.2;python_version>="3.6"``
-- …
> Updates for ChartMaker, Traffic-generator, refactoring, and more

- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
* The HTML-Inspector provides useful information about a web page.
* Example: [examples/test_inspect_html.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_inspect_html.py) (Chromium browsers only)
```python
from seleniumbase import BaseCase
class HtmlInspectorTests(BaseCase):
def test_html_inspector(self):
self.open("https://xkcd.com/1144/")
self.inspect_html()
```
--------
```bash
pytest test_inspect_html.py 
============================ test session starts ============================
platform darwin -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/michael/github/SeleniumBase/examples, configfile: pytest.ini
plugins: html-2.0.1, rerunfailures-9.1.1, xdist-2.2.1, metadata-1.11.0,
ordering-0.6, forked-1.3.0, seleniumbase-1.59.2
collected 1 …
```
> Improve reliability of the HTML-Inspector and JS-loading code

- examples/migration/protractor/ReadMe.md
- examples/migration/protractor/example_spec.js
- examples/migration/protractor/example_test.py
- examples/migration/protractor/input_spec.js
- examples/migration/protractor/input_test.py
- examples/migration/protractor/mat_paginator_spec.js
- examples/migration/protractor/mat_paginator_test.py
🔵 The Protractor/Angular tests from [github.com/angular/protractor/tree/master/example](https://github.com/angular/protractor/tree/master/example) have been migrated to SeleniumBase.
✅ Here's a test run with ``pytest`` using ``--reuse-session`` mode and Chromium ``--guest`` mode:
```bash
$ pytest --rs -v --guest
platform darwin -- Python 3.9.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
metadata: {'Python': '3.9.2', 'Platform': 'macOS-10.14.6-x86_64-i386-64bit', 'Packages': {'pytest': '6.2.3', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '2.0.1', 'rerunfailures': '9.1.1', 'xdist': '2.2.1', 'metadata': '1.11.0', 'ordering': '0.6', 'forked': '1.3.0', 'seleniumbase': '1.59.6'}}
rootdir: /Users/michael/github/SeleniumBase/examples, configfile: pytest.ini
plugins: html-2.0.1, …
```
> Add support for migrating from Protractor to SeleniumBase

- examples/migration/protractor/mat_paginator_test.py
- examples/pytest.ini
- examples/translations/pytest.ini
- pytest.ini
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Improve compatibility on older versions of Python.
* Use the IPython debugger by default (``ipdb``).
-- ``setuptools>=56.2.0;python_version>="3.6"``
-- ``decorator==5.0.7;python_version>="3.5"``
> Compatibility updates and more

- docs/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Fix https://github.com/seleniumbase/SeleniumBase/issues/903 by making the visual layout comparison be done against ``test/name`` instead of ``file_class_test/name``. This lets two different tests (same name, but located in different files/classes) be able to do a visual layout comparison against each other.
* Also update Python dependencies: (``rich==10.2.0;python_version>="3.6"``)
> Update visual baseline folder naming and dependencies

- Dockerfile
While building image noticed that sbase was missing from Dockerfile and was throwing error on:
RUN cd /SeleniumBase && python3 setup.py develop
Nice work you did here - GRATS!
> Update Docker file with sbase

- requirements.txt
- setup.py
Upstream changelog [here](https://cryptography.io/en/latest/changelog/#v3-4)
Closes #920
> Update cryptography to 3.4.7

- examples/test_contains_selector.py
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* Fix issue causing Demo Mode highlighting to not work when using a multi-syllable ``:contains()`` selector.
> Fix issue with the ":contains()" selector and Demo Mode

- README.md
- examples/dialog_boxes/ReadMe.md
- examples/dialog_boxes/dialog_box_tour.py
- help_docs/ReadMe.md
- help_docs/features_list.md
- help_docs/method_summary.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/jqc_helper.py
- seleniumbase/core/style_sheet.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/masterqa/master_qa.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* Add New Feature: SeleniumBase Dialog Boxes.
* Add custom timeout option for ``self.assert_no_404_errors()``.
* Add a default Chromium option for disabling notifications.
* Auto-repair ChromeDriver to sync with Chrome (Mac/Win only).
* Add ``self.is_attribute_present(selector, attribute, value)``.
* Update the error message for fixing a SeleniumBase install.
* Add ``self.wait_for_attribute_not_present()``.
* Add ``self.assert_attribute_not_present()``.
* Add keyboard shortcuts to MasterQA mode.
* Add "--slowmo" as an alternative to "--slow-mode".
* Add "--screenshot" as an alternative to "--save-screenshot".
* Update the favicon link in generated reports.
* Add additional shortcuts for partial_link_text selectors.
* Update methods for getting the link text from selectors.
* Add "&" as a …
> Dialog Boxes and more

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- setup.py
* Fix the automatic chromedriver repair/upgrade script:
-- A folder might need to be created first in some scenarios.
* Auto-upgrade chromedriver on ``"version must be between"``:
-- Previously, only on ``"This version of ChromeDriver only supports"``.
* Refresh Python dependencies:
-- ``cryptography==3.4.8;python_version>="3.6"``
* Update a test created by ``sbase mkdir DIR``.
> Fix & update the automatic ChromeDriver repair/upgrade script

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* This reverts a change made in version ``1.65.0``.
-- The old way (and now) may need Xvfb installed.
> Change how headless Firefox runs on Linux

- docs/requirements.txt
- examples/ReadMe.md
- examples/test_show_file_choosers.py
- help_docs/customizing_test_runs.md
- help_docs/recorder_mode.md
- mkdocs.yml
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/fixtures/base_case.py
- setup.py
* Make improvements around recording "Choose File" events.
* Remove a debugging statement from the previous release.
-- ``filelock==3.3.0;python_version>="3.6"',``
> Recorder updates: Improve "Choose File" processing and more

- help_docs/recorder_mode.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
This is to prevent a duplicate browser action that can occur when a click redirects to a new URL. The Recorder will record a ``click()`` and an ``open()`` action, but if the click already takes the user to the URL being opened, then the browser does not need to call the ``open()`` action separately, and instead should mask the action with ``open_if_not_url()``. This issue was discovered when clicking a link with ``href="https://en.wikipedia.org/"``, which redirected to ``https://en.wikipedia.org/wiki/Main_Page``.
* Better error-handling for the ``open()`` method.
* Update timing logic for the time-limit feature.
* Refresh Python dependencies:
-- ``more-itertools==8.11.0;python_version>="3.5"``
> Update Recorder Mode script-generation

- examples/test_deferred_asserts.py
- help_docs/method_summary.md
- help_docs/recorder_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
SeleniumBase deferred asserts allow you to make multiple assertions on the same page without failing the test after the first failed assert. Instead, you can choose when to process those assertions by calling: ``self.process_deferred_asserts()``.
* Add ``self.deferred_assert_exact_text()``
-- (This is similar to ``self.deferred_assert_text()``, but text must be ``equal``, instead of ``in``.)
* Fix spacing in the console output of deferred assertion failures.
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1065
* Example test: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_deferred_asserts.py
* ``traitlets`` version now only has a lower bound, instead of an exact version.
-- (For Python versions 3.7 and newer. Earlier Python versions still use a …
> Make improvements to the "Deferred Assert" system

- examples/custom_settings.py
- examples/github_test.py
- examples/handle_alert_test.py
- examples/visual_testing/test_layout_fail.py
- mkdocs.yml
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/config/settings.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
* Fix log path issue with visual tests that use the ``sb`` fixture.
* Handle a possible edge case with page loads.
* Make sure highlighting isn't blocked by pop-up alerts.
* Set ``WAIT_FOR_RSC_ON_CLICKS`` to be ``False`` by default.
--  Tests will be faster, but you may need to manually call ``self.accept_alert()`` or ``self.dismiss_alert()`` because previously, waiting for the ``readyState`` of the page to be "complete" might have dismissed alerts automatically due to an existing WebDriver "feature" where calling ``self.execute_script("")`` automatically closes pop-up alerts.
> Fix visual tests that use the "sb" fixture (and more!)

- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
* All part of determining the optimal trade-off between speed and reliability.
> Refactor wait_for_ready_state_complete() and related code

- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
In some scenarios there will be a mixture of requests some will need a proxy some won't. This adds and exposes the proxy bypass option.
I have only tested this in chrome on linux, can you help by suggesting:
- What tests need to be added.
- Documentation to be added.
- Updates for other browsers.
> Expose the proxy bypass option

- integrations/brython/ReadMe.md
- integrations/brython/index.html
- integrations/brython/library.html
> Update the Brython tutorial

- examples/setup.cfg
- examples/wordle_test.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/jqc_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.cfg
- setup.py
* Include ``timeout`` values for Shadow DOM methods:
-- The automatic waiting now works more accurately with ``::shadow`` selectors.
* Update "flake8" style guide implementation:
--  ``ignore=W503,W504`` (line break before or after binary operators)
* Refresh Python dependencies:
-- ``fasteners==0.17.3;python_version>="3.6"``
> Update Shadow DOM methods and style guide implementation

- examples/wordle_test.py
I fixed a minor typographical error in two instances of the "initialize_word_list" function
> fixed typo in initialize_word_list function

- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/selenium_plugin.py
* [Check for service process before driver.quit() on Windows](https://github.com/seleniumbase/SeleniumBase/commit/91c76462e7955e8aac1c5a3ce6c8722eba3d4468)
-- (This prevents a hanging process during cleanup if a driver was already quit. Sometimes people forget that SeleniumBase already quits drivers automatically at the end of tests, so if they manually try to quit a driver during a test, then during the cleanup phase there would be a hanging process on Windows when SeleniumBase tries to quit the driver again. Now, a check is performed to find out if drivers have already been quit.)
-- (In the case of tests that spin up multiple drivers using ``self.get_new_driver()``, in SeleniumBase ``2.4.22``, a new method was added: ``self.quit_extra_driver()``, which quits extra drivers safely, and …
> Perform Windows and Edge optimizations

- examples/hack_the_planet.py
- examples/offline_examples/test_demo_page.py
- examples/proxy_test.py
- examples/pure_python.py
- examples/test_iframes.py
- help_docs/method_summary.md
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
* [Add and update methods related to iframes](https://github.com/seleniumbase/SeleniumBase/commit/43b7e0a525180c25e8bbf3508bf664cb2c90cd20)
Here's the full list of iframe method now (some already existed):
```python
self.switch_to_frame(frame, timeout=None)
self.switch_to_default_content()
self.switch_to_parent_frame()
self.set_content_to_frame(frame, timeout=None)
self.set_content_to_default(nested=False)
self.set_content_to_parent()
```
For an example of these methods in action, see: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_iframes.py
* [Better error-handling output](https://github.com/seleniumbase/SeleniumBase/commit/63e571b86f782ecf4324e6b185e4c0b0104c8690)
If locating an element by the ``:contains("TEXT")`` selector and the element is not found, then the …
> Iframe methods and more

- README.md
- examples/raw_browser_launcher.py
- help_docs/syntax_formats.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/drivers/ReadMe.md
- seleniumbase/fixtures/page_actions.py
- seleniumbase/fixtures/shared_utils.py
* [Allow use of "page_actions" without "BaseCase"](https://github.com/seleniumbase/SeleniumBase/commit/2f56b9cb56947c3377ce839d8622c099b31c7849)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1316
> Allow use of all "page_actions.py" methods without using "BaseCase"

- .github/workflows/python-package.yml
- examples/test_cycle_elements.py
- help_docs/method_summary.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add a shortcut to tab through and click active elements](https://github.com/seleniumbase/SeleniumBase/commit/36e71ece3401cbbac2ecf1cdd031cac274ec1bbe)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1390
Eg. ``self.send_keys("html", "\t\t\t\t\n")``
This assumes that selector is ``html`` , and that the text is a series of tabs (zero or more ``\t``) followed by one ``\n`` at the end of the string.
Examples:
```python
self.send_keys("html", "\t\t\t\t\n")
self.send_keys("html", "\t\n")
self.send_keys("html", "\n")
```
Another way of clicking the active element right now is by calling:
```python
self.click_active_element()
```
> Add a shortcut for cycling through elements with the "tab" key and then clicking the active element

- examples/test_iframes.py
- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add Context Manager frame_switch(frame). ("with" required)](https://github.com/seleniumbase/SeleniumBase/commit/1512f820682f043a3ef81db2afbaa787c825c0f9)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1408
* Example usage: ``with self.frame_switch(frame):``
Here's an example test that demonstrates this feature:
```python
from seleniumbase import BaseCase
class FrameTests(BaseCase):
def test_iframes_with_context_manager(self):
self.open("https://seleniumbase.io/w3schools/iframes.html")
with self.frame_switch("iframeResult"):
self.assert_text("HTML Iframes", "h2")
with self.frame_switch('[title*="Iframe"]'):
self.assert_text("This page is displayed in an iframe", "h1")
self.assert_text("Use CSS width & height to specify", "p")
with …
```
> Add a Context Manager method for switching into iframes using a "with" statement

- examples/hack_the_planet.py
- examples/parameterized_test.py
- examples/test_docs_site.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Handle edge cases after successful actions](https://github.com/seleniumbase/SeleniumBase/commit/ef9eced2913a0ff2774e8e3fe4ed6481271604c4)
--> Resolves https://github.com/seleniumbase/SeleniumBase/issues/1421
--> (Handles ``cannot determine loading status`` and ``unexpected command response``)
* [Refresh dependencies to officially allow Python 3.11 and up](https://github.com/seleniumbase/SeleniumBase/commit/c9a696bbc6109d97b64644dfdae60426275ba878)
--> Resolves https://github.com/seleniumbase/SeleniumBase/issues/1420
> Handle edge cases after successful actions and refresh dependencies

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix intermittent Firefox issue](https://github.com/seleniumbase/SeleniumBase/commit/c7addc1cf9c1b198e84d2c3df64480bf7e618217)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1424
The following intermittent issues should all be handled now:
```
"geckodriver unexpectedly exited"
"Process unexpectedly closed"
"Failed to read marionette port"
"A connection attempt failed"
```
(For situations caused intermittently by the Firefox auto-update process that checks to see if an update is available, whether to perform the update, and then perform the update if applicable.)
> Fix intermittent issue with Firefox and geckodriver

- examples/test_usefixtures.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
- setup.py
* Convert text args to strings before performing text asserts.
--> https://github.com/seleniumbase/SeleniumBase/commit/f512989b9958ce8f9d5f5dfd204a670dae72f705
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1474
* Refresh Python dependencies.
--> https://github.com/seleniumbase/SeleniumBase/commit/5e948cb563cd7a61c951afcd5617e4dae4377d56
> Convert numbers to strings before performing text asserts

- seleniumbase/__version__.py
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
* Fix bug that occurs on Windows with Selenium Grid tests.
--> Fixes an issue where the browser remained open after tests ended.
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1494
* Update output when calling ``sbase get DRIVER``.
--> The slashes should now be correct per Operating System.
--> This also updates error-handling when downloading drivers.
> Fix bug with Windows tests that run on a Selenium Grid

- examples/test_apple_site.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/page_actions.py
* Fix issue with hovering over elements.
--> (For when the selector was NOT CSS and NOT XPath: eg. ID, NAME, CLASS, or LINK_TEXT)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1501
* Fix compatibility issues with tests that run on Safari.
--> (Includes lots of little updates)
> Fix two separate issues regarding hovering and Safari compatibility

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* Proxy authentication takes priority over headless Chromium mode. Since Proxy authentication requires the use of a chromium extension, and since headless Chromium does not support extensions, we have to pick one option over the other if both options are set.
Eg: ``pytest --headless --proxy=user:pass@server:port`` (Then headless mode is skipped)
* Headless Mode is prioritized over Undetected Chromedriver Mode.
Eg. ``pytest --headless --uc`` (Then undetected mode is skipped)
* If the user sets Headless Mode AND Proxy Auth AND Undetected Mode, then Proxy Auth AND Undetected Mode win out while Headless Mode is skipped in that specific situation.
Eg: ``pytest --headless --uc --proxy=user:pass@server:port`` (Then headless mode is skipped)
> Refactoring options ordering

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/log_helper.py
- seleniumbase/core/report_helper.py
- setup.py
* Refactor reports
--> (See below for an example in the new format)
--> ``rich==12.6.0``
--------
Here's an example of a ``basic_test_info.txt`` report in the new format:
```
test_fail.py::FailingTests::test_find_army_of_robots_on_xkcd_desert_island
--------------------------------------------------------------------
Last Page: https://xkcd.com/731/
Duration: 1.59s
Browser: Chrome 105.0.5195.125 / headless
Driver: chromedriver 105.0.5195.52
Timestamp: 1664724374  (Unix Timestamp)
Date: Sunday, October 2, 2022
Time: 11:26:14 AM  (EDT, UTC-05:00)
--------------------------------------------------------------------
Traceback: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run …
```
> Refactor reports

- README.md
- help_docs/method_summary.md
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/fixtures/base_case.py
* Add arg for excluding URLs from assert_no_js_errors()
--------
```python
def assert_no_js_errors(self, exclude=[]):
"""Asserts current URL has no "SEVERE"-level JavaScript errors.
Works ONLY on Chromium browsers (Chrome or Edge).
Does NOT work on Firefox, IE, Safari, or some other browsers:
* See https://github.com/SeleniumHQ/selenium/issues/1161
Based on the following Stack Overflow solution:
* https://stackoverflow.com/a/41150512/7058266
@Params
exclude -->
A list of substrings or a single comma-separated string of
substrings for filtering out error URLs that contain them.
URLs that contain any excluded substring will get excluded
from the final errors list that's used with the assertion.
Examples:
self.assert_no_js_errors()
self.assert_no_js_errors(exclude=["/api.", "/analytics."]) …
```
> Add arg for excluding URLs from assert_no_js_errors()

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/plugins/base_plugin.py
- seleniumbase/plugins/pytest_plugin.py
* When setting headless mode, don't use options.headless
--> https://github.com/seleniumbase/SeleniumBase/commit/63306d83923749e20f2dd22b3ef3332e26246d5e
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1638
* Add ``--env=uat`` (User Acceptance Testing)
--> https://github.com/seleniumbase/SeleniumBase/commit/f48da77f87ab28f905bf86a2de93171ff23482ee
--> This completes changes from version ``4.9.10``
> Headless and env settings

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Make refinements to UC Mode (``--uc``)
--> https://github.com/seleniumbase/SeleniumBase/pull/1801/commits/1757ef27c2a2e0188be78f04470fb6eee42b1006
--> This resolves issues with tests that use multiple tabs in UC Mode
* Also refresh Python dependencies (``pytest-xdist``)
--> https://github.com/seleniumbase/SeleniumBase/pull/1801/commits/100f4738d9cc34f1f9ddfbedded79ee352012047
--> This resolves a ``pytest-xdist`` issue with using ``--dist=worksteal`` in multithreaded mode.
--> (Details: https://github.com/pytest-dev/pytest-xdist/issues/884)
> Refine UC Mode and update pytest-xdist

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* Update minimum ``filelock`` version for a bug-fix
--> New minimum: ``filelock>=3.10.3``
--> https://github.com/seleniumbase/SeleniumBase/commit/d95f7c8a63e361a3cb9a2e82dad46fa3169a1235
> Update minimum "filelock" version

- examples/tour_examples/bootstrap_google_tour.py
- examples/tour_examples/bootstrap_xkcd_tour.py
- examples/tour_examples/driverjs_maps_tour.py
- examples/tour_examples/google_tour.py
- examples/tour_examples/hopscotch_google_tour.py
- examples/tour_examples/introjs_google_tour.py
- examples/tour_examples/maps_introjs_tour.py
- examples/tour_examples/shepherd_google_tour.py
- examples/tour_examples/xkcd_tour.py
- help_docs/method_summary.md
- mkdocs.yml
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/tour_helper.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp.py
- setup.py
* Fix an issue with the remote-debugging-port in `--uc` mode
--> https://github.com/seleniumbase/SeleniumBase/commit/082c692261b8d7c9166ec56a5e774b785ffdb5c6
--> (Uses port `9222` unless changing via `chromium_arg="remote-debugging-port=PORT"`)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1827
* Tours can now be controlled via the `Page-Up`/`Page-Down` keys.
--> Useful if driving a tour as a presentation via a physical clicker device.
* Tours that previously couldn't be controlled via the Arrow keys have now gained that ability.
--> https://github.com/seleniumbase/SeleniumBase/commit/730c6d0367afec612c11daab5736b24bd27f26c9
> Updates and fixes

- help_docs/html_inspector.md
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_behave_gui.py
- seleniumbase/console_scripts/sb_caseplans.py
- seleniumbase/console_scripts/sb_commander.py
- seleniumbase/console_scripts/sb_mkrec.py
- seleniumbase/console_scripts/sb_recorder.py
- seleniumbase/fixtures/base_case.py
* Update GUI Apps
--> https://github.com/seleniumbase/SeleniumBase/commit/e144cecfbf7eca7d39e7c7ffb0549bff484c9d02
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1837
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1838
* Update the HTML Inspector
--> https://github.com/seleniumbase/SeleniumBase/commit/3cc765a9c76acea642c8a9c4f53911369c33a972
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1839
> Update GUI Apps and the HTML Inspector

- examples/test_repeat_tests.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/common/exceptions.py
- seleniumbase/fixtures/base_case.py
- setup.py
* Improve exception-handling when Internet is unreachable
--> https://github.com/seleniumbase/SeleniumBase/commit/f8eff16e9d7f3461e31ae80b5325f730e9d38efd
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/1855
--> https://github.com/seleniumbase/SeleniumBase/commit/074d124f5b0522a2a8017bbe4f9b081f4b0e67a2
> Not-connected exception-handling

- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
* [Fix driver download script](https://github.com/seleniumbase/SeleniumBase/commit/72750da8b03f402220eff0fc77bae301607c3b45)
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1969
> As mentioned in https://github.com/seleniumbase/SeleniumBase/issues/1969, until the Chromium Team resolves https://bugs.chromium.org/p/chromium/issues/detail?id=1466427, it's best to set chromedriver 114 as the maximum version for download, (and to keep using it for Chrome 115+).
> Fix driver download script

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Refactor and fix error-handling on Edge](https://github.com/seleniumbase/SeleniumBase/commit/5d7d7bb3129cfc9140a01365fd9993511abfeaf4)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2041
> Fix error-handling on Edge

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix issue with msedgedriver & Edge on Linux](https://github.com/seleniumbase/SeleniumBase/commit/328e5c9f476998d5486813eebfeee30a8cb916ad)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2076
> Fix issue with msedgedriver & Edge on Linux

- seleniumbase/undetected/reactor.py
This bug took me a while to find, but the main problem it had is that it caused all my logging messages to print with the root logger in the program I use seleniumbase in. I included some code below that will show you the issue.
```py
import logging
import logging.handlers
import time
from seleniumbase import Driver
logger = logging.getLogger("sub")
logger.setLevel(logging.DEBUG)
logger.debug("debug")
driver = Driver(undetectable=True, uc_cdp_events=True)
driver.quit()
time.sleep(3)
logger.debug("Should not show up")
```
> Fix log message on exception in UC Reactor

- help_docs/ReadMe.md
- mkdocs.yml
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Upgrade to selenium 4.14.0](https://github.com/seleniumbase/SeleniumBase/commit/04c047f4a0cab1539a736b6b7f1657ae02f277f1)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2174
* [Modernize Mobile Mode](https://github.com/seleniumbase/SeleniumBase/commit/3c1efe3788bb111d85d875deaf91bdd821466557)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2170
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2169
* [Add "--ftrace" to "SB()" command-line options](https://github.com/seleniumbase/SeleniumBase/commit/4dc8ca72cc8d6e7aff93a97475dbb4ff6d89605e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2171
* [Refactor UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/9b8f8a00178715c28973963f2b1ca352041c32 …
> Upgrade `selenium` and Mobile Mode

- examples/hack_the_planet.py
- examples/presenter/edge_presentation.py
- examples/raw_mobile.py
- examples/raw_uc_mode.py
- examples/test_skype_site.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_driver.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Fix issue with mobile mode and user agents](https://github.com/seleniumbase/SeleniumBase/commit/f622897b243f41740a9bc7de2859b28ab6bd3b8b)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2181
* [Improve "driver.highlight(selector)" functionality](https://github.com/seleniumbase/SeleniumBase/commit/14e62c4aa6f366bfcfaa31af6e9ec4c67d6a594e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2182
* [Fix issue that caused "PytestAssertRewriteWarning"](https://github.com/seleniumbase/SeleniumBase/commit/9a9dcbdf873a785d83ab40d60d33e040da1991b2)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2183
* [Add UC Mode customization options](https://github.com/seleniumbase/SeleniumBase/commit/9445bb1dc426e874e760ea6692d3476933d38455)
--> …
> Various updates and fixes

- seleniumbase/__version__.py
- seleniumbase/fixtures/xpath_to_css.py
* [Fix the XPath-to-CSS converter](https://github.com/seleniumbase/SeleniumBase/commit/2b9cd90e4709c0270e3dc9d1fd05bc4a62b32ac3)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2193
--> (There was an issue caused by dashes in HTML tags.)
> Fix the XPath-to-CSS converter

- help_docs/method_summary.md
- help_docs/recorder_mode.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Prevent the "Enhanced ad privacy" pop-up](https://github.com/seleniumbase/SeleniumBase/commit/11be78556f0062120525148fad91d7f795885bf1)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2201
--> (This issue only appeared when setting a custom `user-data-dir`)
* Also update some unrelated documentation
> Prevent the "Enhanced ad privacy" pop-up from appearing

- examples/boilerplates/samples/google_test.py
- examples/boilerplates/samples/test_page_objects.py
- examples/capabilities/ReadMe.md
- examples/capabilities/sample_cap_file_SL.py
- examples/raw_parameter_script.py
- examples/test_todomvc.py
- help_docs/customizing_test_runs.md
- help_docs/desired_capabilities.md
- help_docs/how_it_works.md
- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/fixtures/page_utils.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
- seleniumbase/utilities/selenium_grid/ReadMe.md
- setup.py
* [Add more options for capturing CDP logs](https://github.com/seleniumbase/SeleniumBase/commit/ab2de3146919093c24e841a631a4c023e63d839e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2220
* [Update WebRTC preferences](https://github.com/seleniumbase/SeleniumBase/commit/4bfd8c952a0699c4b1392a838e62fe8b8503363e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2218
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2217
* [Fix link-checking methods](https://github.com/seleniumbase/SeleniumBase/commit/5af9e029551443a8e36f30498b82649f595bd88f)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2219
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/6f168c6fd7634275aa38f3d654910d …
> Update logging options, WebRTC preferences, and link-checking methods

- examples/hack_the_planet.py
- examples/raw_uc_mode.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Fix a Windows issue with UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/71a45904c3d5b65b18d19f3be872345f08e40309)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2289
* [Improve compatibility with Appium](https://github.com/seleniumbase/SeleniumBase/commit/fdf3071c6822cd012aa3ec06cdb7a717600a739a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2287
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/395c9241832099f6cac7bcf58f1ab1309fe3c787)
> A few small updates

- README.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/constants.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Add "breakpoint" option for reconnecting in UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/bcf0fb565b58400526a35f53de3fc7bd972d662c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2384
Other unrelated changes:
* [Add "brave" to valid Chromium binary_location filenames](https://github.com/seleniumbase/SeleniumBase/commit/a9a3156471841de8a0375385be2ddb9a369e722d)
* [Update coverage version in optional dependencies](https://github.com/seleniumbase/SeleniumBase/commit/6bfea20ab6e4f3fa60836e36c653b2447b2385ae)
--------
Currently, some UC Mode methods let you set a custom `reconnect_time` / `timeout` (in seconds) to specify how long the driver should be disconnected from Chrome to prevent detection before reconnecting again. The new plan here is to add an …
> Add a `"breakpoint"` option for reconnecting in UC Mode

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Expand firefox_pref="KEY:VALUE" to allow URLs as VALUEs](https://github.com/seleniumbase/SeleniumBase/commit/c7914993e36e01a62f5879d4beae0463d0082782)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2386
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2387
* Also: [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/b1fa3c5523383670f013993bf0d794de85182316)
> Expand firefox_pref to allow URLs as VALUEs in KEY:VALUE pairs

- examples/capabilities/ReadMe.md
- examples/capabilities/sample_cap_file_BS.py
- examples/capabilities/sample_cap_file_BS.yml
- help_docs/chinese.md
- help_docs/desired_capabilities.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/capabilities_parser.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add YAML option for parsing capabilities](https://github.com/seleniumbase/SeleniumBase/commit/69700823949895e97c87eb3203a2de3e44981a48)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2403
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2401
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/060190a7d8eff07424e2df50600e55486df286b8)
> Add YAML option for capabilities

- README.md
Allure Report documentation is moved from https://docs.qameta.io/allure/ to https://allurereport.org/docs/. The suggested change updates the link.
> Update Allure report site

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/constants.py
- setup.py
* [Refresh dependencies](https://github.com/seleniumbase/SeleniumBase/commit/d3a1d6a13ebfb4d96b39735d27d063fc4bcdd472)
* [Update the default UC Mode reconnect_time](https://github.com/seleniumbase/SeleniumBase/commit/1fddb33056aada9cba6c1fead34cb2ecc999dff2)
> Refresh dependencies and UC Mode timing

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix user-agent string in headless UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/044fc46eba9237876d4e406434411bc78192a270)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2523
> Fix user-agent string in headless UC Mode

- examples/boilerplates/samples/google_test.py
- examples/boilerplates/samples/test_page_objects.py
- examples/github_test.py
- examples/proxy_test.py
- examples/rate_limiting_test.py
- examples/shadow_root_test.py
- examples/test_apple_site.py
- examples/test_canvas.py
- examples/test_chromedriver.py
- examples/test_hack_search.py
- examples/test_multiple_drivers.py
- examples/test_override_driver.py
- examples/test_override_sb_fixture.py
- examples/test_shadow_dom.py
- examples/test_verify_chromedriver.py
- examples/youtube_search_test.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/cb0c375ffb3c95d7e3fa5e9065357b1811ab6f3b)
* [Update example tests](https://github.com/seleniumbase/SeleniumBase/commit/7c1bf93056d84a2a6c9ec3a758300608d584d5ff)
> Refresh dependencies and examples

- examples/presenter/multi_uc.py
- examples/presenter/uc_presentation.py
- examples/raw_call.py
- examples/raw_multi_drivers.py
- examples/raw_turnstile.py
- examples/raw_uc_mode.py
- examples/verify_undetected.py
- help_docs/uc_mode.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/sb_driver.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
* [Improve non-pytest script processing during pytest collection](https://github.com/seleniumbase/SeleniumBase/commit/1a2a910bb6cffba720a80e88b914231e086448d0)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2575
* [Fix an issue with driver.highlight(element) when setting "loops"](https://github.com/seleniumbase/SeleniumBase/commit/49a8f98027155deaac8e0310fbbfeb6eab978390)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2576
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/0deefa37d79c684a76b62de31756b7b0262835d6)
* [Update UC Mode docs](https://github.com/seleniumbase/SeleniumBase/commit/aeedbd745f52480209c683f5918ab2777192cbbe)
> Improve pytest collection and more

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/detect_b_ver.py
- setup.py
* [Fix browser-version-detection on Windows](https://github.com/seleniumbase/SeleniumBase/commit/9a9c2537a347add831de97a7db846b9161786b2d)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2603
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/c50f33588782464fc57e67a807e5ab33ccc4389c)
> Fix browser-version-detection on Windows

- seleniumbase/__version__.py
- seleniumbase/core/detect_b_ver.py
- seleniumbase/fixtures/base_case.py
* [Refactor the code](https://github.com/seleniumbase/SeleniumBase/commit/ccb9e38aadc9cf75e51a1e3cd6f627ada307960b)
> Light refactoring

- examples/raw_cdp_logging.py
- examples/raw_form_turnstile.py
- examples/raw_nopecha.py
- examples/raw_turnstile.py
- examples/test_download_files.py
- examples/uc_cdp_events.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/constants.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/undetected/webelement.py
- setup.py
* [Make UC Mode great again](https://github.com/seleniumbase/SeleniumBase/commit/1067d88ee8ea52f3a905cd854176399d2de134b6)
* [Update example tests](https://github.com/seleniumbase/SeleniumBase/commit/4820d73b066500e543dd78eebde0869f5e7ffac2)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/a719c970aeb232db1454f24b9fecc4a123225dd6)
> Upgrade UC Mode

- examples/raw_bing_captcha.py
- examples/raw_nopecha.py
- examples/raw_pixelscan.py
- examples/test_docs_site.py
- help_docs/uc_mode.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/webelement.py
- setup.py
* [Make refinements to UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/06e00f010ca4bf96d020ce55387f23374bb7b645)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/39b09e4f7ef3d834ec70987dd31ba09cf382a0c2)
* [Update the documentation](https://github.com/seleniumbase/SeleniumBase/commit/9c0e7f87057ebcab71945eb2372b37116504ff0c)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/e4f1fde1cb67232c5f8c28dd7647eae8d999d628)
> UC Mode refinements and more

- README.md
- examples/raw_nopecha.py
- help_docs/uc_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/undetected/webelement.py
- setup.py
* [Fix issue with escaping characters in UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/060ca1c976a97d6720582cb44cbe473ad8bc0f2a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2666
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/fabec481debd4b128aeee38ae4357ed593e3fc1e)
* [Update an example](https://github.com/seleniumbase/SeleniumBase/commit/91be834da70786d774d674295784430e47393537)
* [Update the documentation](https://github.com/seleniumbase/SeleniumBase/commit/263b1380deb683528104470026961cddf36c56d5)
> Fix issue with UC Mode

- seleniumbase/__version__.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/sb_manager.py
* [Add command-line shortcuts for SB() and Driver()](https://github.com/seleniumbase/SeleniumBase/commit/97d6b3a8ca2667645bbe5e85011ba59dbb22cd90)
--> This adds the following missing command-line shortcuts for `SB()` and `Driver()` formats:
------> `--gui` / `--headed`
------> `--xvfb` (for the `SB()` format only)
------> `--pls=none` (Page Load Strategy)
------> `--pls=eager` (Page Load Strategy)
------> `--pls=normal` (Page Load Strategy)
> Add command-line shortcuts for `SB()` / `Driver()` formats

- examples/raw_performance_logs.py
- examples/test_highlight_elements.py
- help_docs/method_summary.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* [Add / improve methods that highlight elements](https://github.com/seleniumbase/SeleniumBase/commit/b3d47bd574af3727bb62869005d6221b692a2d76)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2747
--> Now, `self.highlight(selector)` can also accept a `WebElement` for the `selector`.
--> Adds `self.highlight_elements(selector)`, which highlights all elements that match the `selector`.
> Add / improve methods that highlight elements

- examples/hack_the_planet.py
- examples/raw_order_tickets.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Update sb.open_new_window() for UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/fc3f55c2c29da34980ab1b7f6b33940ce0c41a39)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2823
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/e25ddb737e68b6d8567fe7d1834e6861ae5d508b)
> Update a method and refresh dependencies

- Dockerfile
- examples/raw_cdp_logging.py
- examples/raw_form_turnstile.py
- examples/raw_nopecha.py
- examples/raw_turnstile.py
- examples/uc_cdp_events.py
- help_docs/uc_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/shared_utils.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/sb_manager.py
- setup.py
* [Add support for uc_gui_handle_cf() in the Driver() formats](https://github.com/seleniumbase/SeleniumBase/commit/3d9f0ea6cf86f5fa05531f3344ec9abd2d373cfa)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2879
* [Update the Dockerfile](https://github.com/seleniumbase/SeleniumBase/commit/197cf5fbd017204422095092b8f142d0af032bc8)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2881
* [Update UC Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/f67449a9d5bb5fa509c6e8163b8f27220c3eeb61)
--> https://github.com/seleniumbase/SeleniumBase/issues/2880
* [Update the UC Mode documentation](https://github.com/seleniumbase/SeleniumBase/commit/12e64a167b52ed133ee98998e1137bccb3b7f7a2)
* [Do some …
> UC Mode updates and refactoring

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/page_actions.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Improve multithreading in UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/a2cb6b3f69b0d5b3de009fa384fc4339d005a6d7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2883
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/cd9c0ac605083a56ddf67cce5b7454cec9687ed7)
> Improve multithreading in UC Mode

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/page_actions.py
* [Fix Windows bug in UC Mode for uc_gui_handle_cf()](https://github.com/seleniumbase/SeleniumBase/commit/2655d10018a33ea211aba8e05fc04aee25ece6fc)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2889
> Fix Windows thread-locking bug in UC Mode

- examples/raw_gui_click.py
- examples/raw_order_tickets.py
- examples/raw_uc_mode.py
- help_docs/method_summary.md
- help_docs/uc_mode.md
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add UC Mode clicking methods](https://github.com/seleniumbase/SeleniumBase/commit/ac3a9bed3940cab1ed87adb3d4d209dfbd995c29)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2910
* [Add more methods to SB](https://github.com/seleniumbase/SeleniumBase/commit/4dcbf3c22f915cd4843c7a8bbed988a6708f31d7)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/de75ec61353d0bf228f2ad22c66841dfe55da26a)
* [Update the documentation](https://github.com/seleniumbase/SeleniumBase/commit/afcd439408e15df500077a95dfabc697ed7b8c7d)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/5a06b39dd7023c44938f92103ac40fedbcad860a)
> Add UC Mode clicking methods that use PyAutoGUI

- examples/raw_recaptcha.py
- examples/raw_uc_mode.py
- help_docs/method_summary.md
- help_docs/uc_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/5872a660d619e6312d6a592306e5e6fb858a3356)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/65c15ab1e5202d813e57da2a3f5dce7620489926)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/719b6b44a777611e878c2fef657dc4e238594c08)
> Make UC Mode more advanced

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Refactor UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/4624edd2d9c1a4de6272890a598fa9816d4482f8)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/d636b8e19855d52016f71dd8348baea7bfaf3b02)
> Refactor UC Mode and refresh dependencies

- examples/raw_form_turnstile.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/8941335d68f1496a365412ed5b0f3ff32a664250)
* [Update an example](https://github.com/seleniumbase/SeleniumBase/commit/f007dcf607293c42dd2b36a76339c2dd68ec8b7f)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/ff1cc8de73dc3bbf35844a88989a4be99237d6c1)
> Handle UC Mode edge cases

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Update default Chromium options](https://github.com/seleniumbase/SeleniumBase/commit/59e77ec53f5158aa86669f39326bccccefeac1e2)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2959
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/e1006e44a5f85a5da45263b7648778c81ed84a8a)
--> Includes upgrading `pytest` (to `8.3.2`), which fixes an issue for Conda users.
--> (More info: https://github.com/pytest-dev/pytest/issues/12652)
> Update options and dependencies

- examples/raw_ahrefs.py
- examples/raw_form_turnstile.py
- examples/raw_games.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Handle update to form turnstiles](https://github.com/seleniumbase/SeleniumBase/commit/d10164ce14db73d606e4e87f32fee2a9527ab811)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2966
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/e2f69b7e3cefdac3ea1e42fe7e3ff424718c1ce4)
> Handle update to form turnstiles

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Handle CAPTCHA updates](https://github.com/seleniumbase/SeleniumBase/commit/4250c6db21df9bf633cecc2206ba277c128d7903)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2973
> Handle CAPTCHA updates

- examples/raw_cdp_logging.py
- examples/raw_form_turnstile.py
- examples/raw_gui_click.py
- examples/raw_pyautogui.py
- examples/raw_recaptcha.py
- examples/uc_cdp_events.py
- help_docs/method_summary.md
- help_docs/uc_mode.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
* [Allow Mobile Mode "device_pixel_ratio" to use floats](https://github.com/seleniumbase/SeleniumBase/commit/db012234fc9760cc41357f8c7011e1cd9f454a75)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2985
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/8621dfeef6581f95c9efbd4be7db8d9fe11a3a4d)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2986
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/fda2ffe865c6757ace96a5356093df593935ffb2)
* [Update the UC Mode docs](https://github.com/seleniumbase/SeleniumBase/commit/0f9592e0d81a3d2d23be6f71ae25a9b8cdfe50e8)
> Update Mobile Mode and UC Mode

- help_docs/uc_mode.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* [Prevent memory leaks for Windows users](https://github.com/seleniumbase/SeleniumBase/commit/2dedf26719b800e9ed2fcdf29bdc0afbbd813999)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2991
* [Improve the UC Mode experience on Windows](https://github.com/seleniumbase/SeleniumBase/commit/af8e11dd50d17d0b3acb4ee0c52f2119ac4ddf80)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2998
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/2999
* [Improve error-handling for "by"-selection](https://github.com/seleniumbase/SeleniumBase/commit/b0909b3beccb33e64dd17fb1ca829fe186cd961f)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3003
* [Update the default geckodriver version to …
> Various updates

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/ReadMe.md
- seleniumbase/console_scripts/run.py
- seleniumbase/console_scripts/sb_mkfile.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Fix UC Mode for CAPTCHA updates](https://github.com/seleniumbase/SeleniumBase/commit/670bd2fe88b57782081a4ae9ef86b215dbc9071e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3077
* [Add "--uc" option for "sbase mkfile FILE.py"](https://github.com/seleniumbase/SeleniumBase/commit/58820f660288cdde75ec7e7fb3c4615f9bd1fbca)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3078
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/7dc129e53c2b321eb877e71690d74b10e9063271)
> UC Mode upgrades

- examples/raw_cf.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/974731063bc6b218c915e7a07e22e6f5633ac3bc)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3084
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/4a598ac2de614ad12ff8341c2bdb918e9d68a348)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/df1ad4bc062ed3308e7ec33036a7b882b25a7596)
> More UC Mode updates

- README.md
- examples/presenter/uc_presentation.py
- examples/presenter/uc_presentation_3.py
- examples/raw_ahrefs.py
- examples/raw_cf.py
- examples/raw_order_tickets.py
- examples/raw_pixelscan.py
- help_docs/thank_you.md
- help_docs/uc_mode.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Improve UC Mode methods](https://github.com/seleniumbase/SeleniumBase/commit/111f8eefbd3c6597ef1f37775e6f3ad81a604b91)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3093
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/fab150b88193abc73389f8bc40441a2084b00bb0)
> Update UC Mode and examples

- README.md
- examples/custom_settings.py
- examples/hack_the_planet.py
- examples/raw_ahrefs.py
- examples/raw_nopecha.py
- examples/test_geolocation.py
- help_docs/customizing_test_runs.md
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/behave/behave_sb.py
- seleniumbase/config/settings.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
* [Improve UC Mode reliability](https://github.com/seleniumbase/SeleniumBase/commit/d0b34aa85f29de6ed945ffa3bd0379a5c7df9c9d)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3120
* [Update UC Mode compatibility](https://github.com/seleniumbase/SeleniumBase/commit/70806d5e2b245f850a29c3e322665952c2e7d475)
* [Change default settings for AngularJS waits](https://github.com/seleniumbase/SeleniumBase/commit/e34928fa7f7e2377eb568b5a009779e4bcd96277)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3122
* [Add option to wait for AngularJS to load](https://github.com/seleniumbase/SeleniumBase/commit/ecc253b110923a760394c4280fca737dd399d352)
> Refactor UC Mode and JS waits

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Update UC Mode for Tab + Spacebar](https://github.com/seleniumbase/SeleniumBase/commit/fd8d3b7d36f8c7c63a8977d4cd4875b17ddd8d37)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3131
----> (This fixes `sb.uc_gui_handle_captcha()`)
> UC Mode Tab + Spacebar (with reload as needed)

- examples/test_download_files.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Update Firefox options and settings](https://github.com/seleniumbase/SeleniumBase/commit/fd3ca4eca18af15a8bb36fc9dd59ad8a7bc528b7)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3170
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3171
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/56382ae193b69495d93579d5cc9f855cea494837)
> Update Firefox options and settings

- seleniumbase/__init__.py
- seleniumbase/__version__.py
- seleniumbase/console_scripts/run.py
- seleniumbase/fixtures/shared_utils.py
* [Fix console output on Windows](https://github.com/seleniumbase/SeleniumBase/commit/3fb258b8dbb01fd351aa2f3f3c9871155f191664)
> Fix console output on Windows

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_async.py
- examples/cdp_mode/raw_footlocker.py
- examples/cdp_mode/raw_hyatt.py
- examples/cdp_mode/raw_pokemon.py
- examples/cdp_mode/raw_req_async.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
* [Update UC Mode / CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/7c924acd9a594b2c4d22c135326b456e3f5339bb)
* [Update CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/dd6659be868ca6ad1aa1662f7d6d6ed458ea0b81)
* [Update the CDP Mode docs](https://github.com/seleniumbase/SeleniumBase/commit/40dd528d5e30cea95c729e5a644ddc9b3b7b5e50)
> CDP Mode - Patch 1

- examples/cdp_mode/raw_async.py
- examples/cdp_mode/raw_cdp.py
- examples/cdp_mode/raw_cdp_with_sb.py
- examples/verify_undetected.py
- pyproject.toml
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/sb_manager.py
- setup.py
* [Update UC Mode](https://github.com/seleniumbase/SeleniumBase/commit/dbf82861126231637c3fae2d4bca7c9f0f3f63b7)
--> This improves the fix / workaround for the `user-data-dir` issue on Chrome-130 in UC Mode.
--> This also includes an update that allows loading cross-origin cookies with the `load_cookies()` method.
* [Include CDP Mode in packages](https://github.com/seleniumbase/SeleniumBase/commit/3258db07f84f592dad60ae42cfa51a8ff9c6d16c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3219
* [Update examples for CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/101d2af4d5b09e70fb66c1f5b0278caab178a733)
> CDP Mode - Patch 2

- examples/cdp_mode/raw_easyjet.py
- examples/cdp_mode/raw_hyatt.py
- examples/cdp_mode/raw_nike.py
- examples/github_test.py
- examples/hack_the_planet.py
- examples/raw_recaptcha.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- setup.py
* [Fix issue where Chrome was blocking new tabs as pop-ups](https://github.com/seleniumbase/SeleniumBase/commit/5ba82844dab267b3e7c4ec2fc0b045f01fa265b5)
* [Prevent issue caused by running Selenium via cron jobs](https://github.com/seleniumbase/SeleniumBase/commit/6a1cce663e4a6f79d05d26dc932d4b97a2f517aa)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/323dcb4bcf96c21b786861283102fe190528dbb2)
* [Add a new CDP Mode example](https://github.com/seleniumbase/SeleniumBase/commit/5d834bf37f1003a3b3774ecaf09cb65ce68d178b)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/39682e209bf16c1828c59930750181756e52f7b9)
> CDP Mode - Patch 7

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_demo_site.py
- examples/presenter/uc_presentation.py
- examples/presenter/uc_presentation_3.py
- examples/presenter/uc_presentation_4.py
- help_docs/uc_mode.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/undetected/cdp_driver/browser.py
- setup.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/8decf8dc460eba5e836904fffcfb32e569545a80)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3297
--> (This also includes other fixes) 
* [Add a new CDP Mode example](https://github.com/seleniumbase/SeleniumBase/commit/68a51565f4ac884352b710c1222facfc5a743d42)
* [Update presentations](https://github.com/seleniumbase/SeleniumBase/commit/b80af58e29cf1481d18200a24e6b3b2eb8a954f2)
* [Update the documentation](https://github.com/seleniumbase/SeleniumBase/commit/47c2379136410f372a165dc1c1cf08383ddffd76)
* [Refresh optional dependencies](https://github.com/seleniumbase/SeleniumBase/commit/6311726d9f38ae1cb16133a77690f48e346f2ba6)
> CDP Mode - Patch 14

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_hyatt.py
- examples/presenter/uc_presentation_4.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/cdp_driver/tab.py
- setup.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/ac26b08942ac24e8127bd1336c3c42103453ea9a)
* [Update CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/26b63ca157ca28d950b2accbffb3d82b11f3b869)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/762a006eb83702113d876d1e02c4ead7e3b5c8fa)
> CDP Mode - Patch 16

- examples/cdp_mode/raw_radwell.py
- examples/cdp_mode/raw_tiktok.py
- examples/cdp_mode/raw_united.py
- examples/master_qa/pytest.ini
- examples/migration/raw_selenium/pytest.ini
- examples/pytest.ini
- examples/translations/pytest.ini
- help_docs/method_summary.md
- help_docs/recorder_mode.md
- pyproject.toml
- pytest.ini
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* [Mostly pytest updates](https://github.com/seleniumbase/SeleniumBase/commit/54320aa84b7840b7d154658b9cb906ec9b200f5e)
* [Handle edge cases regarding lock files](https://github.com/seleniumbase/SeleniumBase/commit/9cec4346b9615f12e017fe0c27f269c677e8c76f)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/2f8a8d7546e12e7514d132575ef7faa95dd38563)
* [Update the docs](https://github.com/seleniumbase/SeleniumBase/commit/fe3b985717565d28e01a883cd5b4112dfa1f17d1)
* [Add CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/967f54fe8f653bf26c94cf59ecd036960996829b)
> Mostly `pytest` updates

- .gitignore
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_mkdir.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* [Update pytest reports](https://github.com/seleniumbase/SeleniumBase/commit/9a23859779b46a016b6d91729891c35f2dc110c3)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3318
--> A copy of completed `pytest` reports will get saved to `last_report.html`
* [Handle edge cases with lock files](https://github.com/seleniumbase/SeleniumBase/commit/7ba93608b0cd0af00fd8d4dfcc3a92674e3e6bf2)
> `pytest` report updates

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_fingerprint.py
- examples/cdp_mode/raw_publication.py
- examples/cdp_mode/raw_res_sb.py
- examples/raw_recaptcha.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/core/settings_parser.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/cdp_driver/config.py
- seleniumbase/undetected/cdp_driver/element.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/320b125097652ba867de1fe31b2f511959b5aee4)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3329
--> This also adds `get_attribute()` to CDP Mode
* [Update the settings parser](https://github.com/seleniumbase/SeleniumBase/commit/a03ccc9ba574c5ec11bd2cd7e0eb8df644f397cc)
* [Update the CDP Mode docs](https://github.com/seleniumbase/SeleniumBase/commit/b88024efb7c0accd94af28e0dc8ae285254d397f)
* [Update CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/edd32cb3e45a5929370ae50a8f55ac4f55dfaec5)
> CDP Mode - Patch 18

- examples/cdp_mode/raw_socialblade.py
- seleniumbase/__version__.py
- seleniumbase/undetected/cdp_driver/element.py
* [Fix a bug in CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/025e64700b186807e3e9931b6ba8e68b340e59a9)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3337
* [Add a new CDP Mode example](https://github.com/seleniumbase/SeleniumBase/commit/6c65993dea6c06d910d48398b16753cd92461d02)
> CDP Mode - Patch 20

- LICENSE
- examples/cdp_mode/ReadMe.md
- examples/presenter/hacking_with_cdp.py
- examples/raw_skype_mobile.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- setup.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/04719e50309be94ee74b6569998dde8445036e69)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3389
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/cd38f864f9839fd2add059607a9d945326c7dd4e)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/78b180ffb2aadd7e259f1b2ebafade811409c941)
> CDP Mode - Patch 23

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_bestwestern.py
- examples/presenter/uc_presentation_4.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/patcher.py
* [Update the UC Mode driver patcher](https://github.com/seleniumbase/SeleniumBase/commit/9903899a435a9b7719edec664f969446355bef6e)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3406
* [Update uc_gui_handle_captcha()](https://github.com/seleniumbase/SeleniumBase/commit/4a24e268323d672f7ec67a2cc7f37f53205a6c1d)
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/279ca9399a2dfce2a3299f8132f2e71faaec3812)
> CDP Mode - Patch 24

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/undetected/patcher.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/d4639a27b863d90d646011ce86f8139acae9bcfc)
--> The conversion about it was on Discord: https://discord.gg/EdhQTn3EyE
> CDP Mode - Patch 27

- help_docs/customizing_test_runs.md
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/pytest_plugin.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/plugins/selenium_plugin.py
- setup.py
* [Add shortcuts for using "Chrome for Testing" and "Chrome-Headless-Shell"](https://github.com/seleniumbase/SeleniumBase/commit/c167a23a06793319a84997f2e7b251b6334116b0)
--> `--cft` / `cft=True` ******** `--chs` / `chs=True`
* [Error early when combining UC Mode with Chrome-Headless-Shell](https://github.com/seleniumbase/SeleniumBase/commit/a6c0493a3ddccc798aa3a9549197514d2490d843)
--> You can't combine UC Mode with Chrome-Headless-Shell
--> Chrome-Headless-Shell is incredibly fast, but not stealthy
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/02d13c66b44e66f83ab362c7d38b54af8d5ec9cc)
> Add shortcuts and error-handling

- examples/cdp_mode/raw_cdp_drivers.py
- examples/multiple_cdp_drivers.py
- examples/raw_cdp_drivers.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/__init__.py
- setup.py
* [Fix methods for switching drivers in CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/b64cbd818c453a9bdb0a0132157c897b0be59200)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3465
* [Improve output when Rosetta 2 is missing/needed on macOS](https://github.com/seleniumbase/SeleniumBase/commit/51ec1c7244ed1a2e5fd1273bd255a32939c1b641)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3466
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/d9ce2d027bb7b8963a0f774d21a76ad52a6b5ec0)
> CDP Mode - Patch 28

- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Fix issue with using multiple extension directories](https://github.com/seleniumbase/SeleniumBase/commit/9e0f98cef1e1e8274aaeae33b68371c94128a78c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3468
> Fix issue with loading multiple extensions

- examples/cdp_mode/raw_indeed.py
- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/page_utils.py
- setup.py
* [Update acceptable URL schemes](https://github.com/seleniumbase/SeleniumBase/commit/1bc579b00627651d51054f73e5020e9cf260d605)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/ece3784a380cfd51d9e0454ddaa81706da65104e)
* [Add a new CDP Mode example](https://github.com/seleniumbase/SeleniumBase/commit/9e7c5c16256a6d7b4cd3765f165df8ea7a031eaf)
> URL schemes and dependencies

- examples/cdp_mode/raw_multi_async.py
- examples/cdp_mode/raw_multi_cdp.py
- seleniumbase/__version__.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- seleniumbase/undetected/cdp_driver/tab.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/de9735a9e1cdd6194c954378fba7c688f9805357)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3479
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3480
* [Add new CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/5ea003ff80115600cda7cbe7ad933db163cafe40)
> CDP Mode - Patch 29

- seleniumbase/__version__.py
- seleniumbase/core/detect_b_ver.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/browser.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/ac29db516d82fded699e9fdb178f00782494a7ff)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3489
> CDP Mode - Patch 31

- examples/proxy_test.py
- seleniumbase/__version__.py
- seleniumbase/config/proxy_list.py
- seleniumbase/core/proxy_helper.py
----
* [Add more proxy schemes](https://github.com/seleniumbase/SeleniumBase/commit/22db6a303cac0f03f0638e6d417794090c138f15)
--> This affects the Chrome extension that allows for proxy-with-auth.
--> This modifies the [StackOverflow solution](https://stackoverflow.com/a/35293284) for proxy extensions.
--> The update: `scheme: ["http", "https", "socks4", "socks5"]`
> More proxy schemes

- examples/boilerplates/samples/google_test.py
- examples/boilerplates/samples/test_page_objects.py
- examples/cdp_mode/raw_priceline.py
- examples/presenter/uc_presentation_4.py
- examples/raw_google.py
- examples/raw_gui_click.py
- examples/raw_pyautogui.py
- examples/test_cdp_ad_blocking.py
- mkdocs_build/requirements.txt
- seleniumbase/__version__.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/webelement.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/32960b6f77d53a93238efd38b21bf59b8907d6be)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3512
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/d028e3be820fcc304f9466c9b6c3e3261ac5ed93)
> CDP Mode - Patch 33

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_cf.py
- examples/cdp_mode/raw_pokemon.py
- seleniumbase/__version__.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/js_utils.py
- seleniumbase/plugins/pytest_plugin.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/1019b488f8804d266d8a806271c9935ed624bf3d)
* [Fix issue with post_message(message)](https://github.com/seleniumbase/SeleniumBase/commit/4b249b8bdec7009b4c43d2bc0da44ab3d799fba3)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3563
* [Fix issue with "pytest -h"](https://github.com/seleniumbase/SeleniumBase/commit/b8d308d3b4bf1b898dee070a277f65070da90dac)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3561
* [Update CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/25365eface9e84091dfe09ec067a47afb6267628)
> CDP Mode: Patch 37

- examples/cdp_mode/raw_chatgpt.py
- examples/cdp_mode/raw_elal.py
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
* [Update assert_no_js_errors()](https://github.com/seleniumbase/SeleniumBase/commit/f30187da55ebed6fd27c32b14c5e0b1a9065870c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3596
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/1b02e839e7d202b451bb66addde78f83a805c625)
> Update the JS checker

- examples/cdp_mode/ReadMe.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/tab.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/9bde7e73871da081b2426f8e039379af1f160fee)
--> Related to handling PDFs
> CDP Mode: Patch 43

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- setup.py
* [Add keyword arg shortcuts for get_new_driver()](https://github.com/seleniumbase/SeleniumBase/commit/f8f30105411a8a8db845fc90172a953aa83dfaa9)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/71a0446121038fe64cee16b1a6fcfb03dd5d5553)
> Shortcuts and dependencies

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/console_scripts/sb_install.py
- setup.py
* [Update geckodriver](https://github.com/seleniumbase/SeleniumBase/commit/72832a57e543a70b826c411e13529845dbb42806)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/ef7e1f1bac66504ee9c6d20795ff00bbf3e1d56a)
> Update geckodriver and dependencies

- seleniumbase/__version__.py
- seleniumbase/undetected/__init__.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/ca84cdddc091b4cb216d3eccc3dab4299cd04e6d)
> CDP Mode: Patch 44

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/0da7d0fbcaffaca0a3b5b0465d4852fcdbefd57f)
> Refresh dependencies

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp.py
- setup.py
* [Reduce memory usage](https://github.com/seleniumbase/SeleniumBase/commit/4e9fbd65bfb75832c49f49f042d5f1a675bf9041)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/7798808d8ca88172e5e81843cadfa2f6ffe8cfe5)
> Mostly memory improvements

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/connection.py
- setup.py
* [Fix a memory leak in CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/2040014f0d3a222adedc5a6f82564b706fa06e28)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3685
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/9cc66b9146491eeee5181b1839d9b75b960d8360)
> Fix CDP Mode memory leak

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_pixelscan.py
- examples/cdp_mode/raw_theaters.py
- examples/cdp_mode/raw_walmart.py
- examples/presenter/uc_presentation_4.py
- examples/raw_cdp_logging.py
- examples/raw_pixelscan.py
- seleniumbase/__version__.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/connection.py
* [Improve CDP multithreading](https://github.com/seleniumbase/SeleniumBase/commit/c500466ecb885ad02d3cad5037d976bc9c9c1b68)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3692
* [Update examples](https://github.com/seleniumbase/SeleniumBase/commit/ee8b82df82b3013417db91e3ba052cd0102ad090)
> Improve CDP Multithreading

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/browser.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- seleniumbase/undetected/cdp_driver/tab.py
- setup.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/a3d6e6218cc5028b85d507895be9f95eb406d8e0)
--> Includes various fixes and optimizations
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/03d7dc0c1b1a00675e586c42ae73a09890aa1716)
> CDP Mode: Patch 45

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_tab_switching.py
- examples/cdp_mode/raw_timezone_sb.py
- help_docs/method_summary.md
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/cdp_driver/browser.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- seleniumbase/undetected/cdp_driver/tab.py
* [Add ability to change fingerprints in realtime](https://github.com/seleniumbase/SeleniumBase/commit/ab56241aa79b4fd7462e552e7235ddad39df2c8a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3708
* [Add example of changing settings in realtime](https://github.com/seleniumbase/SeleniumBase/commit/876b462fee0b887c09dbbb58e58355e1f6066140)
> Realtime fingerprint changing

- seleniumbase/__version__.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/connection.py
- seleniumbase/undetected/cdp_driver/tab.py
* [Improve CDP memory usage](https://github.com/seleniumbase/SeleniumBase/commit/e625c21fc7be567616cf6b0d19ab9f2ba573311f)
If you're spinning up a lot of CDP Mode web browsers in a loop within a Python file, then you'll use less memory because resources will get freed up at the end of the `with SB() as sb:` block, rather than after you've reached the end of the Python file (where regular garbage collection takes place).
Related discussion: https://github.com/seleniumbase/SeleniumBase/discussions/3679 - (Special thanks @felipehertzer)
> Improve CDP memory usage

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/__init__.py
- seleniumbase/undetected/cdp_driver/connection.py
- setup.py
* [Update CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/6d8744dbde7fc4a9745cbefe61aec4c6675df504)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3715
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3716
To avoid memory leaks in CDP Mode, upgrade to Python 3.12 (or newer).
There's an issue with `asyncio` in earlier versions, which makes the memory leak unavoidable.
Due to that, there's not much that can be done from the SeleniumBase side to avoid that specific memory leak if you're using an older version of Python. (Only CDP Mode is affected, and only for Python 3.11 and older versions.) That's because CDP Mode using `asyncio` in the backend, even if you don't call any `async` functions directly.
> CDP Mode: Patch 46

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/cdp_driver/tab.py
- setup.py
* [Update UC Mode / CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/55879efe3a38236db41aff07ef6dbc0ffc7fc3d1)
--> (Includes 3 bug fixes)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3765
--> This resolves an issue with combining UC Mode and CDP Mode methods.
--> This resolves an issue that may occur when overriding the driver.
* [Update error messages to handle a 1-second timeout](https://github.com/seleniumbase/SeleniumBase/commit/06babf49920afbbf24adb75fb39f749b0c1eb743)
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/05de46464dfc2a3ea5576099976a3a40595cd3fa)
> CDP Mode: Patch 48

- examples/migration/protractor/input_test.py
- examples/migration/protractor/mat_paginator_test.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_driver.py
- seleniumbase/plugins/driver_manager.py
- seleniumbase/plugins/sb_manager.py
- seleniumbase/undetected/cdp_driver/browser.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- seleniumbase/undetected/cdp_driver/connection.py
* [Add IntelliSense autocompletion support](https://github.com/seleniumbase/SeleniumBase/commit/1db2f1c0be874943bca8ab5d84988fbf63a57a42)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3791
* [Fix locale settings](https://github.com/seleniumbase/SeleniumBase/commit/a3cc95c290dcc9620d7142fd623f5e5551611b18)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3787
> Support IntelliSense and fix locale settings

- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/plugins/pytest_plugin.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/0c2ab28af29d7530f17c496cde1197e53b1e7b57)
* [Update pytest_plugin.py to handle changes in pytest](https://github.com/seleniumbase/SeleniumBase/commit/98f5f9d923f22245d75229bbffcc8cdbf22759ad)
* [Update cookie methods that use "expiry"](https://github.com/seleniumbase/SeleniumBase/commit/8471ef1788a412312ded68610f8356f8c6ce4812)
> Update dependencies and refactor

- mkdocs_build/requirements.txt
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/fixtures/base_case.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- setup.py
* [Fix PyAutoGUI targeting issue on Linux](https://github.com/seleniumbase/SeleniumBase/commit/f46cca90af3b08f485ebf4c46602c0e55e07319b)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3854
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/4ed8cc777107eedf4a25a233174250f513dcf8dd)
> Fix PyAutoGUI targeting issue on Linux

- requirements.txt
- seleniumbase/__version__.py
- setup.py
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/fa34b634e89fa4b8aa548906956f9da1b06b037b)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/3877
> Fix debugger on Python 3.13

- examples/raw_bing_captcha.py
- seleniumbase/__version__.py
- seleniumbase/core/browser_launcher.py
* [Update UC Mode / CDP Mode CAPTCHA-bypass](https://github.com/seleniumbase/SeleniumBase/commit/4c870580640fff5870d9fa82670c725ebeb4a673)
> CDP Mode: Patch 51

- examples/cdp_mode/ReadMe.md
- examples/cdp_mode/raw_consecutive_c.py
- examples/cdp_mode/raw_hyatt.py
- examples/cdp_mode/raw_nordstrom.py
- examples/cdp_mode/raw_walmart.py
- examples/presenter/uc_presentation_4.py
- requirements.txt
- seleniumbase/__version__.py
- seleniumbase/core/sb_cdp.py
- seleniumbase/undetected/cdp_driver/cdp_util.py
- setup.py
* [Add command-line shortcuts for Pure CDP Mode (sb_cdp)](https://github.com/seleniumbase/SeleniumBase/commit/c770fa893679fd9c729486c129b03f34e073841a)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/4008
* [Improve certain types of clicks in CDP Mode](https://github.com/seleniumbase/SeleniumBase/commit/c0949e3d289a2043caf0e629a72b42460435c5b3)
--> May improve clicking of `<div>` and `<input>` elements
* [Refresh Python dependencies](https://github.com/seleniumbase/SeleniumBase/commit/2c0ef1cbfb184cd93b759ebd5f07b2353d1e940c)
--> This resolves https://github.com/seleniumbase/SeleniumBase/issues/4009
* [Update CDP Mode examples](https://github.com/seleniumbase/SeleniumBase/commit/0341c5e99fe1618fc3793ef5d4a5b7d88d66b800)
----
For Pure CDP Mode (`sb_cdp`), we're adding …
> CDP Mode: Patch 63
